function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	/*Массив названий тестов*/
	var taskNameArray=new Array();
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/
/*************************************************************/
//Тесты по немецкому языку	
/*************************************************************/	
/*ЗНО-2014 немецкий язык. Основной тест. I сессия*/
	if(testName==znoGer2014Main)
	{
		testLength=43;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/ger\/img\/test2014main\/';
		testTitle = znoName+"2014"+znoGerName;
		testDetails=mainName;
		answerLanguage="eng";
		gradeArray=new Array("100.0","100.5","101.0","102.0","103.0","105.5","109.0","113.0","117.0","121.0","125.5","129.0","132.5","135.5","138.0","140.5","142.5","144.0","145.0","146.5","147.5","148.5","149.5","150.5","151.5","152.5","153.5","154.5","155.5","156.5","157.5","158.5","159.5","160.5","161.0","162.5","163.0","164.0","165.0","166.5","167.5","168.5","169.5","170.5","172.0","174.0","176.0","179.0","182.0","185.0","186.5","188.5","191.5","194.0","197.0","199.0","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var lesen1="1\nKaum eine größere Stadt ohne Musical – so sieht es zurzeit in Deutschland aus. Kein Wunder, dass viele Jugendliche von einer Bühnenkarriere träumen. Im Nürnberger Verein „Musical Bahnhof“ können sie den ersten Schritt machen. Junge Talente, die Musical-Darsteller werden wollen, bekommen dort Unterricht in Gesang, Tanz und Schauspiel. Eine Garantie für die Karriere bekommt man allerdings nicht. Zu viele Bewerber stehen vor den Toren der Schauspielschulen. Harte Eingangsprüfungen sind die Regel. Doch träumen ist ja nicht verboten. \n\n2\nAnna besucht die elfte Klasse des Bach-Musikgymnasiums in Berlin. Sie möchte später professionelle Musikerin werden. Ihre Chancen stehen gut. Die Schule bietet den Schülern eine deutschlandweit einzigartige Ausbildung. Hochschulprofessoren der Berliner Musikhochschulen unterrichten hier. Auf dem Stundenplan stehen Klavier und ein weiteres Instrument nach Wahl, Musiktheorie und Gehörbildung. Für Anna ist die Ausbildung im Bach-Gymnasium sehr wichtig. Nach dem Abitur möchte sie ein Gesangstudium in den USA beginnen. Sie war schon auf Konzertreisen in Lissabon, in Israel, in Ungarn und in anderen Ländern unterwegs. \n\n3\nEva, 19, lernt, wie man Geigen baut. Mit ihr besuchen 45 junge Leute eine Fachschule für Musikinstrumentenbau in Klingenthal. Diese Schule bildet ihre Schüler in drei Jahren im Bau von Geigen, Mandolinen oder Akkordeons aus. Die Schüler benötigen Kreativität, Musikalität und handwerkliches Geschick. Zum Herstellen einer Geige werden Handwerkstechniken genutzt, die bereits Jahrhunderte alt sind. Der Bau umfasst rund 500 Arbeitsgänge und dauert ca. 1–3 Monate. \n\n4\nJedes Jahr nach den Abiturprüfungen ist es soweit. Mit einem witzigen Wettbewerb beschließen die Abiturienten ihre Schulzeit. Die Teams müssen zahlreiche Aufgaben lösen. Jede Sekunde ist kostbar. Doch es geht nicht darum, wer am schnellsten laufen kann. Schnelles Denken, gute Ideen und Kreativität sind gefragt. Es gibt viele Rätsel und sportliche Aufgaben. Auch das gerade gelernte Abiturwissen ist noch einmal nützlich. Ein Test mit Wissensfragen über die Stadt, die Schule und Fächer wie Biologie und Latein bringt wichtige Punkte. \n\n5\nWer weiß schon, was Vater und Mutter bei der Arbeit machen? Bei der bundesweiten Aktion „Girls’ Day“ erhielten Mädchen einen Tag schulfrei. Sie konnten einmal ihren Eltern im Beruf über die Schulter schauen. Stolz präsentierten Väter und Mütter ihren Töchterchen ihren Arbeitsplatz und erklärten ihnen genau, womit sie ihr Geld verdienen. Das Ziel dieser Aktion: Die Schülerinnen sollten sich die Betriebe anschauen, um sich Ideen für ihre Berufswahl zu holen. Denn immer noch wählen viele Mädchen typische Frauenberufe, obwohl sie bessere Schulabschlüsse als Jungen haben.";
		var lesen2="\tGut im Geschäft\n\n\tSie sind jung, erfolgreich und voller Ideen. Ihre Geschäfte laufen prima, doch Verträge dürfen sie nicht abschließen, Geld verdienen auch nicht. Das Einzige, was die jungen Unternehmer als Lohn erhalten, ist eine Menge Erfahrung und eine Vorstellung von ihrem zukünftigen Berufsleben. \n\n\tSchülerfirmen gibt es an vielen Schulen. Meist verkaufen ihre Mitarbeiter belegte Brötchen, Obst, Getränke und Süßigkeiten in den Pausen. Doch die Schüler haben oft noch ganz andere Ideen, für die es sich lohnt, ein eigenes Unternehmen zu gründen. 80 Schülerinnen aus dem Bundesgebiet stellen nun in Berlin ihre Geschäftsideen vor. Besucher können Waren kaufen und bestellen – wie bei einer echten Fachmesse. \n\n\tDoch es geht nicht so sehr ums Fachgeschäftliche, sondern ums Soziale. Die Schüler lernen kreativ zu sein, zusammen zu arbeiten, es geht also um Disziplin und Zuverlässigkeit. Und so müssen auch die sieben Mädchen von der Schule am Zwickauer Damm in Rudow lernen Rechnungen zu schreiben, Bilanzen zu führen und den Arbeitstag zu organisieren. Cosmo Girls nennen sich die Schülerinnen, die Haar- und Nagelpflege in ihrer Schule anbieten. Jeden Freitag öffnen die Mädchen von 9 bis 12.30 Uhr ihren Salon im Schulhaus. Sie waschen Mitschülern die Haare, massieren Hände und schminken Mädchen. Die Dienstleistungen kosten höchstens 1,50 Euro, Erwachsene zahlen das Doppelte. Alles wird für Shampoo, Spray und Schminke ausgegeben. Da bleibt kein Geld übrig. \n\n\tVor der Wirtschafts- und Finanzkrise haben junge Unternehmer keine Angst. Schülerfirmen funktionieren anders als gewöhnliche Firmen. Sie brauchen kein Startkapital, oft übernehmen Lehrer und Betreuer die finanzielle Verantwortung. Mitschüler, Lehrer und Eltern sind treue Kunden. Oft ist so eine Schülerfirma ein Plus-Minus-Null-Geschäft mit nicht so hohen Ausgaben. Doch die Pflichten werden verteilt wie in der realen Arbeitswelt. \n\n\tMit 15 Jahren ist Benedikt Franke Geschäftsführer der Firma Elegancia, die Bio-Kaffee aus Nicaragua verkauft. Seit April 2009 kümmern sich zwölf Schüler der 9. und 10. Klassen einer privaten Gesamtschule in Berlin um den Verkauf des Kaffees in umliegenden Läden, auf Messen und Tagungen. Der ist zwar teurer als gewöhnlicher Kaffee aus dem Supermarkt, „doch die Bauern, die Kaffeebohnen anbauen, bekommen dafür einen gerechten Preis“, sagt Franke.";
		var anzeigeA="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Gartenpfleger/in gesucht</p><p style='text-align:center;  color:black;'>Ich suche einen Gartenpfleger für ca. 2–3 Std./Woche.</p><p style='text-align:center;  color:black;'>Ich freue mich auf Ihren Anruf. Telefon: 457 66 90</p></div>";
		var anzeigeB="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Hausmeisterfirma</p><p style='text-align:center;  color:black;'>sucht eine/n Arbeiter/in</p><p style='text-align:center;  color:black;'>für die Grünanlagenpflege mit Festanstellung.</p><p style='text-align:center;  color:black;'>Telefon: 089/793 40 87</p></div>";
		var anzeigeC="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:black;'>Zuverlässige</p><p style='text-align:center;  color:red;'>Bürokraft</p><p style='text-align:center;  color:black;'>ab sofort gesucht.</p><p style='text-align:center;  color:black;'>Teilzeit, 20 Std./Woche Tel. 089/14 38 333</p></div>";
		var anzeigeD="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Fleißige(r) Hausmeister(in)</p><p style='text-align:center;  color:black;'>mit handwerklichem Geschick gesucht.</p><p style='text-align:center;  color:black;'>Festanstellung, ca. 35 Std./Woche</p><p style='text-align:center;  color:black;'>Ihre Bewerbung senden Sie bitte an:</p><p style='text-align:center;  color:black;'>s.schmidt@hv-schmid.de</p></div>";
		var anzeigeE="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Bürokauffrau/-mann</p><p style='text-align:center;  color:black;'>Wir suchen eine(n) Auszubildende(n).</p><p style='text-align:center;  color:black;'>Voraussetzungen: Realschulabschluss, ordentliches Erscheinungsbild und korrektes Auftreten.</p><p style='text-align:center;  color:black;'>Ihre schriftliche Bewerbung richten Sie bitte an K&M Gebäudereinigung GmbH, Breite Str. 7, 01917 Kamenz</p></div>";
		var anzeigeF="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:black;'>Für unser junges Team suchen wir</p><p style='text-align:center;  color:red;'>Bürohelfer in Vollzeit.</p><p style='text-align:center;  color:black;'>Flexibilität, sowie gutes Zahlenverständnis setzen wir voraus.</p><p style='text-align:center;  color:black;'>Schriftliche Bewerbung an:</p><p style='text-align:center;  color:red;'>VSR Verlag Service GmbH</p><p style='text-align:center;  color:black;'>Alexandra Scholz, Kistlerhofstr.170, 81379 München</p></div>";
		var anzeigeG="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:black;'>Wir suchen</p><p style='text-align:center;  color:red;'>1 Auszubildende(n) zum KFZ-Mechatroniker (PKW)</p><p style='text-align:center;  color:black;'>Voraussetzung: guter Hauptschulabschluss, oder Realschulabschluss</p><p style='text-align:center;  color:black;'>Vorhandene Praktikumsnachweise sind von Vorteil.</p><p style='text-align:center;  color:red;'>www.waldforst.net</p></div>";
		var anzeigeH="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Hausmeisterfirma</p><p style='text-align:center;  color:black;'>sucht einen Aushilfsfahrer für 2–3 Tage in der Woche, vorzugsweise mit eigenem PKW.</p><p style='text-align:center;  color:black;'>Telefon: 089/793 40 87</p></div>";
		var skateboarding="Mein Hobby ist Skateboarding\n\nAnna lebt in der ostfriesischen Stadt Aurich. Sie hat dieses Jahr Abitur gemacht und will Fotografie studieren. Sie erzählt: – Vor fünf Jahren, (17)____________, bin ich zum ersten Mal zusammen mit meinem Bruder auf der Straße geskatet. Seitdem skate ich so oft wie möglich. Durch das Skateboarden reise ich auch viel. Manchmal fahre ich zu den Wettbewerben, (18)____________. Das Skaten ist ein wichtiger Teil meines Lebens. Es ist ein unvergleichliches Gefühl, (19)____________. Mir gefällt, (20)____________. Die meisten Skateboarder sind männlich. Zum Glück gibt es immer mehr Mädchen, so wie mich.\n\n(21)__________, verbindet uns alle die Liebe zum Skateboarden. Seit letztem Jahr machen wir jedes Jahr eine „Girls’ Skate Tour“ mit Skaterinnen aus ganz Europa. Die Videos und Fotos, (22)____________, begeistern auch die männlichen Skater. Das Negative am Skateboarden sind ab und zu die Verletzungen.";
		var tornados="\tAuf der Suche nach Tornados\n\n– Mein Name ist Heiko Wichmann. Ich liebe extremes Wetter und interessiere (23)__________ für seltene und gefährliche Wetterphänomene.\n\nIch bekomme professionelle Wetterkarten mit verschiedenen Daten, (24)__________ ich analysieren muss. Und dann weiß ich, wo ich diesmal (25)___________ werde. Besonders toll finde ich (26)__________ Wetter, zum Beispiel Gewitter. Ich filme dann, mache Fotos und gebe mit (27)__________ Handy wichtige Daten an den deutschen Wetterdienst weiter.\n\nIch habe auch schon zwei Tornados gesehen. Einer war 2007 nördlich (28)__________ Berlin, der andere 2009 in Brandenburg. Dieses Wetterphänomen hat (29)__________ in Deutschland schon immer gegeben.\n\nIch lese alte Zeitungen und Kirchenchroniken und versuche, Informationen über Tornados (30)__________. Ich habe gerade sechs historische Fotos vom 1. August 1877 gefunden. An beschädigten Gebäuden sieht man, (31)__________ dort ein Tornado war. Er muss sehr stark gewesen sein. Solche historischen Wetterdaten (32)__________ untersucht und publiziert.";
		var buchmessen="\tDie Geschichte der Buchmessen\n\nDie größte Buchmesse ist die in Frankfurt am Main. So wie sie heute noch (33)__________, wurde sie im Jahr 1949 vom „Börsenverein des Deutschen Buchhandels“ (34)__________. Es (35)__________ sie jedes Jahr im Oktober. Aber diese Messe hat eine über 500-jährige Geschichte. Im Jahr 1455 (36)__________ Johannes Gutenberg in Mainz (nicht weit weg von Frankfurt) den Buchdruck. Einige Buchdrucker (37)__________ in der Folge die Frankfurter Messe zu einem Handelszentrum für gedruckte Bücher.";
		var Fahrrad="\tFahrrad fahren\n\nMehr Sport treiben, Geld sparen, die Umwelt schonen – das möchte fast jeder. Kein Wunder, dass immer mehr Deutsche für ihre täglichen Wege zur Arbeit oder zum Einkaufen vom Auto aufs Fahrrad (38)__________ . Etwa 80 Prozent aller (39)__________ haben mindestens ein Fahrrad. Das hat zum Teil praktische (40)__________: Wer Rad fährt, gibt kein Geld für Benzin aus, muss nicht nach einem Parkplatz suchen oder im (41)__________ stehen. Und gesund ist Radfahren auch. Darüber hinaus ist Fahrradfahren cool: Wer Rad fährt, präsentiert sich als (42)__________.";
		var taskNumber=1;
		/*задание №1 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 1<br>LESEN<p style='text-align:justify;  color:black;'>Welche Überschrift passt zu Kurztext №1:</p><p>Kaum eine größere Stadt ohne Musical – so sieht es zurzeit in Deutschland aus. Kein Wunder, dass viele Jugendliche von einer Bühnenkarriere träumen. Im Nürnberger Verein „Musical Bahnhof“ können sie den ersten Schritt machen. Junge Talente, die Musical- Darsteller werden wollen, bekommen dort Unterricht in Gesang, Tanz und Schauspiel. Eine Garantie für die Karriere bekommt man allerdings nicht. Zu viele Bewerber stehen vor den Toren der Schauspielschulen. Harte Eingangsprüfungen sind die Regel. Doch träumen ist ja nicht verboten.</p>";
			zadanieArray[1]="Fachschule für einen anspruchsvollen Beruf";
			zadanieArray[2]="Musical-Unterricht für talentierte Jugendliche";
			zadanieArray[3]="Mehr Informationen für Mädchen bei der Berufswahl";
			zadanieArray[4]="Lustige Prüfung nach dem Abitur";
			zadanieArray[5]="Praktikum im Betrieb der Eltern";
			zadanieArray[6]="Zukunftspläne der Abiturienten";
			zadanieArray[7]="Schauspielschule auf dem Nürnberger Bahnhof";
			zadanieArray[8]="Weitgehende Pläne der Gymnasiastin";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.1";	
		/*задание №2 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 1<br>LESEN<p style='text-align:justify;  color:black;'>Welche Überschrift passt zu Kurztext №2:</p><p>Anna besucht die elfte Klasse des Bach-Musikgymnasiums in Berlin. Sie möchte später professionelle Musikerin werden. Ihre Chancen stehen gut. Die Schule bietet den Schülern eine deutschlandweit einzigartige Ausbildung. Hochschulprofessoren der Berliner Musikhochschulen unterrichten hier. Auf dem Stundenplan stehen Klavier und ein weiteres Instrument nach Wahl, Musiktheorie und Gehörbildung. Für Anna ist die Ausbildung im Bach-Gymnasium sehr wichtig. Nach dem Abitur möchte sie ein Gesangstudium in den USA beginnen. Sie war schon auf Konzertreisen in Lissabon, in Israel, in Ungarn und in anderen Ländern unterwegs.</p>";
			zadanieArray[1]="Fachschule für einen anspruchsvollen Beruf";
			zadanieArray[2]="Musical-Unterricht für talentierte Jugendliche";
			zadanieArray[3]="Mehr Informationen für Mädchen bei der Berufswahl";
			zadanieArray[4]="Lustige Prüfung nach dem Abitur";
			zadanieArray[5]="Praktikum im Betrieb der Eltern";
			zadanieArray[6]="Zukunftspläne der Abiturienten";
			zadanieArray[7]="Schauspielschule auf dem Nürnberger Bahnhof";
			zadanieArray[8]="Weitgehende Pläne der Gymnasiastin";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.2";	
		/*задание №3 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 1<br>LESEN<p style='text-align:justify;  color:black;'>Welche Überschrift passt zu Kurztext №3:</p><p>Eva, 19, lernt, wie man Geigen baut. Mit ihr besuchen 45 junge Leute eine Fachschule für Musikinstrumentenbau in Klingenthal. Diese Schule bildet ihre Schüler in drei Jahren im Bau von Geigen, Mandolinen oder Akkordeons aus. Die Schüler benötigen Kreativität, Musikalität und handwerkliches Geschick. Zum Herstellen einer Geige werden Handwerkstechniken genutzt, die bereits Jahrhunderte alt sind. Der Bau umfasst rund 500 Arbeitsgänge und dauert ca. 1–3 Monate.</p>";
			zadanieArray[1]="Fachschule für einen anspruchsvollen Beruf";
			zadanieArray[2]="Musical-Unterricht für talentierte Jugendliche";
			zadanieArray[3]="Mehr Informationen für Mädchen bei der Berufswahl";
			zadanieArray[4]="Lustige Prüfung nach dem Abitur";
			zadanieArray[5]="Praktikum im Betrieb der Eltern";
			zadanieArray[6]="Zukunftspläne der Abiturienten";
			zadanieArray[7]="Schauspielschule auf dem Nürnberger Bahnhof";
			zadanieArray[8]="Weitgehende Pläne der Gymnasiastin";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.3";	
		/*задание №4 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 1<br>LESEN<p style='text-align:justify;  color:black;'>Welche Überschrift passt zu Kurztext №4:</p><p>Jedes Jahr nach den Abiturprüfungen ist es soweit. Mit einem witzigen Wettbewerb beschließen die Abiturienten ihre Schulzeit. Die Teams müssen zahlreiche Aufgaben lösen. Jede Sekunde ist kostbar. Doch es geht nicht darum, wer am schnellsten laufen kann. Schnelles Denken, gute Ideen und Kreativität sind gefragt. Es gibt viele Rätsel und sportliche Aufgaben. Auch das gerade gelernte Abiturwissen ist noch einmal nützlich. Ein Test mit Wissensfragen über die Stadt, die Schule und Fächer wie Biologie und Latein bringt wichtige Punkte.</p>";
			zadanieArray[1]="Fachschule für einen anspruchsvollen Beruf";
			zadanieArray[2]="Musical-Unterricht für talentierte Jugendliche";
			zadanieArray[3]="Mehr Informationen für Mädchen bei der Berufswahl";
			zadanieArray[4]="Lustige Prüfung nach dem Abitur";
			zadanieArray[5]="Praktikum im Betrieb der Eltern";
			zadanieArray[6]="Zukunftspläne der Abiturienten";
			zadanieArray[7]="Schauspielschule auf dem Nürnberger Bahnhof";
			zadanieArray[8]="Weitgehende Pläne der Gymnasiastin";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.4";		
		/*задание №5 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 1<br>LESEN<p style='text-align:justify;  color:black;'>Welche Überschrift passt zu Kurztext №5:</p><p>Wer weiß schon, was Vater und Mutter bei der Arbeit machen? Bei der bundesweiten Aktion „Girls’ Day“ erhielten Mädchen einen Tag schulfrei. Sie konnten einmal ihren Eltern im Beruf über die Schulter schauen. Stolz präsentierten Väter und Mütter ihren Töchterchen ihren Arbeitsplatz und erklärten ihnen genau, womit sie ihr Geld verdienen. Das Ziel dieser Aktion: Die Schülerinnen sollten sich die Betriebe anschauen, um sich Ideen für ihre Berufswahl zu holen. Denn immer noch wählen viele Mädchen typische Frauenberufe, obwohl sie bessere Schulabschlüsse als Jungen haben.</p>";
			zadanieArray[1]="Fachschule für einen anspruchsvollen Beruf";
			zadanieArray[2]="Musical-Unterricht für talentierte Jugendliche";
			zadanieArray[3]="Mehr Informationen für Mädchen bei der Berufswahl";
			zadanieArray[4]="Lustige Prüfung nach dem Abitur";
			zadanieArray[5]="Praktikum im Betrieb der Eltern";
			zadanieArray[6]="Zukunftspläne der Abiturienten";
			zadanieArray[7]="Schauspielschule auf dem Nürnberger Bahnhof";
			zadanieArray[8]="Weitgehende Pläne der Gymnasiastin";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.5";		
		/*задание №6 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 2<br>LESEN<p style='text-align:justify;  color:black;'>Mit welchem Ziel gründen die Schüler ihre Schulfirmen?</p>"; 
			zadanieArray[1]="Um auf großen Messen ihre Waren zu verkaufen.";
			zadanieArray[2]="Um Erfahrungen für ihren zukünftigen Beruf zu sammeln.";
			zadanieArray[3]="Um ihre Geschäftsideen an andere Firmen zu verkaufen.";
			zadanieArray[4]="Um mit dem Verdienst ihr weiteres Studium zu finanzieren.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.6";
		/*задание №7 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 2<br>LESEN<p style='text-align:justify;  color:black;'>Welche Kompetenzen sind für die jungen Unternehmer am wichtigsten?</p>"; 
			zadanieArray[1]="Fachkompetenzen";
			zadanieArray[2]="Führungskompetenzen";
			zadanieArray[3]="Sozialkompetenzen";
			zadanieArray[4]="Sprachkompetenzen";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.7";
		/*задание №8 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 2<br>LESEN<p style='text-align:justify;  color:black;'>Was trifft auf das <i>Cosmo Girls</i> Geschäft zu?</p>"; 
			zadanieArray[1]="Sie machen kostenlose Haar- und Nagelpflege.";
			zadanieArray[2]="Sie bieten ihren Service täglich an.";
			zadanieArray[3]="Sie verdienen für sich persönlich nichts.";
			zadanieArray[4]="Sie verkaufen billiges Shampoo und Schminke.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.8";
		/*задание №9 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 2<br>LESEN<p style='text-align:justify;  color:black;'>Welche Gemeinsamkeiten gibt es zwischen Schülerfirmen und gewöhnlichen Firmen?</p>"; 
			zadanieArray[1]="Man fürchtet sich vor Finanzkrisen.";
			zadanieArray[2]="Man braucht am Anfang genug Geld.";
			zadanieArray[3]="Man investiert viel Geld ins Geschäft.";
			zadanieArray[4]="Man teilt die Arbeit untereinander auf.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.9";
		/*задание №10 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 2<br>LESEN<p style='text-align:justify;  color:black;'>Warum verkauft die Firma <i>Elegancia</i> den Bio-Kaffee aus Nicaragua?</p>"; 
			zadanieArray[1]="Weil dieser Kaffee billiger als in Supermärkten ist.";
			zadanieArray[2]="Weil die Schüler mit diesem Geschäft gut verdienen.";
			zadanieArray[3]="Weil die Schüler Kaffeeproduzenten unterstützen wollen.";
			zadanieArray[4]="Weil der Bio-Kaffee Schülern und Lehrern gut schmeckt.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=lesen2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.10";
		/*задание №11 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 3<br>LESEN. Welche Anzeige passt zu  Situation?<p style='text-align:justify;  color:black;'>Herr Bauer ist ein guter Handwerker und würde gerne als Hausmeister arbeiten.</p>";
			zadanieArray[1]=anzeigeA;
			zadanieArray[2]=anzeigeB;
			zadanieArray[3]=anzeigeC;
			zadanieArray[4]=anzeigeD;
			zadanieArray[5]=anzeigeE;
			zadanieArray[6]=anzeigeF;
			zadanieArray[7]=anzeigeG;
			zadanieArray[8]=anzeigeH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.11";
		/*задание №12 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 3<br>LESEN. Welche Anzeige passt zu  Situation?<p style='text-align:justify;  color:black;'>Katja hat ihren Realschulabschluss gemacht und sucht eine Ausbildungsstelle als Bürokauffrau.</p>";
			zadanieArray[1]=anzeigeA;
			zadanieArray[2]=anzeigeB;
			zadanieArray[3]=anzeigeC;
			zadanieArray[4]=anzeigeD;
			zadanieArray[5]=anzeigeE;
			zadanieArray[6]=anzeigeF;
			zadanieArray[7]=anzeigeG;
			zadanieArray[8]=anzeigeH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.12";
		/*задание №13 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=13;
			zadanieArray[0]="Aufgabe 3<br>LESEN. Welche Anzeige passt zu  Situation?<p style='text-align:justify;  color:black;'>Nina hat Vorliebe für Pflanzen und möchte sich nach ihrem Schulabschluss mit der Gärtnerei beschäftigen.</p>";
			zadanieArray[1]=anzeigeA;
			zadanieArray[2]=anzeigeB;
			zadanieArray[3]=anzeigeC;
			zadanieArray[4]=anzeigeD;
			zadanieArray[5]=anzeigeE;
			zadanieArray[6]=anzeigeF;
			zadanieArray[7]=anzeigeG;
			zadanieArray[8]=anzeigeH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.13";
		/*задание №14 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 3<br>LESEN. Welche Anzeige passt zu  Situation?<p style='text-align:justify;  color:black;'>Herr Schulz sucht Stelle als KFZ-Mechatroniker oder PKW-Fahrer. Teilzeitbeschäftigung ist auch möglich.</p>";
			zadanieArray[1]=anzeigeA;
			zadanieArray[2]=anzeigeB;
			zadanieArray[3]=anzeigeC;
			zadanieArray[4]=anzeigeD;
			zadanieArray[5]=anzeigeE;
			zadanieArray[6]=anzeigeF;
			zadanieArray[7]=anzeigeG;
			zadanieArray[8]=anzeigeH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.14";
		/*задание №15 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 3<br>LESEN. Welche Anzeige passt zu  Situation?<p style='text-align:justify;  color:black;'>Andrea möchte gerne in einem Büro arbeiten, kann aber nur vormittags.</p>";
			zadanieArray[1]=anzeigeA;
			zadanieArray[2]=anzeigeB;
			zadanieArray[3]=anzeigeC;
			zadanieArray[4]=anzeigeD;
			zadanieArray[5]=anzeigeE;
			zadanieArray[6]=anzeigeF;
			zadanieArray[7]=anzeigeG;
			zadanieArray[8]=anzeigeH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.15";
		/*задание №16 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 3<br>LESEN. Welche Anzeige passt zu  Situation?<p style='text-align:justify;  color:black;'>Herr Böll, Rentner, möchte etwas zusätzlich verdienen. Er würde gerne Hilfsarbeiten im Garten erledigen.</p>";
			zadanieArray[1]=anzeigeA;
			zadanieArray[2]=anzeigeB;
			zadanieArray[3]=anzeigeC;
			zadanieArray[4]=anzeigeD;
			zadanieArray[5]=anzeigeE;
			zadanieArray[6]=anzeigeF;
			zadanieArray[7]=anzeigeG;
			zadanieArray[8]=anzeigeH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.16";
		/*задание №17 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 4<br>Lesen Sie den Text und füllen Sie die Lücken.<br> <p style='text-align:justify;  color:black;'>Sie erzählt: – Vor fünf Jahren, (17)&nbsp;__________, bin ich zum ersten Mal zusammen mit meinem Bruder auf der Straße geskatet.</p>";
			zadanieArray[1]="obwohl wir unterschiedliche Lebensstile haben";
			zadanieArray[2]="als ich an einem Skaterwettbewerb teilgenommen habe";
			zadanieArray[3]="die dabei entstehen";
			zadanieArray[4]="die in anderen Städten und Ländern stattfinden";
			zadanieArray[5]="obwohl Mädchen oft nicht schlechter als Jungen skaten";
			zadanieArray[6]="als ich noch Schülerin war";
			zadanieArray[7]="den Asphalt unter dem Skateboard zu spüren";
			zadanieArray[8]="dass die Skaterszene eine eigene Welt ist";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=skateboarding;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.17";
		/*задание №18 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 4<br>Lesen Sie den Text und füllen Sie die Lücken.<br> <p style='text-align:justify;  color:black;'>Manchmal fahre ich zu den Wettbewerben, (18)&nbsp;____________.</p>";
			zadanieArray[1]="obwohl wir unterschiedliche Lebensstile haben";
			zadanieArray[2]="als ich an einem Skaterwettbewerb teilgenommen habe";
			zadanieArray[3]="die dabei entstehen";
			zadanieArray[4]="die in anderen Städten und Ländern stattfinden";
			zadanieArray[5]="obwohl Mädchen oft nicht schlechter als Jungen skaten";
			zadanieArray[6]="als ich noch Schülerin war";
			zadanieArray[7]="den Asphalt unter dem Skateboard zu spüren";
			zadanieArray[8]="dass die Skaterszene eine eigene Welt ist";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=skateboarding;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.18";
		/*задание №19 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 4<br>Lesen Sie den Text und füllen Sie die Lücken.<br> <p style='text-align:justify;  color:black;'>Es ist ein unvergleichliches Gefühl, (19)&nbsp;____________.</p>";
			zadanieArray[1]="obwohl wir unterschiedliche Lebensstile haben";
			zadanieArray[2]="als ich an einem Skaterwettbewerb teilgenommen habe";
			zadanieArray[3]="die dabei entstehen";
			zadanieArray[4]="die in anderen Städten und Ländern stattfinden";
			zadanieArray[5]="obwohl Mädchen oft nicht schlechter als Jungen skaten";
			zadanieArray[6]="als ich noch Schülerin war";
			zadanieArray[7]="den Asphalt unter dem Skateboard zu spüren";
			zadanieArray[8]="dass die Skaterszene eine eigene Welt ist";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="g";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=skateboarding;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.19";
		/*задание №20 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 4<br>Lesen Sie den Text und füllen Sie die Lücken.<br> <p style='text-align:justify;  color:black;'>Mir gefällt, (20)&nbsp;____________.</p>";
			zadanieArray[1]="obwohl wir unterschiedliche Lebensstile haben";
			zadanieArray[2]="als ich an einem Skaterwettbewerb teilgenommen habe";
			zadanieArray[3]="die dabei entstehen";
			zadanieArray[4]="die in anderen Städten und Ländern stattfinden";
			zadanieArray[5]="obwohl Mädchen oft nicht schlechter als Jungen skaten";
			zadanieArray[6]="als ich noch Schülerin war";
			zadanieArray[7]="den Asphalt unter dem Skateboard zu spüren";
			zadanieArray[8]="dass die Skaterszene eine eigene Welt ist";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=skateboarding;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.20";
		/*задание №21 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 4<br>Lesen Sie den Text und füllen Sie die Lücken.<br> <p style='text-align:justify;  color:black;'>(21)&nbsp;__________, verbindet uns alle die Liebe zum Skateboarden.</p>";
			zadanieArray[1]="obwohl wir unterschiedliche Lebensstile haben";
			zadanieArray[2]="als ich an einem Skaterwettbewerb teilgenommen habe";
			zadanieArray[3]="die dabei entstehen";
			zadanieArray[4]="die in anderen Städten und Ländern stattfinden";
			zadanieArray[5]="obwohl Mädchen oft nicht schlechter als Jungen skaten";
			zadanieArray[6]="als ich noch Schülerin war";
			zadanieArray[7]="den Asphalt unter dem Skateboard zu spüren";
			zadanieArray[8]="dass die Skaterszene eine eigene Welt ist";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=skateboarding;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.21";
		/*задание №22 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 4<br>Lesen Sie den Text und füllen Sie die Lücken.<br> <p style='text-align:justify;  color:black;'>Die Videos und Fotos, (22)&nbsp; ____________, begeistern auch die männlichen Skater.</p>";
			zadanieArray[1]="obwohl wir unterschiedliche Lebensstile haben";
			zadanieArray[2]="als ich an einem Skaterwettbewerb teilgenommen habe";
			zadanieArray[3]="die dabei entstehen";
			zadanieArray[4]="die in anderen Städten und Ländern stattfinden";
			zadanieArray[5]="obwohl Mädchen oft nicht schlechter als Jungen skaten";
			zadanieArray[6]="als ich noch Schülerin war";
			zadanieArray[7]="den Asphalt unter dem Skateboard zu spüren";
			zadanieArray[8]="dass die Skaterszene eine eigene Welt ist";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=skateboarding;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.22";
		/*задание №23 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Ich liebe extremes Wetter und interessiere (23)&nbsp;__________ für seltene und gefährliche Wetterphänomene.</p>"; 
			zadanieArray[1]="sich";
			zadanieArray[2]="mich";
			zadanieArray[3]="mir";
			zadanieArray[4]="meinen";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="5.23";			
		/*задание №24 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Ich bekomme professionelle Wetterkarten mit verschiedenen Daten, (24)&nbsp;__________ ich analysieren muss.</p>"; 
			zadanieArray[1]="den";
			zadanieArray[2]="die";
			zadanieArray[3]="deren";
			zadanieArray[4]="denen";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.24";
		/*задание №25 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Und dann weiß ich, wo ich diesmal (25)&nbsp;__________ werde.</p>"; 
			zadanieArray[1]="hinzufahren";
			zadanieArray[2]="hingefahren";
			zadanieArray[3]="hinfahren";
			zadanieArray[4]="hinfuhren";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.25";
		/*задание №26 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Besonders toll finde ich (26)&nbsp;__________ Wetter, zum Beispiel Gewitter.</p>"; 
			zadanieArray[1]="schlecht";
			zadanieArray[2]="schlechtes";
			zadanieArray[3]="schlechte";
			zadanieArray[4]="schlechten";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.26";
		/*задание №27 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Ich filme dann, mache Fotos und gebe mit (27)&nbsp;__________ Handy wichtige Daten an den deutschen Wetterdienst weiter.</p>";
			zadanieArray[1]="meinem";
			zadanieArray[2]="mein";
			zadanieArray[3]="meins";
			zadanieArray[4]="meines";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.27";
		/*задание №28 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Einer war 2007 nördlich (28)&nbsp;__________ Berlin, der andere 2009 in Brandenburg.</p>";
			zadanieArray[1]="ab";
			zadanieArray[2]="von";
			zadanieArray[3]="aus";
			zadanieArray[4]="zu";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.28";
		/*задание №29 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Dieses Wetterphänomen hat (29)&nbsp;__________ in Deutschland schon immer gegeben.</p>";
			zadanieArray[1]="man";
			zadanieArray[2]="es";
			zadanieArray[3]="er";
			zadanieArray[4]="das";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.29";
		/*задание №30 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Ich lese alte Zeitungen und Kirchenchroniken und versuche, Informationen über Tornados(30)&nbsp;__________.</p>";
			zadanieArray[1]="gefunden";
			zadanieArray[2]="finden";
			zadanieArray[3]="finde";
			zadanieArray[4]="zu finden";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.30";
		/*задание №31 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>An beschädigten Gebäuden sieht man, (31)&nbsp;__________dort ein Tornado war.</p>";
			zadanieArray[1]="dass";
			zadanieArray[2]="das";
			zadanieArray[3]="wenn";
			zadanieArray[4]="als";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.31";
		/*задание №32 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 5<br>SPRACHBAUSTEINE<br>Lesen Sie den Lückentext und ergänzen Sie ihn. Wählen Sie das Wort (A, B, C oder D), das in die Lücke passt.<br> <p style='text-align:justify;  color:black;'>Solche historischen Wetterdaten (32)&nbsp;__________ untersucht und publiziert.</p>";
			zadanieArray[1]="war";
			zadanieArray[2]="geworden";
			zadanieArray[3]="werden";
			zadanieArray[4]="wird";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tornados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="5.32";
		/*задание №33 ЗНО-2014 немецкий язык. Основной тест(доделать!!!)*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>So wie sie heute noch (33)&nbsp;__________, ...</p>";
			zadanieArray[1]="erkannte";
			zadanieArray[2]="machten";
			zadanieArray[3]="erfand";
			zadanieArray[4]="stattfindet";
			zadanieArray[5]="arbeiteten";
			zadanieArray[6]="gegründet";
			zadanieArray[7]="gibt";
			zadanieArray[8]="sind";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=buchmessen;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;		
			taskNameArray[taskNumber-1]="6.33";
		/*задание №34 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>...wurde sie im Jahr 1949 vom „Börsenverein des Deutschen Buchhandels“ (34)&nbsp;__________.</p>";
			zadanieArray[1]="erkannte";
			zadanieArray[2]="machten";
			zadanieArray[3]="erfand";
			zadanieArray[4]="stattfindet";
			zadanieArray[5]="arbeiteten";
			zadanieArray[6]="gegründet";
			zadanieArray[7]="gibt";
			zadanieArray[8]="sind";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=buchmessen;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;		
			taskNameArray[taskNumber-1]="6.34";
		/*задание №35 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>Es (35)&nbsp;__________ sie jedes Jahr im Oktober.</p>";
			zadanieArray[1]="erkannte";
			zadanieArray[2]="machten";
			zadanieArray[3]="erfand";
			zadanieArray[4]="stattfindet";
			zadanieArray[5]="arbeiteten";
			zadanieArray[6]="gegründet";
			zadanieArray[7]="gibt";
			zadanieArray[8]="sind";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="g";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=buchmessen;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;		
			taskNameArray[taskNumber-1]="6.35";
		/*задание №36 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>Im Jahr 1455 (36)&nbsp;__________ Johannes Gutenberg in Mainz (nicht weit weg von Frankfurt) den Buchdruck.</p>";
			zadanieArray[1]="erkannte";
			zadanieArray[2]="machten";
			zadanieArray[3]="erfand";
			zadanieArray[4]="stattfindet";
			zadanieArray[5]="arbeiteten";
			zadanieArray[6]="gegründet";
			zadanieArray[7]="gibt";
			zadanieArray[8]="sind";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=buchmessen;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="6.36";
		/*задание №37 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=37;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>Einige Buchdrucker (37)&nbsp;__________ in der Folge die Frankfurter Messe zu einem Handelszentrum für gedruckte Bücher.</p>";
			zadanieArray[1]="erkannte";
			zadanieArray[2]="machten";
			zadanieArray[3]="erfand";
			zadanieArray[4]="stattfindet";
			zadanieArray[5]="arbeiteten";
			zadanieArray[6]="gegründet";
			zadanieArray[7]="gibt";
			zadanieArray[8]="sind";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=buchmessen;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.37";
		/*задание №38 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=38;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>Kein Wunder, dass immer mehr Deutsche für ihre täglichen Wege zur Arbeit oder zum Einkaufen vom Auto aufs Fahrrad (38)&nbsp;__________ .</p>";
			zadanieArray[1]="Gründe";
			zadanieArray[2]="fahren";
			zadanieArray[3]="Haushalte";
			zadanieArray[4]="ökologisch";
			zadanieArray[5]="umweltbewusst";
			zadanieArray[6]="umsteigen";
			zadanieArray[7]="Vorschläge";
			zadanieArray[8]="Stau";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Fahrrad;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="6.38";
		/*задание №39 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=39;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>Etwa 80 Prozent aller (39)&nbsp;__________ haben mindestens ein Fahrrad.</p>";
			zadanieArray[1]="Gründe";
			zadanieArray[2]="fahren";
			zadanieArray[3]="Haushalte";
			zadanieArray[4]="ökologisch";
			zadanieArray[5]="umweltbewusst";
			zadanieArray[6]="umsteigen";
			zadanieArray[7]="Vorschläge";
			zadanieArray[8]="Stau";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Fahrrad;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="6.39";
		/*задание №40 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=40;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>Das hat zum Teil praktische (40)&nbsp;__________: Wer Rad fährt, gibt kein Geld für Benzin aus,...</p>";
			zadanieArray[1]="Gründe";
			zadanieArray[2]="fahren";
			zadanieArray[3]="Haushalte";
			zadanieArray[4]="ökologisch";
			zadanieArray[5]="umweltbewusst";
			zadanieArray[6]="umsteigen";
			zadanieArray[7]="Vorschläge";
			zadanieArray[8]="Stau";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Fahrrad;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="6.40";
		/*задание №41 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=41;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>...muss nicht nach einem Parkplatz suchen oder im (41)&nbsp;__________ stehen.</p>";
			zadanieArray[1]="Gründe";
			zadanieArray[2]="fahren";
			zadanieArray[3]="Haushalte";
			zadanieArray[4]="ökologisch";
			zadanieArray[5]="umweltbewusst";
			zadanieArray[6]="umsteigen";
			zadanieArray[7]="Vorschläge";
			zadanieArray[8]="Stau";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Fahrrad;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="6.41";
		/*задание №42 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=42;
			var zadanieArray=new Array();
			zadanieArray[0]="Aufgabe 6<br>SPRACHBAUSTEINE<br>Lesen Sie die Lückentexte und ergänzen Sie sie mit den Wörtern aus den vorgegebenen Listen.<br> <p style='text-align:justify;  color:black;'>Darüber hinaus ist Fahrradfahren cool: Wer Rad fährt, präsentiert sich als (42)&nbsp;__________.</p>";
			zadanieArray[1]="Gründe";
			zadanieArray[2]="fahren";
			zadanieArray[3]="Haushalte";
			zadanieArray[4]="ökologisch";
			zadanieArray[5]="umweltbewusst";
			zadanieArray[6]="umsteigen";
			zadanieArray[7]="Vorschläge";
			zadanieArray[8]="Stau";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Fahrrad;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="6.42";
		/*задание №43 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=43;
			var zadanieArray=new Array();
			zadanieArray[0]="Schreiben  Aufgabe<br>Ihr Freund lernt Englisch im Gymnasium und dieses Fach fällt ihm ziemlich schwer. Im nächsten Jahr hat er aber vor, das Abitur zu machen. Wie könnte er seine Englischkenntnisse verbessern? Er bittet Sie um Rat.<br>Schreiben Sie Ihrem Freund einen Brief zu folgenden Punkten:<ul><li>berichten Sie Ihrem Freund über Ihre Erfahrungen mit dem Fremdsprachenunterricht in Ihrer Schule</li><li>erzählen Sie über Ihre selbstständige Arbeit an der Fremdsprache</li><li>geben Sie Ihrem Freund ein paar Ratschläge zu seinem Problem</li></ul>Schreiben Sie nicht weniger als 100 Wörter. Schreiben Sie keine persönlichen Angaben (Name, Adresse). Verwenden Sie nur den  Namen und die Adresse, die in der Situation vorgegeben sind."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]="";
			taskTypeArray[taskNumber-1]="tvir";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=14;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="Schreiben.43";
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}	/* Окончание ЗНО-2014 немецкий язык. Основной тест. I сессия*/	
	
/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/
	
	startInitialization();
	
}
