//инициализация тестов по испанскому языку
function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/
/*************************************************************/
//Тесты по испанскому языку	
/*************************************************************/	

/*ЗНО-2011 испанский язык. Основной тест.*/
	if(testName==znoEsp2011Main)
	{
		testLength=46;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/esp\/img\/test2011main1\/';
		testTitle = znoName+"2011"+znoEspName;
		testDetails=mainName;
		var Tarea1_2011='1 - (…..)\nLa renovacion del espacio medioambiental para todos los publicos ?Toca, Toca! en el Museo de la Ciencia en Madrid, ha  creado un espacio interactivo que permite al visitante conocer diferentes habitats y las especies que en ellos viven. Alli no solo podra ver los animales, sino que tambien podra tocar serpientes, tortugas, estrellas o pepinos de mar. Algunos de los animales que se pueden encontrar en este espacio son tortugas de espolones y dragones barbudos.\n\n2 - (…..)\nLa ultima costa virgen protegida de Murcia lleva nueve anos esperando que el Tribunal Constitucional resuelva un recurso contra una macrourbanizacion. El mayor complejo urbanistico previsto en el Mediterraneo ocupara un parque natural en la costa virgen de la autonomia gracias a una ley de 2001. Un portavoz del Constitucional explica que el tribunal sigue sin fecha para decidir sobre el parrafo de la Ley del Suelo de Murcia que permitia la urbanizacion y que recurrio el PSOE.\n\n3 - (…..)\nLos documentales medioambientales estan de moda. Titulos como Tierra y Home compiten con el cine de Hollywood en las listas de los DVD mas vendidos. Tierra, el espectacular largometraje sobre nuestro planeta de la BBC, ocupo varias semanas el primer puesto en las listas de ventas nacionales de la FNAC en formato Blu-ray. La proxima gran produccion en este genero promete ser Oceans, el documental con mayor presupuesto de la historia: 50 millones de euros.\n\n4 - (…..)\nTras meses en los que los constructores no se han cansado de repetir que los precios de los pisos ya han bajado todo lo que tienen que bajar y que no lo van a hacer mas, un paseo por el Salon Inmobiliario de Madrid (SIMA), deparaba ofertas como la siguiente: “Dos dormitorios, 72 metros cuadrados utiles en Getafe. Desde 300.000 euros”. Sin embargo, los expertos no lo dudan: los precios tienen que bajar mucho mas.\n\n5 - (…..)\nEl mochilero es un personaje peculiar de la vida contemporanea. El mochilero es un joven que con poco dinero y mucha habilidad se lanza a viajar por el mundo solo, gastando lo menos posible (conoce todos los alojamientos interesantes de media estrella, e incluso de ninguna) y disfrutando al maximo porque lo que vale no tiene precio. El mochilero es un maestro en el arte de vivir a fondo mientras atraviesa cualquier lugar del mundo, sea Tailandia, Galicia o Argentina.';
		var Tarea2_2011='Buscamos una casa rural\n\n Los espanoles nos hemos vuelto cada vez mas previsores y reservamos nuestros lugares de vacaciones con una antelacion impensable hace unos anos. Si no lo cree, pruebe a buscar una casa rural para la proxima Nochevieja con menos de dos meses de antelacion. Le resultara mision imposible. Y eso que la oferta de alojamiento rural en Espana se ha disparado. \n\n Si desea alquilar una casa rural, para empezar hay que tener en cuenta que unas casas se alquilan por habitaciones, y otras, enteras. En las primeras, lo normal es que los duenos vivan en ellas y funcione como una explotacion agropecuaria. Permiten disfrutar del espiritu original con el que nacieron estos alojamientos: vivir de cerca las faenas agricolas mientras se facilita a los propietarios unos ingresos extra. A veces huele a vaca o hay que compartir el bano con los duenos. En ocasiones, los propietarios organizan actividades de agroturismo: como ordenar vacas, buscar setas o cocer pan en sus hornos. \n\n Sin embargo, cada vez se rehabilitan mas casas para alquiler completo. En este caso, compruebe que el precio incluye sabanas, mantas, toallas y gastos de calefaccion. \n\n Existe para los precios gran amplitud de oferta. En cualquier caso, mas que por el precio, dejese tentar por la calidad. No es lo mismo pagar una cantidad por una vivienda con doscientos anos de historia primorosamente decorada con muebles antiguos y rodeada por un paisaje de ensueno que abonar casi lo mismo por una casa de paredes blancas donde el dueno ha acumulado todos los muebles viejos que no le cabian en la suya. Las guias especializadas sobre casas rurales y las paginas de Internet pueden ayudarle a decidir de antemano si la vivienda elegida esta decorada con gusto o es un almacen de trastos viejos. \n\n Las necesidades de mercado han llevado a los propietarios de alojamientos rurales a asociarse en centrales de reservas, muy comodas para el usuario porque permiten contratar un alojamiento sin sobreprecio y facilitan la busqueda de otra vivienda en la misma zona si la elegida esta ocupada. A la hora de elegir el lugar para sus vacaciones, valore tambien la belleza del entorno, la cercania de carreteras o zonas industriales que provoquen ruidos, la posibilidad de dar paseos por los alrededores y la oferta de actividades culturales o en la naturaleza que le ofrezca la propia casa o empresas cercanas.';
		var Tarea3_2011='Alejandro Amenábar regresa a las pantallas con “Ágora”, un drama histórico que centra su atención en la figura de Hipatia de Alejandría. Amenábar charla sobre su última producción, así como de su carrera cinematográfica.\n\n11 – Hola, Alejandro. ?Por que has tardado tanto tiempo en hacer una pelicula desde “Mar adentro”? \n– (.....) \n\n12 – Cincuenta millones de euros para hacer una pelicula en medio de una crisis economica. ?Lo has pensado bien? \n– (.....) \n\n13 – ?Como conociste a Hipatia? ?Te intereso primero el personaje o investigaste porque tenias la idea de una produccion ambientada en el mundo clasico? \n– (.....) \n\n14 – A proposito, Alejandro, ?que opinas de la “pirateria” audiovisual? \n– (.....) \n\n15 – ?Que le recomendarias a un guionista novel como yo que quiere dedicarse al cine? \n– (.....)';
		var Tarea4_2011='– ?Que periodico quieres? \n– Me da lo mismo, el que (16)_____. \n\n– Bueno, ?que os parece la paella? \n– Que (17)_____. \n\n– ?Que me contais de Jose? \n– Pues desde que sale con esa chica tan guapa, (18)_____. \n\n– Es dificil hablar con Micaela. \n– Tienes razon. Me molesta que ella nunca (19)_____ con nadie. \n\n– Hoy es mi primer dia de trabajo. \n– ?Pues que (20)_____! \n\n– Mira, como estan las plantas. Te dije que tenias que regarlas todos los dias... \n– Bueno, no te pongas asi, no (21)_____.';
		var Tarea5_2011='Kung Fu Panda  \n\nMarta y Paco quieren ir a ver una pelicula. Los dos estan mirando en el periodico la cartelera actual de cine. \n\nMarta: ?Que te parece esta, Paco? \nPaco: ?Cual? ?“La princesa del bosque”? Mama, por favor, que no tengo cinco anos. ?Desde cuando veo yo ese tipo de peliculas de ninas? Que yo (22)_____, nunca. \nMarta: Bueno, vale. Era solo una (23)_____. ?Y la de Harry Potter? \nPaco: Ya la he visto dos veces. \nMarta: ?Uff!, mira que es dificil (24)_____ una pelicula contigo. Dime tu, ?cual quieres ver? \nPaco: Esta. “La aventura espacial”. \nMarta: A ver... Paco, (25)_____ el dedo del texto, que quiero ver lo que pone. ?Ah, no, no! ?Es una pelicula para mayores de 18 anos! Tiene escenas violentas. Asi que, jovencito, puedes buscar otra que (26)_____ a tu edad. \nPaco: Vaya rollo. Pues Oscar ya la ha visto. \nMarta: Lo que haya visto Oscar o no, es cosa de Oscar y sus padres. Yo tengo bastante con ocuparme de tu educacion. Asi que esa pelicula no es para tu edad, ?vale? Y ahora, (27)_____ buscando. \nPaco: A mi me (28)_____ igual. Me voy a jugar con el ordenador. Escoge tu misma. \nMarta: Voy a preguntar a tu padre si quiere ir al cine con nosotros. A lo (29)_____ el tiene alguna idea... ?Gabrieeel! \nGabriel: ?Que pasa? \nMarta: Oye, ?no querias ir al cine la semana pasada? \nGabriel: Si. Pero (30)_____ hacia mal tiempo, todo el mundo penso en ir al cine y no (31)_____ entradas. \nMarta: Y, ?que pelicula querias ver? Quiza podriamos ir hoy los tres a verla. \nGabriel: Hmmm, si. Pero no se si a ti te gustaria. Es de artes marciales. \nMarta: ?Por que no? ?Cual es? \nGabriel: “Kung Fu Panda”. \nMarta: Pero, ?no es una pelicula para ninos? Gabriel, me (32)_____. A mi me encantaria ir a verla. Y seguro que a Paco tambien le (33)_____ a gustar.';
		var Tarea6_1_2011='  Texto 1\n\nLa Oroya, un pueblo minero en los Andes del Peru, figura (34)_____ las diez ciudades mas contaminadas del mundo. (35)_____ las investigaciones del Instituto Blacksmith, el noventa (36)_____ ciento de los ninos de La Oroya tienen altos niveles de plomo y zinc en la sangre, contaminacion que resulta de la intensa fundicion de metales pesados en el area (37)_____ los anos veinte del siglo pasado. El promedio de plomo en la sangre de esos ninos era el triple del limite aceptable establecido por la Organizacion Mundial (38)_____ la Salud. Los cientificos afirman que, aun cuando las fabricas vayan (39)_____ disminuir las  emisiones, el nivel de la contaminacion por el plomo puede permanecer en la tierra durante muchos siglos.';
		var Tarea6_2_2011='  Texto 2\n\n Los espanoles (40)_____ orgullosos de preservar con fervor la figura de sus reyes como jefes absolutos del Estado. Para muchos, la Familia Real constituye el modelo ideal de vida en familia. Ademas, los espanoles se interesan por conocer la vida cotidiana de los reyes, del principe y de las infantas, como si (41)_____ celebridades del espectaculo.\n\n Los espanoles (42)_____ un especial gusto por conocer la vida privada de otros personajes destacados de la sociedad. Este interes (43)_____ paso a una importante industria editorial dedicada exclusivamente a explorar la vida y costumbres de los personajes de moda. Puede que el producto mas emblematico de todos (44)_____ la publicacion “?Hola!”, revista que (45)_____ investigar los detalles mas privados de las celebridades y la nobleza espanola.';	
		gradeArray=new Array("100.0","100.5","100.5","100.5","100.5","103.5","108.0","111.0","114.5","122.0","124.0","126.0","127.0","128.0","129.0","129.0","131.5","132.0","133.0","133.5","134.5","134.5","135.5","136.5","137.0","137.5","139.5","140.0","140.5","140.5","141.5","142.0","142.0","142.5","143.0","144.0","144.5","144.5","145.0","146.5","147.0","148.0","149.0","151.0","151.0","152.5","154.0","154.0","154.5","155.0","155.0","156.5","157.5","158.0","158.0","158.0","159.0","160.5","162.0","163.0","164.5","165.5","168.0","168.5","170.0","171.5","172.0","176.0","177.5","178.0","180.0","184.5","186.5","186.5","190.5","190.5","194.0","196.5","200.0");
		answerArray=new Array("c","d","h","f","b","a","c","b","c","d","h","f","e","g","d","e","a","b","c","f","g","c","a","c","c","b","b","d","a","a","d","b","d","c","e","a","d","h","i","b","a","e","i","c","g"," ");
		taskTypeArray=new Array("textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","tvir");
		textAnalysisArray=new Array(Tarea1_2011,Tarea1_2011,Tarea1_2011,Tarea1_2011,Tarea1_2011,Tarea2_2011,Tarea2_2011,Tarea2_2011,Tarea2_2011,Tarea2_2011,Tarea3_2011,Tarea3_2011,Tarea3_2011,Tarea3_2011,Tarea3_2011,Tarea4_2011,Tarea4_2011,Tarea4_2011,Tarea4_2011,Tarea4_2011,Tarea4_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea5_2011,Tarea6_1_2011,Tarea6_1_2011,Tarea6_1_2011,Tarea6_1_2011,Tarea6_1_2011,Tarea6_1_2011,Tarea6_2_2011,Tarea6_2_2011,Tarea6_2_2011,Tarea6_2_2011,Tarea6_2_2011,Tarea6_2_2011,"tvir");
		taskMarkArray=new Array(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,24);
		variantNumberArray=new Array(9,9,9,9,9,4,4,4,4,4,8,8,8,8,8,8,8,8,8,8,8,4,4,4,4,4,4,4,4,4,4,4,4,9,9,9,9,9,9,9,9,9,9,9,9,0);
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,"picture",variantNumberArray[i], "vertical", answerLanguage, "", "");
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
	
		}		
	}
	/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();	
}
