function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	/*Массив названий тестов*/
	var taskNameArray=new Array();
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/
/*************************************************************/
//Тесты по испанскому языку	
/*************************************************************/	
/*ЗНО-2014 испанский язык. Основной тест. I сессия*/
	if(testName==znoEsp2014Main)
	{
		testLength=43;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/esp\/img\/test2014main\/';
		testTitle = znoName+"2014"+znoEspName;
		testDetails=mainName;
		answerLanguage="eng";
		gradeArray=new Array("100.0","100.5","101.0","104.0","106.0","109.0","115.0","118.0","122.0","125.0","128.0","130.0","133.0","134.0","135.0","136.0","137.5","138.5","139.0","140.0","141.5","142.5","143.5","144.5","145.5","146.5","147.5","148.5","149.5","151.0","152.5","153.5","154.5","156.0","157.5","158.5","160.0","162.0","163.0","165.0","166.0","168.0","169.0","170.5","172.5","175.0","177.0","180.0","183.0","185.0","187.0","190.0","193.0","196.0","199.0","200.0","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var tarea1="1 – (…..)\n\tDurante el verano, los niños que participan en los campamentos que ofrece el zoológico de la Casa de Campo preparan una vez a la semana los helados que consisten en bloques de hielo con trozos de frutas y van destinados a lémures, leones marinos, gorilas y osos panda entre otros animales. Los elefantes disponen también de piscinas para poderse refrescar. \n\n2 – (…..)\n\t La famosa curiosidad del gato puede ser fuente de graves problemas. Por eso, mantén cerrados los electrodomésticos, no dejes los fuegos de la cocina encendidos sin vigilancia y ten cuidado con los cables eléctricos y las plantas, pues tu mascota podría morderlos en momentos de aburrimiento. También resultan peligrosos los productos químicos, los cosméticos y las bolsas de plástico. \n\n3 – (…..)\n\t Adquirir un perro es una inversión a largo plazo: con un poco de suerte te acompañará durante muchos años. Así que no seas tacaño a la hora de comprarlo, recuerda que con los perros, como con los coches, “lo barato muchas veces sale caro”. Si compras una mascota con papeles, tendrás la seguridad de adquirir un perro de raza que posee las características que te interesan. \n\n4 – (…..)\n\t Si la temperatura de la Tierra aumenta de 2 grados centígrados más, un tercio de la población de animales y más de la mitad de las plantas del planeta podrán desaparecer. Así lo afirma un estudio publicado en la revista Nature. Las regiones del África sahariana, América Central y Australia serán las más afectadas. Sin embargo, si las emisiones de gases de efecto invernadero se reducen rápidamente el impacto se podrá moderar. \n\n5 – (…..)\n\t Nuestras mascotas son nuestros mejores amigos. Florence Nightingale, fundadora de las modernas escuelas de enfermería, observó que estos “camaradas” eran muy beneficiosos para los enfermos crónicos. Además ahora hay investigaciones que han comprobado que estos pequeños animales pueden hacer grandes cosas dentro de una consulta del psicólogo o en el hogar disminuyendo las tensiones.";
		var tarea2="\tHuertos urbanos, agricultura entre rascacielos\n\n\tEspacios verdes plantados entre rascacielos y polígonos industriales, los huertos urbanos representan una vía de contacto con la naturaleza, al mismo tiempo que aportan beneficios educacionales, sociales, terapéuticos y, en algunos casos, económicos. No es necesario para su creación disponer de grandes extensiones de terreno; se puede utilizar un solar que está en desuso, las azoteas de los edificios o los balcones de la propia vivienda. \n\tEl ayuntamiento de Tokio aprobó una norma que exigía que los nuevos edificios privados cubrieran, al menos, el 20% de su superficie con huertos. Otros países donde se promueve este tipo de huertos son Alemania, Holanda y Suecia. \n\tEn España la pionera fue Barcelona, que en 1996 puso en marcha la primera red de huertos urbanos, que establece como única condición para convertirse en uno de sus usuarios ser mayor de 65 años y vivir en el distrito donde se halla el huerto. Desde entonces otras ciudades españolas han desarrollado proyectos similares. Pero esta iniciativa no se destina en exclusiva a los jubilados; muchas escuelas han comenzado a implantar estos huertos que se han convertido en una forma de educación ambiental. \n\tEl acceso a los huertos urbanos se realiza por sorteo, previa inscripción de los interesados en una lista de espera. El afortunado tiene derecho a cultivar en la parcela que se le ha asignado durante un período determinado de años siempre que se comprometa a cumplir una serie de normas. Por ejemplo, él debe cubrir gastos para la compra de semillas y pagar una parte del agua de riego; se compromete a destinar su cosecha al consumo personal, a no instalar jaulas para animales en el huerto y a respetar las parcelas vecinas. Se recomienda que el lugar elegido para sembrar las plantas cuente al menos con cinco horas de sol diarias, que esté protegido del viento y que se vigile a menudo la humedad de las plantas, ya que en un recipiente pequeño es más fácil que la tierra se seque. \n\tMuchos expertos subrayan los beneficios terapéuticos y sociales de la horticultura. Por esta razón, en numerosos huertos se dispone de parcelas reservadas para pacientes neurológicos o con algún tipo de discapacidad. Además, en el caso de los jubilados, los cuidados en el huerto les ayudan a evitar depresiones. También los huertos urbanos ayudan a recuperar zonas verdes y a mitigar la acumulación del calor en las ciudades.";
		var respuestaA="<div style='color:black; font-size:14px;'>– A mí el teatro me encanta, me seduce mucho... El teatro es una terapia y un entrenamiento actoral continuo. Creo que es por regla general el medio más agradecido para el actor, aunque hay algunas cosas alrededor que no me gustan.</div>";
		var respuestaB="<div style='color:blue; font-size:14px;'>– Pienso que es una profesión para siempre. No es como en otras carreras, como las de algunos deportistas, que ya a los treinta y pico no les queda más remedio que retirarse. El artista tiene un don que siempre va a seguir desarrollando.</div>";
		var respuestaC="<div style='color:black; font-size:14px;'>– Repaso el texto mentalmente una y otra vez, cambiándolo, poniéndole música, haciéndolo muy distinto a cómo me lo van a pedir, como si fuera un niño, como si fuera una mujer, con un dramatismo exagerado, etcétera.</div>";
		var respuestaD="<div style='color:blue; font-size:14px;'>– “La máquina de bailar”, porque fue mi debut profesional en el cine; y “Así es mejor”, cortometraje producido por mí y que me ha ayudado a entender el resto de áreas de la profesión del cine.</div>";
		var respuestaE="<div style='color:black; font-size:14px;'>– Es que yo no creo en las edades, creo en el talento. Puedes tener la edad que quieras, que si tienes talento debes ocupar el puesto que mereces. Esa es mi opinión, pero yo no he creado esta sociedad. Si lo hubiera hecho yo, ¡qué diferente sería!</div>";
		var respuestaF="<div style='color:blue; font-size:14px;'>– Para el año que viene me han dado una beca para hacer una especialización en Dirección de Cine. Veré los primeros meses cómo la llevo, y si las cosas van mejor de lo pensado, sacaré tiempo para ir un par de veces a la semana a clases de interpretación.</div>";
		var respuestaG="<div style='color:black; font-size:14px;'>– Acudí con trece años a mi primera clase de teatro, aunque el gusanillo me entró a los cuatro haciendo de narrador en el belén escolar. Estuve hasta los dieciséis años en el Centro Insular de Cultura y de ahí pasé a la Escuela de Actores de Canarias.</div>";
		var respuestaH="<div style='color:blue; font-size:14px;'>– Sí, y han sido el apoyo máximo para que yo esté aquí ahora. Es importante estudiar y formarse, pero si tienes otros sueños, adelante, tienes que encontrar lo que te haga feliz, y hay que buscar tu vocación, no lo que te dé más dinero.</div>";
		var maletaPerfecta="\tCómo hacer la maleta perfecta\n\n\tIr de viaje siempre es una experiencia emocionante que esperamos con ilusión. Lo que no nos suele hacer tanta gracia es el “momento maleta”. Saber qué llevar y cómo guardarlo es todo un arte, pero una vez que se aprende (17)_____. \n\tAntes de hacer la maleta haz una lista con todo lo que (18)_____, teniendo en cuenta qué temperatura hace y qué vas a hacer allí. Evita los temibles “por si acaso”. A menudo las maletas suelen llenarse de prendas que metemos para situaciones hipotéticas que (19)_____. Dentro de zapatos o botas tienes un espacio rígido, donde puedes meter cosas que no quieres que (20)_____ (por ejemplo, un collar de cristales de Swarovski). Los zapatos deben ir en bolsas individuales y bien encajados para que (21)_____. El cinturón enrollado ocupa más, así que colócalo estirado de manera que (22)_____.";
		var resultados="\tSegún los resultados de una encuesta sobre (23)_____ deportivos de los españoles, la práctica del deporte ha ido aumentando de forma regular en los últimos años: el 45% de los encuestados afirma hacer algún deporte, con un porcentaje mayor en (24)_____ de personas más jóvenes. En su gran mayoría, los españoles hacen deporte por su (25)_____, al margen de clubes o asociaciones. No es de extrañar, por ello, que el deporte más practicado sea la gimnasia de mantenimiento, (26)_____ a bastante distancia por el fútbol, la natación y el ciclismo. Un aspecto importante para la difusión popular del deporte es (27)_____ del obstáculo que constituía la escasez de instalaciones. Los resultados de la encuesta (28)_____ la mejora progresiva de los equipamientos deportivos: (29)_____ de los polideportivos cubiertos, cuyo número casi se duplica entre 1990 y 2010, es un buen indicador de esa mejora, porque estos equipamientos se pueden utilizar a lo (30)_____ de todo el año, con horarios muy amplios y flexibles. La encuesta (31)_____ otros aspectos de la cuestión, entre los que se cuenta (32)_____ muy positiva que merecen, para un elevado porcentaje de encuestados, los resultados de España en las competiciones deportivas internacionales.";
		var taskNumber=1;
		/*задание №1 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 1 <br>Leer los textos № 1-5.<p style='text-align:justify;  color:black;'>¿Qué título (A-H) es adecuado para el №1 de texto?</p><p>Durante el verano, los niños que participan en los campamentos que ofrece el zoológico de la Casa de Campo preparan una vez a la semana los helados que consisten en bloques de hielo con trozos de frutas y van destinados a lémures, leones marinos, gorilas y osos panda entre otros animales. Los elefantes disponen también de piscinas para poderse refrescar.</p>";
			zadanieArray[1]="Cómo curar una herida a tu perro";
			zadanieArray[2]="Plantas tóxicas o venenosas para los animales";
			zadanieArray[3]="Fuerte caída de las emisiones de gases contaminantes";
			zadanieArray[4]="El cambio climático es una grave amenaza para la biodiversidad";
			zadanieArray[5]="Animales “enfermeros” que nos cuidan";
			zadanieArray[6]="Toma precauciones en el hogar";
			zadanieArray[7]="Vale la pena gastar algo más";
			zadanieArray[8]="Combatiendo el calor";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.1";	
		/*задание №2 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 1 <br>Leer los textos № 1-5.<p style='text-align:justify;  color:black;'>¿Qué título (A-H) es adecuado para el №2 de texto?</p><p>La famosa curiosidad del gato puede ser fuente de graves problemas. Por eso, mantén cerrados los electrodomésticos, no dejes los fuegos de la cocina encendidos sin vigilancia y ten cuidado con los cables eléctricos y las plantas, pues tu mascota podría morderlos en momentos de aburrimiento. También resultan peligrosos los productos químicos, los cosméticos y las bolsas de plástico.</p>";
			zadanieArray[1]="Cómo curar una herida a tu perro";
			zadanieArray[2]="Plantas tóxicas o venenosas para los animales";
			zadanieArray[3]="Fuerte caída de las emisiones de gases contaminantes";
			zadanieArray[4]="El cambio climático es una grave amenaza para la biodiversidad";
			zadanieArray[5]="Animales “enfermeros” que nos cuidan";
			zadanieArray[6]="Toma precauciones en el hogar";
			zadanieArray[7]="Vale la pena gastar algo más";
			zadanieArray[8]="Combatiendo el calor";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.2";	
		/*задание №3 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 1 <br>Leer los textos № 1-5.<p style='text-align:justify;  color:black;'>¿Qué título (A-H) es adecuado para el №3 de texto?</p><p>Adquirir un perro es una inversión a largo plazo: con un poco de suerte te acompañará durante muchos años. Así que no seas tacaño a la hora de comprarlo, recuerda que con los perros, como con los coches, “lo barato muchas veces sale caro”. Si compras una mascota con papeles, tendrás la seguridad de adquirir un perro de raza que posee las características que te interesan.</p>";
			zadanieArray[1]="Cómo curar una herida a tu perro";
			zadanieArray[2]="Plantas tóxicas o venenosas para los animales";
			zadanieArray[3]="Fuerte caída de las emisiones de gases contaminantes";
			zadanieArray[4]="El cambio climático es una grave amenaza para la biodiversidad";
			zadanieArray[5]="Animales “enfermeros” que nos cuidan";
			zadanieArray[6]="Toma precauciones en el hogar";
			zadanieArray[7]="Vale la pena gastar algo más";
			zadanieArray[8]="Combatiendo el calor";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="g";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.3";	
		/*задание №4 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 1 <br>Leer los textos № 1-5.<p style='text-align:justify;  color:black;'>¿Qué título (A-H) es adecuado para el №4 de texto?</p><p>Si la temperatura de la Tierra aumenta de 2 grados centígrados más, un tercio de la población de animales y más de la mitad de las plantas del planeta podrán desaparecer. Así lo afirma un estudio publicado en la revista Nature. Las regiones del África sahariana, América Central y Australia serán las más afectadas. Sin embargo, si las emisiones de gases de efecto invernadero se reducen rápidamente el impacto se podrá moderar.</p>";
			zadanieArray[1]="Cómo curar una herida a tu perro";
			zadanieArray[2]="Plantas tóxicas o venenosas para los animales";
			zadanieArray[3]="Fuerte caída de las emisiones de gases contaminantes";
			zadanieArray[4]="El cambio climático es una grave amenaza para la biodiversidad";
			zadanieArray[5]="Animales “enfermeros” que nos cuidan";
			zadanieArray[6]="Toma precauciones en el hogar";
			zadanieArray[7]="Vale la pena gastar algo más";
			zadanieArray[8]="Combatiendo el calor";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.4";		
		/*задание №5 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 1 <br>Leer los textos № 1-5.<p style='text-align:justify;  color:black;'>¿Qué título (A-H) es adecuado para el №5 de texto?</p><p>Nuestras mascotas son nuestros mejores amigos. Florence Nightingale, fundadora de las modernas escuelas de enfermería, observó que estos “camaradas” eran muy beneficiosos para los enfermos crónicos. Además ahora hay investigaciones que han comprobado que estos pequeños animales pueden hacer grandes cosas dentro de una consulta del psicólogo o en el hogar disminuyendo las tensiones.</p>";
			zadanieArray[1]="Cómo curar una herida a tu perro";
			zadanieArray[2]="Plantas tóxicas o venenosas para los animales";
			zadanieArray[3]="Fuerte caída de las emisiones de gases contaminantes";
			zadanieArray[4]="El cambio climático es una grave amenaza para la biodiversidad";
			zadanieArray[5]="Animales “enfermeros” que nos cuidan";
			zadanieArray[6]="Toma precauciones en el hogar";
			zadanieArray[7]="Vale la pena gastar algo más";
			zadanieArray[8]="Combatiendo el calor";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea1;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.5";		
		/*задание №6 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 2<br>Después de leer el siguiente texto, busque para frase la opción  adecuada entre las cuatro (A-D) que se le ofrecen.<p style='text-align:justify;  color:black;'>Los huertos urbanos</p>"; 
			zadanieArray[1]="perjudican al paisaje de las ciudades grandes.";
			zadanieArray[2]="son muy rentables desde el punto de vista de la economía.";
			zadanieArray[3]="permiten asociar aspectos sociales con aspectos naturales.";
			zadanieArray[4]="ayudan a reducir en parte considerable el consumo de agua.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.6";
		/*задание №7 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 2<br>Después de leer el siguiente texto, busque para frase la opción  adecuada entre las cuatro (A-D) que se le ofrecen.<p style='text-align:justify;  color:black;'>La agricultura urbana</p>"; 
			zadanieArray[1]="ayuda a bajar la temperatura en las ciudades.";
			zadanieArray[2]="produce nuevos puestos de trabajo.";
			zadanieArray[3]="representa el 20% de la superficie de Tokio.";
			zadanieArray[4]="se desarrolla sólo en los polígonos industriales.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.7";
		/*задание №8 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 2<br>Después de leer el siguiente texto, busque para frase la opción  adecuada entre las cuatro (A-D) que se le ofrecen.<p style='text-align:justify;  color:black;'>Los usuarios de un huerto urbano</p>"; 
			zadanieArray[1]="tienen derecho a criar animales.";
			zadanieArray[2]="tienen que pagar los derechos de inscripción.";
			zadanieArray[3]="pueden vender una parte de su cosecha.";
			zadanieArray[4]="compran las semillas por su propia cuenta.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.8";
		/*задание №9 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 2<br>Después de leer el siguiente texto, busque para frase la opción  adecuada entre las cuatro (A-D) que se le ofrecen.<p style='text-align:justify;  color:black;'>Según el texto,</p>"; 
			zadanieArray[1]="es más fácil mantener un huerto en el balcón que en la tierra.";
			zadanieArray[2]="hay que estar muy pendiente de las necesidades hídricas de las plantas.";
			zadanieArray[3]="la horticultura fomenta la conciencia del reciclaje de los residuos.";
			zadanieArray[4]="el objetivo de la agricultura urbana es conseguir la mejor cosecha.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.9";
		/*задание №10 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 2<br>Después de leer el siguiente texto, busque para frase la opción  adecuada entre las cuatro (A-D) que se le ofrecen.<p style='text-align:justify;  color:black;'>En el texto se afirma que</p>"; 
			zadanieArray[1]="va creciendo el interés de las escuelas por los huertos urbanos.";
			zadanieArray[2]="hay huertos sólo para los niños con algún tipo de discapacidad.";
			zadanieArray[3]="diferentes centros docentes ofrecen cursos de horticultura.";
			zadanieArray[4]="en muchas escuelas la horticultura es una asignatura obligatoria.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=tarea2;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.10";
		/*задание №11 ЗНО-2014 испанский язык. Основной тест*/
		/*Dodelat!!!*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 3<br>Experiencias de uno de los jóvenes talentos con más futur o en la actuación<p style='text-align:justify;  color:black;'>– Lolo, tengo una pregunta sobre cómo fueron tus inicios en la interpretación.</p>RESPUESTAS:";
			zadanieArray[1]=respuestaA;
			zadanieArray[2]=respuestaB;
			zadanieArray[3]=respuestaC;
			zadanieArray[4]=respuestaD;
			zadanieArray[5]=respuestaE;
			zadanieArray[6]=respuestaF;
			zadanieArray[7]=respuestaG;
			zadanieArray[8]=respuestaH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="g";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.11";
		/*задание №12 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 3<br>Experiencias de uno de los jóvenes talentos con más futur o en la actuación<p style='text-align:justify;  color:black;'>– Y tus padres, ¿te han dejado libertad para elegir tu profesión?</p>RESPUESTAS:";
			zadanieArray[1]=respuestaA;
			zadanieArray[2]=respuestaB;
			zadanieArray[3]=respuestaC;
			zadanieArray[4]=respuestaD;
			zadanieArray[5]=respuestaE;
			zadanieArray[6]=respuestaF;
			zadanieArray[7]=respuestaG;
			zadanieArray[8]=respuestaH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.12";
		/*задание №13 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=13;
			zadanieArray[0]="TAREA 3<br>Experiencias de uno de los jóvenes talentos con más futur o en la actuación<p style='text-align:justify;  color:black;'>– ¿Cuáles son los trabajos más importantes en tu carrera?</p>RESPUESTAS:";
			zadanieArray[1]=respuestaA;
			zadanieArray[2]=respuestaB;
			zadanieArray[3]=respuestaC;
			zadanieArray[4]=respuestaD;
			zadanieArray[5]=respuestaE;
			zadanieArray[6]=respuestaF;
			zadanieArray[7]=respuestaG;
			zadanieArray[8]=respuestaH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.13";
		/*задание №14 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 3<br>Experiencias de uno de los jóvenes talentos con más futur o en la actuación<p style='text-align:justify;  color:black;'>– ¿Qué haces para matar el tiempo de espera en los castings?</p>RESPUESTAS:";
			zadanieArray[1]=respuestaA;
			zadanieArray[2]=respuestaB;
			zadanieArray[3]=respuestaC;
			zadanieArray[4]=respuestaD;
			zadanieArray[5]=respuestaE;
			zadanieArray[6]=respuestaF;
			zadanieArray[7]=respuestaG;
			zadanieArray[8]=respuestaH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.14";
		/*задание №15 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 3<br>Experiencias de uno de los jóvenes talentos con más futur o en la actuación<p style='text-align:justify;  color:black;'>– ¿Sigues formándote en clases, seminarios o cursos, y lo combinas con tu actividad laboral?</p>RESPUESTAS:";
			zadanieArray[1]=respuestaA;
			zadanieArray[2]=respuestaB;
			zadanieArray[3]=respuestaC;
			zadanieArray[4]=respuestaD;
			zadanieArray[5]=respuestaE;
			zadanieArray[6]=respuestaF;
			zadanieArray[7]=respuestaG;
			zadanieArray[8]=respuestaH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.15";
		/*задание №16 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 3<br>Experiencias de uno de los jóvenes talentos con más futur o en la actuación<p style='text-align:justify;  color:black;'>– ¿Crees que algún día podrías llegar a dejar la vida del actor para siempre?</p>RESPUESTAS:";
			zadanieArray[1]=respuestaA;
			zadanieArray[2]=respuestaB;
			zadanieArray[3]=respuestaC;
			zadanieArray[4]=respuestaD;
			zadanieArray[5]=respuestaE;
			zadanieArray[6]=respuestaF;
			zadanieArray[7]=respuestaG;
			zadanieArray[8]=respuestaH;
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.16";
		/*задание №17 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 4<br>Lea el siguiente texto. Complete las oraciones eligiendo para cada uno de los huecos (16-21) una de las opciones (A-H) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>Saber qué llevar y cómo guardarlo es todo un arte, pero una vez que se aprende (17)&nbsp;_____.</p>";
			zadanieArray[1]="se rompan";
			zadanieArray[2]="no manchen la ropa";
			zadanieArray[3]="casi nunca se producen";
			zadanieArray[4]="vas a llevar a tu destino";
			zadanieArray[5]="siga la forma de la maleta";
			zadanieArray[6]="sea fácil de combinar entre ella";
			zadanieArray[7]="llévalo puesto durante el trayecto";
			zadanieArray[8]="se convierte en una rutina sencilla y rápida";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=maletaPerfecta;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.17";
		/*задание №18 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 4<br>Lea el siguiente texto. Complete las oraciones eligiendo para cada uno de los huecos (16-21) una de las opciones (A-H) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>Antes de hacer la maleta haz una lista con todo lo que (18)&nbsp;_____, teniendo en cuenta qué temperatura hace y qué vas a hacer allí.</p>";
			zadanieArray[1]="se rompan";
			zadanieArray[2]="no manchen la ropa";
			zadanieArray[3]="casi nunca se producen";
			zadanieArray[4]="vas a llevar a tu destino";
			zadanieArray[5]="siga la forma de la maleta";
			zadanieArray[6]="sea fácil de combinar entre ella";
			zadanieArray[7]="llévalo puesto durante el trayecto";
			zadanieArray[8]="se convierte en una rutina sencilla y rápida";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=maletaPerfecta;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.18";
		/*задание №19 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 4<br>Lea el siguiente texto. Complete las oraciones eligiendo para cada uno de los huecos (16-21) una de las opciones (A-H) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>A menudo las maletas suelen llenarse de prendas que metemos para situaciones hipotéticas que (19)&nbsp;_____.</p>";
			zadanieArray[1]="se rompan";
			zadanieArray[2]="no manchen la ropa";
			zadanieArray[3]="casi nunca se producen";
			zadanieArray[4]="vas a llevar a tu destino";
			zadanieArray[5]="siga la forma de la maleta";
			zadanieArray[6]="sea fácil de combinar entre ella";
			zadanieArray[7]="llévalo puesto durante el trayecto";
			zadanieArray[8]="se convierte en una rutina sencilla y rápida";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=maletaPerfecta;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.19";
		/*задание №20 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 4<br>Lea el siguiente texto. Complete las oraciones eligiendo para cada uno de los huecos (16-21) una de las opciones (A-H) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>Dentro de zapatos o botas tienes un espacio rígido, donde puedes meter cosas que no quieres que (20)&nbsp;_____ (por ejemplo, un collar de cristales de Swarovski).</p>";
			zadanieArray[1]="se rompan";
			zadanieArray[2]="no manchen la ropa";
			zadanieArray[3]="casi nunca se producen";
			zadanieArray[4]="vas a llevar a tu destino";
			zadanieArray[5]="siga la forma de la maleta";
			zadanieArray[6]="sea fácil de combinar entre ella";
			zadanieArray[7]="llévalo puesto durante el trayecto";
			zadanieArray[8]="se convierte en una rutina sencilla y rápida";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=maletaPerfecta;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.20";
		/*задание №21 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 4<br>Lea el siguiente texto. Complete las oraciones eligiendo para cada uno de los huecos (16-21) una de las opciones (A-H) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>Los zapatos deben ir en bolsas individuales y bien encajados para que (21)&nbsp;_____.</p>";
			zadanieArray[1]="se rompan";
			zadanieArray[2]="no manchen la ropa";
			zadanieArray[3]="casi nunca se producen";
			zadanieArray[4]="vas a llevar a tu destino";
			zadanieArray[5]="siga la forma de la maleta";
			zadanieArray[6]="sea fácil de combinar entre ella";
			zadanieArray[7]="llévalo puesto durante el trayecto";
			zadanieArray[8]="se convierte en una rutina sencilla y rápida";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=maletaPerfecta;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.21";
		/*задание №22 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 4<br>Lea el siguiente texto. Complete las oraciones eligiendo para cada uno de los huecos (16-21) una de las opciones (A-H) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>El cinturón enrollado ocupa más, así que colócalo estirado de manera que (22)&nbsp;_____.</p>";
			zadanieArray[1]="se rompan";
			zadanieArray[2]="no manchen la ropa";
			zadanieArray[3]="casi nunca se producen";
			zadanieArray[4]="vas a llevar a tu destino";
			zadanieArray[5]="siga la forma de la maleta";
			zadanieArray[6]="sea fácil de combinar entre ella";
			zadanieArray[7]="llévalo puesto durante el trayecto";
			zadanieArray[8]="se convierte en una rutina sencilla y rápida";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=maletaPerfecta;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.22";
		/*задание №23 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>Según los resultados de una encuesta sobre (23)&nbsp;_____ deportivos de los españoles,...</p>"; 
			zadanieArray[1]="los excesos";
			zadanieArray[2]="los criterios";
			zadanieArray[3]="los aspectos";
			zadanieArray[4]="los hábitos";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="5.23";			
		/*задание №24 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>...con un porcentaje mayor en (24)&nbsp;_____ de personas más jóvenes.</p>"; 
			zadanieArray[1]="el caso";
			zadanieArray[2]="el instante";
			zadanieArray[3]="el lado";
			zadanieArray[4]="el lazo";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.24";
		/*задание №25 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>En su gran mayoría, los españoles hacen deporte por su (25)&nbsp;_____, al margen de clubes o asociaciones.</p>"; 
			zadanieArray[1]="cuesta";
			zadanieArray[2]="cuenta";
			zadanieArray[3]="culpa";
			zadanieArray[4]="medio";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.25";
		/*задание №26 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>No es de extrañar, por ello, que el deporte más practicado sea la gimnasia de mantenimiento, (26)&nbsp;_____ a bastante distancia por el fútbol, la natación y el ciclismo.</p>"; 
			zadanieArray[1]="seguida";
			zadanieArray[2]="guiada";
			zadanieArray[3]="incluida";
			zadanieArray[4]="traída";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.26";
		/*задание №27 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>Un aspecto importante para la difusión popular del deporte es (27)&nbsp;_____ del obstáculo que constituía la escasez de instalaciones.</p>";
			zadanieArray[1]="el mejoramiento";
			zadanieArray[2]="el aumento";
			zadanieArray[3]="la superación";
			zadanieArray[4]="la creación";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.27";
		/*задание №28 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>Los resultados de la encuesta (28)&nbsp;_____ la mejora progresiva de los equipamientos deportivos...</p>";
			zadanieArray[1]="carecen";
			zadanieArray[2]="impulsan";
			zadanieArray[3]="confirman";
			zadanieArray[4]="configuran";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.28";
		/*задание №29 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>...(29)&nbsp;_____ de los polideportivos cubiertos, cuyo número casi se duplica entre 1990 y 2010,...</p>";
			zadanieArray[1]="el logro";
			zadanieArray[2]="el incremento";
			zadanieArray[3]="la muestra";
			zadanieArray[4]="el descenso";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.29";
		/*задание №30 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>...es un buen indicador de esa mejora, porque estos equipamientos se pueden utilizar a lo (30)&nbsp;_____ de todo el año, con horarios muy amplios y flexibles.</p>";
			zadanieArray[1]="habitual";
			zadanieArray[2]="largo";
			zadanieArray[3]="ancho";
			zadanieArray[4]="reciente";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.30";
		/*задание №31 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>La encuesta (31)&nbsp;_____ otros aspectos de la cuestión,...</p>";
			zadanieArray[1]="abarca";
			zadanieArray[2]="acude";
			zadanieArray[3]="alcanza";
			zadanieArray[4]="avanza";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.31";
		/*задание №32 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 5<br>Lea el siguiente texto. Complete el texto eligiendo para cada uno de los huecos (22-33) una de las cuatro opciones (A-D) que se le ofrecen.<br> <p style='text-align:justify;  color:black;'>...entre los que se cuenta (32)&nbsp;_____ muy positiva que merecen, para un elevado porcentaje de encuestados, los resultados de España en las competiciones deportivas internacionales.</p>";
			zadanieArray[1]="la concesión";
			zadanieArray[2]="la prestación";
			zadanieArray[3]="la formación";
			zadanieArray[4]="la valoración";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=resultados;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="5.32";
		/*задание №33 ЗНО-2014 испанский язык. Основной тест(доделать!!!)*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>El año pasado no pudimos ir _____ vacaciones, no teníamos ni un euro.";
			zadanieArray[1]="para";
			zadanieArray[2]="a";
			zadanieArray[3]="en";
			zadanieArray[4]="de";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="6.33";
		/*задание №34 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>¿No crees que el paseo _____ muy divertido?";
			zadanieArray[1]="fuera";
			zadanieArray[2]="sea";
			zadanieArray[3]="será";
			zadanieArray[4]="haya sido";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="6.34";
		/*задание №35 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>Si _____, lo harían de otra manera.";
			zadanieArray[1]="podrían";
			zadanieArray[2]="pudiesen";
			zadanieArray[3]="pudieron";
			zadanieArray[4]="podrán";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.35";
		/*задание №36 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>El abuelo siempre se enfada, pero no lo hace _____ serio.";
			zadanieArray[1]="en";
			zadanieArray[2]="de";
			zadanieArray[3]="a";
			zadanieArray[4]="con";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.36";
		/*задание №37 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=37;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>Le pedí que _____ un poco.";
			zadanieArray[1]="esperara";
			zadanieArray[2]="espere";
			zadanieArray[3]="espera";
			zadanieArray[4]="esperará";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.37";
		/*задание №38 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=38;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>¿Tienes _____ verdad la intención de hacerlo?";
			zadanieArray[1]="de";
			zadanieArray[2]="por";
			zadanieArray[3]="a";
			zadanieArray[4]="en";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.38";
		/*задание №39 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=39;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>No _____ escribirme cuando estés en Lima.";
			zadanieArray[1]="olvida";
			zadanieArray[2]="olvidas";
			zadanieArray[3]="olvide";
			zadanieArray[4]="olvides";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.39";
		/*задание №40 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=40;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>Estos pantalones me quedan bien. _____ llevo.";
			zadanieArray[1]="Los me";
			zadanieArray[2]="Me ellos";
			zadanieArray[3]="Me los";
			zadanieArray[4]="Ellos me";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.40";
		/*задание №41 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=41;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>_____ hacía un frío terrible, fui en taxi.";
			zadanieArray[1]="como";
			zadanieArray[2]="porque";
			zadanieArray[3]="como si";
			zadanieArray[4]="por lo tanto";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="6.41";
		/*задание №42 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=42;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 6<br>No sólo lo dice, _____ que lo afirma con seguridad.";
			zadanieArray[1]="puesto";
			zadanieArray[2]="así";
			zadanieArray[3]="sino";
			zadanieArray[4]="pero";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="6.42";
		/*задание №43 ЗНО-2014 испанский язык. Основной тест*/
			taskNumber=43;
			var zadanieArray=new Array();
			zadanieArray[0]="TAREA 7<br>Expresión escrita<br>Usted tiene que ausentarse unos días de su domicilio. Escriba una carta a una persona con la que tiene gran amistad y confianza para que se ocupe de la casa. En la carta deberá:<ul><li>pedirle el favor y justificar la ausencia;</li><li>decirle las cosas que tiene que hacer;</li><li>mencionar la dirección y el teléfono donde puede localizarle durante su ausencia.</li></ul>Redacte una carta de 100 palabras como mínimo."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]="";
			taskTypeArray[taskNumber-1]="tvir";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=14;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="7.43";
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}	/* Окончание ЗНО-2014 испанский язык. Основной тест. I сессия*/	
	
/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();
}
