function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	/*Массив названий тестов*/
	var taskNameArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/

/*************************************************************/
//Тесты по математике
/*************************************************************/	

/*ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
	if(testName==znoMat2015DemoAdv)
	{
		testLength=38;
		timeCounter=210*60;
		testTime=timeCounter;
		testDirectory='\/test\/mat\/img\/test2015demo\/';
		testTitle = znoName+"2015"+znoMatName+advancedName;
		testDetails=demoName;
		answerLanguage="rus";
		gradeArray=new Array("100.0","102.0","106.5","108.0","110.0","111.0","113.0","115.0","118.5","120.0","124.0","126.0","128.0","132.5","134.0","136.0","138.0","139.0","140.0","142.0","144.5","149.0","151.0","152.5","154.0","156.0","157.0","158.5","159.5","161.0","162.0","163.0","164.5","165.5","166.5","167.5","168.5","170.0","171.0","172.0","173.0","174.0","175.0","176.0","177.0","178.0","179.0","180.0","181.0","182.0","183.0","184.0","185.0","186.5","187.5","188.5","189.5","191.0","192.0","193.5","195.0","196.0","197.5","198.5","199.5","200.0","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var taskNumber=1;
		taskNameArray[taskNumber-1]=""; 
		/*задание №1 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Виразіть у відсотках число 1/5.";
			zadanieArray[1]="2%";
			zadanieArray[2]="20%";
			zadanieArray[3]="50%";
			zadanieArray[4]="0,2%";
			zadanieArray[5]="1,5%";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
		/*задание №2 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="Відрізок, довжина якого дорівнює 60 см, розділений точками на чотири рівні відрізки. Визначте відстань між серединами отриманих крайніх відрізків.";
			zadanieArray[1]="36 см";
			zadanieArray[2]="40 см";
			zadanieArray[3]="45 см";
			zadanieArray[4]="48 см";
			zadanieArray[5]="50 см";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №3 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть добуток коренів рівняння <i>х<sup>2</sup> + 6х - 55 = 0.</i>";
			zadanieArray[1]="-55";
			zadanieArray[2]="55";
			zadanieArray[3]="-6";
			zadanieArray[4]="6";
			zadanieArray[5]="-49";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №4 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №4 ЗНО-2015 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №5 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №5 ЗНО-2015 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №6 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено паралелограм <i>ABCD</i>. Які з наведених тверджень є правильними?<br/>I. &ang;А  + &ang;B + &ang;C + &ang;D = 360&deg;<br/>II. &ang;А + &ang;D = 180&deg;</br>III. &ang;B - &ang;A &gt; 0&deg;  ";
			zadanieArray[1]="лише I";
			zadanieArray[2]="лише I i II";
			zadanieArray[3]="лише II";
			zadanieArray[4]="лише I i III";
			zadanieArray[5]="I, II i III";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №7 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="Розв’яжіть рівняння <i>log<sub>3</sub>x = -1.</i>";
			zadanieArray[1]="1/3";
			zadanieArray[2]="3";
			zadanieArray[3]="-1";
			zadanieArray[4]="-3";
			zadanieArray[5]="-1/3";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
			/*задание №8 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=8;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="Визначте площу сфери, діаметр якої дорівнює 12&nbsp;см.";
			zadanieArray[1]="36&pi; см<sup>2</sup>";
			zadanieArray[2]="72&pi; см<sup>2</sup>";
			zadanieArray[3]="144&pi; см<sup>2</sup>";
			zadanieArray[4]="288&pi; см<sup>2</sup>";
			zadanieArray[5]="576&pi; см<sup>2</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №9 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=9;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="Довжини перпендикулярних векторів <i><span style='text-decoration:overline;'>a</span></i> і <i><span style='text-decoration:overline;'>b</span></i> (див. рисунок) дорівнюють 6 і 8 відповідно. Знайдіть довжину вектора <i><span style='text-decoration:overline;'>a</span></i>+<i><span style='text-decoration:overline;'>b</span></i>.";
			zadanieArray[1]="2";
			zadanieArray[2]="6";
			zadanieArray[3]="8";
			zadanieArray[4]="10";
			zadanieArray[5]="14";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №10 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="Якщо <i>&radic;<span style='text-decoration:overline;'>x</span> + y = 5</i> і <i>&radic;<span style='text-decoration:overline;'>x</span> - y = 7</i>, то <i>у</i> дорівнює";
			zadanieArray[1]="-2";
			zadanieArray[2]="-1";
			zadanieArray[3]="3";
			zadanieArray[4]="2";
			zadanieArray[5]="1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №11 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Майстер обслуговує лише три верстати: 20&nbsp;% робочого часу він обслуговує перший верстат, 30&nbsp;% - другий, 50&nbsp;% - третій. Обчисліть імовірність того, що в навмання вибраний момент робочого часу майстер обслуговує перший або третій верстат.";
			zadanieArray[1]="0,8";
			zadanieArray[2]="0,7";
			zadanieArray[3]="0,5";
			zadanieArray[4]="0,3";
			zadanieArray[5]="0,1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №12 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №12 ЗНО-2015 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №13 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="Яке з наведених рівнянь не має коренів?";
			zadanieArray[1]="sin x = &radic;<span style='text-decoration:overline;'>3</span>/2";
			zadanieArray[2]="tg x = &radic;<span style='text-decoration:overline;'>3</span>/2";
			zadanieArray[3]="ctg x = -2/&radic;<span style='text-decoration:overline;'>3</span>";
			zadanieArray[4]="tg x = 2/&radic;<span style='text-decoration:overline;'>3</span>";
			zadanieArray[5]="cos x = 2/&radic;<span style='text-decoration:overline;'>3</span>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №14 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть <i>36<sup>log<sub>6</sub>5</sup></i>.";
			zadanieArray[1]="5";
			zadanieArray[2]="6";
			zadanieArray[3]="10";
			zadanieArray[4]="25";
			zadanieArray[5]="36";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №15 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено куб <i>ABCDA<sub>1</sub>B<sub>1</sub>C<sub>1</sub>D<sub>1</sub></i>. Визначте градусну міру кута між прямими <i>АВ<sub>1</sub></i> і <i>DD<sub>1</sub></i>.";
			zadanieArray[1]="0&deg;";
			zadanieArray[2]="30&deg;";
			zadanieArray[3]="45&deg;";
			zadanieArray[4]="60&deg;";
			zadanieArray[5]="90&deg;";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №16 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №16 ЗНО-2015 Математика. Пробный тест . Углубленный уровень";
			zadanieArray[1]="a";
			zadanieArray[2]="b";
			zadanieArray[3]="c";
			zadanieArray[4]="d";
			zadanieArray[5]="e";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №17 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Якщо <i>a &isin; (-2; 3)</i>, то <i>|a<sup>2</sup> - a - 6| =</i> ";
			zadanieArray[1]="a<sup>2</sup> - a - 6";
			zadanieArray[2]="a<sup>2</sup> + a - 6";
			zadanieArray[3]="a<sup>2</sup> + a + 6";
			zadanieArray[4]="-a<sup>2</sup> + a + 6";
			zadanieArray[5]="-a<sup>2</sup> - a + 6";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №18 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Розв’яжіть нерівність <i>2&sdot;(0,3)<sup>x</sup> &lt; 0,18</i>";
			zadanieArray[1]="(-&infin; ; 2)";
			zadanieArray[2]="(2 ; +&infin;)";
			zadanieArray[3]="(-&infin; ; 0,3)";
			zadanieArray[4]="(0,3 ; +&infin;)";
			zadanieArray[5]="(0 ; 2)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №19 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="Визначте для функції <i>f(х) = 2х + 2</i> первісну, графік якої проходить через точку <i>(1; 4)</i>.";
			zadanieArray[1]="F(x) = 2x<sup>2</sup> + 2x";
			zadanieArray[2]="F(x) = x<sup>2</sup> + 2x + 1";
			zadanieArray[3]="F(x) = x<sup>2</sup> + 2x + 2";
			zadanieArray[4]="F(x) = x<sup>2</sup> + 2x - 4";
			zadanieArray[5]="F(x) = 2x<sup>2</sup> + x + 1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №20 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено розгортку прямокутного паралелепіпеда. Використовуючи зазначені на рисунку розміри, обчисліть об’єм цього паралелепіпеда.";
			zadanieArray[1]="96 см<sup>2</sup>";
			zadanieArray[2]="108 см<sup>2</sup>";
			zadanieArray[3]="128 см<sup>2</sup>";
			zadanieArray[4]="136 см<sup>2</sup>";
			zadanieArray[5]="144 см<sup>2</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №21 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між виразом (1-4) та тотожно рівним йому виразом (А-Д).";
			zadanieArray[1]="1&nbsp;-&nbsp;cos<sup>2</sup>&alpha;";
			zadanieArray[2]="2&nbsp;sin&alpha;&nbsp;cos&alpha;";
			zadanieArray[3]="cos<sup>2</sup>&alpha;&nbsp;-&nbsp;sin<sup>2</sup>&alpha;";
			zadanieArray[4]="cos<sup>4</sup>&alpha;&nbsp;+&nbsp;sin<sup>2</sup>&alpha;cos<sup>2</sup>&alpha;";
			zadanieArray[5]="cos<sup>2</sup>&alpha;";
			zadanieArray[6]="cos2&alpha;";
			zadanieArray[7]="sin2&alpha;";
			zadanieArray[8]="-cos2&alpha;";
			zadanieArray[9]="sin<sup>2</sup>&alpha;";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="ecba";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №22 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між функцією (1-4) та її властивістю (А-Д).";
			zadanieArray[1]="y&nbsp;=&nbsp;x<sup>2</sup>";
			zadanieArray[2]="y&nbsp;=&nbsp;x<sup>3</sup>&nbsp;+&nbsp;1";
			zadanieArray[3]="y&nbsp;=&nbsp;3&nbsp;-&nbsp;x";
			zadanieArray[4]="y&nbsp;=&nbsp;sin&nbsp;x";
			zadanieArray[5]="зростає на всій області визначення";
			zadanieArray[6]="спадає на всій області визначення";
			zadanieArray[7]="є непарною";
			zadanieArray[8]="є парною";
			zadanieArray[9]="областю значень функції є проміжок (0; +&infin;)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="dabc";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №23 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між запитанням (1-4) та правильною відповіддю на нього (А-Д)."; 
			zadanieArray[1]="На якому рисунку зображено трикутник, у якого центри вписаного й описаного кіл збігаються?";
			zadanieArray[2]="На якому рисунку зображено трикутник, один із внутрішніх кутів якого дорівнює 30&deg;?";
			zadanieArray[3]="На якому рисунку зображено трикутник, площа якого дорівнює 10&nbsp; см<sup>2</sup>?";
			zadanieArray[4]="На якому рисунку зображено трикутник, у якого діаметр описаного навколо нього кола дорівнює 10&radic;<span style='text-decoration:overline;'>2</span>&nbsp;см?";
			zadanieArray[5]="Рис.&nbsp;1";
			zadanieArray[6]="Рис.&nbsp;2";
			zadanieArray[7]="Рис.&nbsp;3";
			zadanieArray[8]="Рис.&nbsp;4";
			zadanieArray[9]="Рис.&nbsp;5";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection_picture";
			answerArray[taskNumber-1]="aced";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №24 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="У прямокутній декартовій системі координат <i>хуz</i> у просторі задано точку <i>М&nbsp;(1;&nbsp;-4;&nbsp;8)</i>. Установіть відповідність між початком речення (1-4) та його закінченням (А-Д) так, щоб утворилося правильне твердження.";
			zadanieArray[1]="Відстань від точки&nbsp;<i>M</i> до площини <i>ху</i> дорівнює";
			zadanieArray[2]="Відстань від точки&nbsp;<i>M</i> до початку координат дорівнює";
			zadanieArray[3]="Відстань від точки&nbsp;<i>M</i> до осі <i>z</i> дорівнює";
			zadanieArray[4]="Відстань від точки&nbsp;<i>M</i> до  точки&nbsp;N&nbsp;(1;&nbsp;0;&nbsp;8) дорівнює";
			zadanieArray[5]="1";
			zadanieArray[6]="4";
			zadanieArray[7]="&radic;<span style='text-decoration:overline;'>17</span>";
			zadanieArray[8]="8";
			zadanieArray[9]="9";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="decb";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №25 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Відстань між двома містами велосипедист долає за 2&nbsp;години, а пішохід - за 6&nbsp;годин. Уважайте, що швидкості велосипедиста і пішохода є сталими протягом усього шляху.<p>1.Визначте відстань між містами (у&nbsp;км), якщо швидкість велосипедиста на 12&nbsp;км/год більша за швидкість пішохода.</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=36;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.1"; 
			/*задание №26 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Відстань між двома містами велосипедист долає за 2&nbsp;години, а пішохід - за 6&nbsp;годин. Уважайте, що швидкості велосипедиста і пішохода є сталими протягом усього шляху.<p>2. Пішохід і велосипедист одночасно вирушили назустріч один одному з цих двох міст. Через скільки годин після початку руху вони зустрінуться?</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 1.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.2"; 
			/*задание №27 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="У ромб <i>ABCD</i> вписано коло з центром у точці&nbsp;<i>О</i>, яке дотикається сторін <i>АВ</i> і <i>АD</i> у точках&nbsp;<i>K</i> і <i>M</i> відповідно (див. рисунок). Периметр ромба дорівнює 48 см, <i>&ang;A&nbsp;</i>=&nbsp;60&deg;. Знайдіть:<p>1. Довжину відрізка <i>ОВ</i> (у&nbsp;см).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]= 6;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.1"; 
			/*задание №28 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="У ромб <i>ABCD</i> вписано коло з центром у точці&nbsp;<i>О</i>, яке дотикається сторін <i>АВ</i> і <i>АD</i> у точках&nbsp;<i>K</i> і <i>M</i> відповідно (див. рисунок). Периметр ромба дорівнює 48 см, <i>&ang;A&nbsp;</i>=&nbsp;60&deg;. Знайдіть:<p>1. Довжину відрізка <i>КМ</i> (у&nbsp;см).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]= 9;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.2";
			/*задание №29 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="Повна вартість доставки великогабаритних меблів у фірмі із перевезень складається з вартості їх доставки на 1-й&nbsp;поверх будинку і вартості підйому меблів на потрібний поверх. Вартість підйому меблів на кожен наступний поверх перевищує вартість їх підйому на попередній на одну й ту саму величину. Визначте повну вартість (у грн) доставки меблів на 11-й&nbsp;поверх будинку, якщо повна вартість доставки меблів на 4-й та 7-й&nbsp; поверхи цього будинку становить 142&nbsp;грн та 154&nbsp;грн відповідно."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 170;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="27";
			/*задание №30 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №28 ЗНО-2015 Математика. Пробный тест . Углубленный уровень"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 3.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="28";
			/*задание №31 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №29 ЗНО-2015 Математика. Пробный тест . Углубленный уровень"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= -83;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]="29";
			/*задание №32 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="Об’єм тіла, утвореного обертанням рівнобедреного трикутника навколо висоти, проведеної до його основи, дорівнює 320&pi;&nbsp;см<sup>3</sup>. Обчисліть довжину бічної сторони цього трикутника (у&nbsp;см), якщо його основа дорівнює 16&nbsp;см."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 17;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
			taskNameArray[taskNumber-1]="30"; 
			/*задание №33 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №31 ЗНО-2015 Математика. Пробный тест . Углубленный уровень";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= -16;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="31";
			/*задание №34 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="Для роботи на уроках геометрії учню потрібно придбати лінійку й транспортир. У магазині канцелярських товарів у продажу є три види транспортирів та чотири види лінійок, а також два види наборів, що складаються з лінійки й транспортира. Скільки всього в учня є варіантів придбання лінійки й транспортира в цьому магазині?";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 14;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="32";
			/*задание №35 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Усі бічні грані правильної чотирикутної піраміди нахилені до площини її основи під кутом 60°. Площа повної поверхні піраміди дорівнює 54&radic;<span style='text-decoration:overline;'>6</span>&nbsp;см<sup>2</sup>. Обчисліть площу (у&nbsp; см<sup>2</sup>) перерізу цієї піраміди площиною, що проходить через висоту піраміди й діагональ її основи.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 27;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="33";		
			/*задание №36 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="За якого значення параметра <i>с</i> найменше значення функції<p align=center>y = x<sup>4</sup> - 8x<sup>2</sup> + c</p>на відрізку [-1; 3] дорівнює 30?";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 46;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="34";		
		/*задание №37 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=37;
			var zadanieArray=new Array();
			zadanieArray[0]="У трапеції&nbsp;<i>ABCD</i> (<i>ВС</i>||<i>AD</i>) діагональ&nbsp;<i>AC</i> є бісектрисою гострого кута&nbsp;<i>A</i>. Ця діагональ перетинає середню лінію трапеції в точці&nbsp;<i>P</i>.<p>1.Доведіть, що &ang;APВ&nbsp;=&nbsp;90&deg;</p><p>2.	Обчисліть площу трапеції&nbsp;<i>ABCD</i>, якщо <i>ВС</i>&nbsp;=&nbsp;5&nbsp;см, <i>AD</i>&nbsp;=&nbsp;13&nbsp;см, площа трикутника&nbsp;<i>АРВ</i> дорівнює 5&nbsp;см<sup>2</sup>.</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 36;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="35";	
		/*задание №38 ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
			taskNumber=38;
			var zadanieArray=new Array();
			zadanieArray[0]="Знайдіть значення параметра <i>a</i>, за яких рівняння<p align=center>ах - 3 = &radic;<span style='text-decoration:overline;'>&nbsp;-x<sup>2</sup> + 18x – 72&nbsp;</span></p>має єдиний корінь.<br>У відповідь запишіть суму розв'язків, що є кратними 0,25.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 1;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=6;
			variantNumberArray[taskNumber-1]=5;			
		     taskNameArray[taskNumber-1]="36";	
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}/*конец ЗНО-2015 Математика. Пробный тест . Углубленный уровень*/
	
/*ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
	if(testName==znoMat2015Demo)
	{
		testLength=32;
		timeCounter=130*60;
		testTime=timeCounter;
		testDirectory='\/test\/mat\/img\/test2015demo\/';
		testTitle = znoName+"2015"+znoMatName+basicName;
		testDetails=demoName;
		answerLanguage="rus";
		gradeArray=new Array("100.0","102.0","106.5","113.0","118.5","124.0","128.0","132.5","136.0","140.0","144.5","149.0","151.0","154.0","156.0","157.0","158.5","159.5","161.0","163.0","164.5","165.5","167.5","168.5","170.0","171.0","172.0","173.0","175.0","176.0","177.0","178.0","179.0","181.0","182.0","183.0","184.0","185.0","186.5","188.5","189.5","191.0","192.0","193.5","195.0","196.0","198.5","199.5","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var taskNumber=1;
		taskNameArray[taskNumber-1]=""; 
		/*задание №1 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Виразіть у відсотках число 1/5.";
			zadanieArray[1]="2%";
			zadanieArray[2]="20%";
			zadanieArray[3]="50%";
			zadanieArray[4]="0,2%";
			zadanieArray[5]="1,5%";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
		/*задание №2 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="Відрізок, довжина якого дорівнює 60 см, розділений точками на чотири рівні відрізки. Визначте відстань між серединами отриманих крайніх відрізків.";
			zadanieArray[1]="36 см";
			zadanieArray[2]="40 см";
			zadanieArray[3]="45 см";
			zadanieArray[4]="48 см";
			zadanieArray[5]="50 см";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №3 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть добуток коренів рівняння <i>х<sup>2</sup> + 6х - 55 = 0.</i>";
			zadanieArray[1]="-55";
			zadanieArray[2]="55";
			zadanieArray[3]="-6";
			zadanieArray[4]="6";
			zadanieArray[5]="-49";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №4 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №4 ЗНО-2015 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №5 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №5 ЗНО-2015 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №6 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено паралелограм <i>ABCD</i>. Які з наведених тверджень є правильними?<br/>I. &ang;А  + &ang;B + &ang;C + &ang;D = 360&deg;<br/>II. &ang;А + &ang;D = 180&deg;</br>III. &ang;B - &ang;A &gt; 0&deg;  ";
			zadanieArray[1]="лише I";
			zadanieArray[2]="лише I i II";
			zadanieArray[3]="лише II";
			zadanieArray[4]="лише I i III";
			zadanieArray[5]="I, II i III";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №7 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="Розв’яжіть рівняння <i>log<sub>3</sub>x = -1.</i>";
			zadanieArray[1]="1/3";
			zadanieArray[2]="3";
			zadanieArray[3]="-1";
			zadanieArray[4]="-3";
			zadanieArray[5]="-1/3";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
			/*задание №8 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=8;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="Визначте площу сфери, діаметр якої дорівнює 12&nbsp;см.";
			zadanieArray[1]="36&pi; см<sup>2</sup>";
			zadanieArray[2]="72&pi; см<sup>2</sup>";
			zadanieArray[3]="144&pi; см<sup>2</sup>";
			zadanieArray[4]="288&pi; см<sup>2</sup>";
			zadanieArray[5]="576&pi; см<sup>2</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №9 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=9;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="Довжини перпендикулярних векторів <i><span style='text-decoration:overline;'>a</span></i> і <i><span style='text-decoration:overline;'>b</span></i> (див. рисунок) дорівнюють 6 і 8 відповідно. Знайдіть довжину вектора <i><span style='text-decoration:overline;'>a</span></i>+<i><span style='text-decoration:overline;'>b</span></i>.";
			zadanieArray[1]="2";
			zadanieArray[2]="6";
			zadanieArray[3]="8";
			zadanieArray[4]="10";
			zadanieArray[5]="14";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №10 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="Якщо <i>&radic;<span style='text-decoration:overline;'>x</span> + y = 5</i> і <i>&radic;<span style='text-decoration:overline;'>x</span> - y = 7</i>, то <i>у</i> дорівнює";
			zadanieArray[1]="-2";
			zadanieArray[2]="-1";
			zadanieArray[3]="3";
			zadanieArray[4]="2";
			zadanieArray[5]="1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №11 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Майстер обслуговує лише три верстати: 20&nbsp;% робочого часу він обслуговує перший верстат, 30&nbsp;% - другий, 50&nbsp;% - третій. Обчисліть імовірність того, що в навмання вибраний момент робочого часу майстер обслуговує перший або третій верстат.";
			zadanieArray[1]="0,8";
			zadanieArray[2]="0,7";
			zadanieArray[3]="0,5";
			zadanieArray[4]="0,3";
			zadanieArray[5]="0,1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №12 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №12 ЗНО-2015 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №13 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="Яке з наведених рівнянь не має коренів?";
			zadanieArray[1]="sin x = &radic;<span style='text-decoration:overline;'>3</span>/2";
			zadanieArray[2]="tg x = &radic;<span style='text-decoration:overline;'>3</span>/2";
			zadanieArray[3]="ctg x = -2/&radic;<span style='text-decoration:overline;'>3</span>";
			zadanieArray[4]="tg x = 2/&radic;<span style='text-decoration:overline;'>3</span>";
			zadanieArray[5]="cos x = 2/&radic;<span style='text-decoration:overline;'>3</span>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №14 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть <i>36<sup>log<sub>6</sub>5</sup></i>.";
			zadanieArray[1]="5";
			zadanieArray[2]="6";
			zadanieArray[3]="10";
			zadanieArray[4]="25";
			zadanieArray[5]="36";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №15 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено куб <i>ABCDA<sub>1</sub>B<sub>1</sub>C<sub>1</sub>D<sub>1</sub></i>. Визначте градусну міру кута між прямими <i>АВ<sub>1</sub></i> і <i>DD<sub>1</sub></i>.";
			zadanieArray[1]="0&deg;";
			zadanieArray[2]="30&deg;";
			zadanieArray[3]="45&deg;";
			zadanieArray[4]="60&deg;";
			zadanieArray[5]="90&deg;";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №16 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №16 ЗНО-2015 Математика. Пробный тест . Базовый уровень";
			zadanieArray[1]="a";
			zadanieArray[2]="b";
			zadanieArray[3]="c";
			zadanieArray[4]="d";
			zadanieArray[5]="e";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №17 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Якщо <i>a &isin; (-2; 3)</i>, то <i>|a<sup>2</sup> - a - 6| =</i> ";
			zadanieArray[1]="a<sup>2</sup> - a - 6";
			zadanieArray[2]="a<sup>2</sup> + a - 6";
			zadanieArray[3]="a<sup>2</sup> + a + 6";
			zadanieArray[4]="-a<sup>2</sup> + a + 6";
			zadanieArray[5]="-a<sup>2</sup> - a + 6";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №18 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Розв’яжіть нерівність <i>2&sdot;(0,3)<sup>x</sup> &lt; 0,18</i>";
			zadanieArray[1]="(-&infin; ; 2)";
			zadanieArray[2]="(2 ; +&infin;)";
			zadanieArray[3]="(-&infin; ; 0,3)";
			zadanieArray[4]="(0,3 ; +&infin;)";
			zadanieArray[5]="(0 ; 2)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №19 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="Визначте для функції <i>f(х) = 2х + 2</i> первісну, графік якої проходить через точку <i>(1; 4)</i>.";
			zadanieArray[1]="F(x) = 2x<sup>2</sup> + 2x";
			zadanieArray[2]="F(x) = x<sup>2</sup> + 2x + 1";
			zadanieArray[3]="F(x) = x<sup>2</sup> + 2x + 2";
			zadanieArray[4]="F(x) = x<sup>2</sup> + 2x - 4";
			zadanieArray[5]="F(x) = 2x<sup>2</sup> + x + 1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №20 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено розгортку прямокутного паралелепіпеда. Використовуючи зазначені на рисунку розміри, обчисліть об’єм цього паралелепіпеда.";
			zadanieArray[1]="96 см<sup>2</sup>";
			zadanieArray[2]="108 см<sup>2</sup>";
			zadanieArray[3]="128 см<sup>2</sup>";
			zadanieArray[4]="136 см<sup>2</sup>";
			zadanieArray[5]="144 см<sup>2</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №21 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між виразом (1-4) та тотожно рівним йому виразом (А-Д).";
			zadanieArray[1]="1&nbsp;-&nbsp;cos<sup>2</sup>&alpha;";
			zadanieArray[2]="2&nbsp;sin&alpha;&nbsp;cos&alpha;";
			zadanieArray[3]="cos<sup>2</sup>&alpha;&nbsp;-&nbsp;sin<sup>2</sup>&alpha;";
			zadanieArray[4]="cos<sup>4</sup>&alpha;&nbsp;+&nbsp;sin<sup>2</sup>&alpha;cos<sup>2</sup>&alpha;";
			zadanieArray[5]="cos<sup>2</sup>&alpha;";
			zadanieArray[6]="cos2&alpha;";
			zadanieArray[7]="sin2&alpha;";
			zadanieArray[8]="-cos2&alpha;";
			zadanieArray[9]="sin<sup>2</sup>&alpha;";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="ecba";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №22 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між функцією (1-4) та її властивістю (А-Д).";
			zadanieArray[1]="y&nbsp;=&nbsp;x<sup>2</sup>";
			zadanieArray[2]="y&nbsp;=&nbsp;x<sup>3</sup>&nbsp;+&nbsp;1";
			zadanieArray[3]="y&nbsp;=&nbsp;3&nbsp;-&nbsp;x";
			zadanieArray[4]="y&nbsp;=&nbsp;sin&nbsp;x";
			zadanieArray[5]="зростає на всій області визначення";
			zadanieArray[6]="спадає на всій області визначення";
			zadanieArray[7]="є непарною";
			zadanieArray[8]="є парною";
			zadanieArray[9]="областю значень функції є проміжок (0; +&infin;)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="dabc";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №23 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між запитанням (1-4) та правильною відповіддю на нього (А-Д)."; 
			zadanieArray[1]="На якому рисунку зображено трикутник, у якого центри вписаного й описаного кіл збігаються?";
			zadanieArray[2]="На якому рисунку зображено трикутник, один із внутрішніх кутів якого дорівнює 30&deg;?";
			zadanieArray[3]="На якому рисунку зображено трикутник, площа якого дорівнює 10&nbsp; см<sup>2</sup>?";
			zadanieArray[4]="На якому рисунку зображено трикутник, у якого діаметр описаного навколо нього кола дорівнює 10&radic;<span style='text-decoration:overline;'>2</span>&nbsp;см?";
			zadanieArray[5]="Рис.&nbsp;1";
			zadanieArray[6]="Рис.&nbsp;2";
			zadanieArray[7]="Рис.&nbsp;3";
			zadanieArray[8]="Рис.&nbsp;4";
			zadanieArray[9]="Рис.&nbsp;5";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection_picture";
			answerArray[taskNumber-1]="aced";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №24 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="У прямокутній декартовій системі координат <i>хуz</i> у просторі задано точку <i>М&nbsp;(1;&nbsp;-4;&nbsp;8)</i>. Установіть відповідність між початком речення (1-4) та його закінченням (А-Д) так, щоб утворилося правильне твердження.";
			zadanieArray[1]="Відстань від точки&nbsp;<i>M</i> до площини <i>ху</i> дорівнює";
			zadanieArray[2]="Відстань від точки&nbsp;<i>M</i> до початку координат дорівнює";
			zadanieArray[3]="Відстань від точки&nbsp;<i>M</i> до осі <i>z</i> дорівнює";
			zadanieArray[4]="Відстань від точки&nbsp;<i>M</i> до  точки&nbsp;N&nbsp;(1;&nbsp;0;&nbsp;8) дорівнює";
			zadanieArray[5]="1";
			zadanieArray[6]="4";
			zadanieArray[7]="&radic;<span style='text-decoration:overline;'>17</span>";
			zadanieArray[8]="8";
			zadanieArray[9]="9";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="decb";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №25 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Відстань між двома містами велосипедист долає за 2&nbsp;години, а пішохід - за 6&nbsp;годин. Уважайте, що швидкості велосипедиста і пішохода є сталими протягом усього шляху.<p>1.Визначте відстань між містами (у&nbsp;км), якщо швидкість велосипедиста на 12&nbsp;км/год більша за швидкість пішохода.</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=36;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.1"; 
			/*задание №26 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Відстань між двома містами велосипедист долає за 2&nbsp;години, а пішохід - за 6&nbsp;годин. Уважайте, що швидкості велосипедиста і пішохода є сталими протягом усього шляху.<p>2. Пішохід і велосипедист одночасно вирушили назустріч один одному з цих двох міст. Через скільки годин після початку руху вони зустрінуться?</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 1.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.2"; 
			/*задание №27 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="У ромб <i>ABCD</i> вписано коло з центром у точці&nbsp;<i>О</i>, яке дотикається сторін <i>АВ</i> і <i>АD</i> у точках&nbsp;<i>K</i> і <i>M</i> відповідно (див. рисунок). Периметр ромба дорівнює 48 см, <i>&ang;A&nbsp;</i>=&nbsp;60&deg;. Знайдіть:<p>1. Довжину відрізка <i>ОВ</i> (у&nbsp;см).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]= 6;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.1"; 
			/*задание №28 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="У ромб <i>ABCD</i> вписано коло з центром у точці&nbsp;<i>О</i>, яке дотикається сторін <i>АВ</i> і <i>АD</i> у точках&nbsp;<i>K</i> і <i>M</i> відповідно (див. рисунок). Периметр ромба дорівнює 48 см, <i>&ang;A&nbsp;</i>=&nbsp;60&deg;. Знайдіть:<p>1. Довжину відрізка <i>КМ</i> (у&nbsp;см).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]= 9;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.2";
			/*задание №29 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="Повна вартість доставки великогабаритних меблів у фірмі із перевезень складається з вартості їх доставки на 1-й&nbsp;поверх будинку і вартості підйому меблів на потрібний поверх. Вартість підйому меблів на кожен наступний поверх перевищує вартість їх підйому на попередній на одну й ту саму величину. Визначте повну вартість (у грн) доставки меблів на 11-й&nbsp;поверх будинку, якщо повна вартість доставки меблів на 4-й та 7-й&nbsp; поверхи цього будинку становить 142&nbsp;грн та 154&nbsp;грн відповідно."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 170;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="27";
			/*задание №30 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №28 ЗНО-2015 Математика. Пробный тест . Базовый уровень"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 3.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="28";
			/*задание №31 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №29 ЗНО-2015 Математика. Пробный тест . Базовый уровень"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= -83;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]="29";
			/*задание №32 ЗНО-2015 Математика. Пробный тест . Базовый уровень*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="Об’єм тіла, утвореного обертанням рівнобедреного трикутника навколо висоти, проведеної до його основи, дорівнює 320&pi;&nbsp;см<sup>3</sup>. Обчисліть довжину бічної сторони цього трикутника (у&nbsp;см), якщо його основа дорівнює 16&nbsp;см."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 17;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
			taskNameArray[taskNumber-1]="30"; 
				
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}/*конец ЗНО-2015 Математика. Пробный тест . Базовый уровень*/


/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();		
		
}
