function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	/*Массив названий тестов*/
	var taskNameArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/
/*************************************************************/
//Тесты по английскому языку	
/*************************************************************/	
/*ЗНО-2014 английский язык. Основной тест. I сессия*/
	if(testName==znoEng2014Main)
	{
		testLength=43;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/eng\/img\/test2014main\/';
		testTitle = znoName+"2014"+znoEngName;
		testDetails=mainName;
		answerLanguage="eng";
		gradeArray=new Array("100.0","100.5","101.0","102.0","104.5","107.5","111.0","115.0","119.0","122.5","125.5","128.0","130.0","132.0","133.5","135.0","136.5","137.5","139.0","140.0","141.0","142.5","143.5","144.5","145.5","147.0","148.0","149.0","150.5","151.5","152.5","154.0","155.0","156.0","157.5","158.5","160.0","161.5","163.0","164.5","166.0","167.5","169.0","170.5","172.5","174.5","176.5","178.5","180.5","183.0","185.5","188.5","191.5","194.5","197.0","199.0","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var studyTips="\tTop Five Study Tips\n\n1 __________\nMake sure you have all the materials you need at hand before you start studying. Getting up to look for a pencil sharpener or ruler will break your concentration and waste your time. \n\n2 __________ \nThink about what it will mean for you if you do well in your studies. How will it make you feel? If you keep the end result in mind it will help you succeed in studying. You might like to find an image or something that represents success for you and put it somewhere you can see it while you’re studying. \n\n3 __________ \nUse a calendar or a list of dates or a wall planner to keep track of exam dates and assignment due dates. Space out your study time each week for the whole term/semester - don’t try to cram it all in the night before! \nDo the hardest work when you’re feeling your best. Save the easy stuff for when you’re tired. \nSet yourself a time limit for each task and follow it. \n\n4 __________ \nYou study better when you’re feeling good. So make sure you eat well and get enough sleep. Exercise is great but don’t overdo it. \nIt’s also a good idea to schedule regular breaks when you’re studying and keep hydrated. If you follow these steps you will study better. \n\n5 __________ \nTaking detailed notes in class or at home will save you a lot of time later. Re-writing and adding to your notes is a great way to revise what you’ve learned.";
		var wakeUpways="\tA Different Way to Wake Up\n\tBy Catherine Clarke Fox \n\nMatty Sallin’s alarm clock wakes you up with the aroma of sizzling bacon. When Matty Sallin, 34, was working on a degree in art and technology at New York University, he got an interesting assignment in electronics class: Create something for the household. He decided to create an alarm clock. \n\n“Everybody has to deal with these every day, and they are extremely unpleasant!” he says. He asked different people what they’d like to wake up to instead of a clanging, noisy alarm. A lot of them said, “The smell of bacon.“ \n\nSo Sallin and two classmates invented a new kind of alarm clock: a wooden box with a pig face and a digital clock that uses the smell of cooking bacon rather than sound to wake someone up. He explains, “There’s no danger of burning, because I built it carefully. It uses halogen light bulbs instead of a flame for cooking and turns off automatically after ten minutes.” Just a few easy steps are required to set the “alarm”. \n\n“What you do is put a couple of frozen strips in the night before,” says Sallin. Bacon is cured, or preserved, so there is no danger of it spoiling overnight. \n\n“If you set the alarm for 8:00, it will turn on at 7:50 and slow cook for ten minutes under the halogen bulbs”, he says. Then the bulbs turn off and a fan blows the scent out through the nostrils of the pig. \n\n“So instead of an alarm or a beep or a radio, you smell yourself awake”, says Sallin. “Then you can open the door on the side and pull the bacon out and eat it.” \n\nWhen Sallin was a kid, he spent a lot of time making drawings of inventions. “I wanted to make an elevator in my back yard and a special tree house,” he says. “But I never really thought I’d be called an inventor!” \n\nSallin got an A in the class and went on to other things – but people continue to hear about his invention and email him every day asking where they can buy his alarm clock. \n\nThese days he designs computer software, but if he decides to produce and sell his aroma alarm, maybe he can develop some other models. Any votes for cinnamon buns?";
		var musicForSoul="\tMusic for the Soul\n\nIt is impossible for me (17) ___________ when it comes to the subject of music or the music program in school. I have been in my school’s band since I was in the sixth grade. The unity and structure of the music caught my ear and pulled me in (18) ____________. I was interested in how so many instruments could all have different parts and still fit together (19) ________. I toyed with the thought of playing multiple instruments before I decided to follow my big brother’s footsteps and invest in a saxophone. Six years have passed since (20) ___________ for the first time and I still enjoy playing. \n\nAlthough I do view my school as a very fun and exciting place with eccentric teachers and great students, I would not enjoy it if it was (21) ___________. For the people in a band, music class is an escape from the math, English, and science classes they take every day. Music is a way for students (22) ________________. As a music fan, I sleep, read, and do homework better when there is music constantly playing in the background.";
		var thisWeakDream="\tThis Week’s Dream\n\nMost pubs in Bermuda have two TVs, one for cricket and one for baseball. In recent decades, American cultural (23) __________ over this little archipelago in the western Atlantic has been strong, but it remains a British Overseas Territory – the oldest of all. Bermuda is oldfashioned, democratic and very friendly – (24) __________ the eye of any stranger in the street and they’ll smile and say hello. \n\nThe island was known (25) __________ the Spanish but still uninhabited in 1609, when Sir George Somers ran aground on a sandbank in a storm and (26) __________ it for the Crown. The “pretty” town of St George’s, which he founded, is the oldest English (27) __________ in the New World. \n\nPink is the island’s “defining colour”. It’s a popular shade for the neatly pressed Bermuda shorts (28) __________ by some locals (usually with a jacket and a tie). Many of the island’s bungalows are pink, its buses are pink – and so are its beaches, (29) __________ to grains of coral in the sand. (30) __________ Bermuda’s other natural wonders are Crystal Cave – a cavern complex with stalagmites and stalactites – and its rich bird’s life: like Prospero’s isle, “(31) __________ of noises, sounds and sweet airs”, Bermuda “thrums to the sound of birdsong (32) __________ dawn and twilight”.";
		var japanUnderSnow="\tJapan under Snow \n\nWhy do so few of us think of (33) __________ Japan in winter? On the north island of Hokkaido, snow is as (34) __________ as in Finnish Lapland, but it’s not as cold. And the resorts are (35) __________ managed and the facilities are first-class. At Rusutsu there are 18 miles of groomed trails, catering to all abilities, through well-spaced birch and bamboo forests. Niseko is even (36) __________, with 30 miles of trails and plenty of off-piste too. After a hard day in this “Oriental (37) __________ wonderland” you can visit a traditional onsen for a shiatsu massage and a dip in the steam bath, guaranteeing a good night’s sleep.";
		var turkeyPardon="\tThe Turkey Pardon \n\nEach year at Thanksgiving, the President of the United States (38) __________ a gift of a live turkey (along (39) __________ an alternate in case something (40) __________ to the official turkey). At a White House ceremony, the president (41) ___________ “pardons” the National Thanksgiving Turkey and the alternate turkeys, allowing them (42) __________ out the rest of their lives on a farm.";
		var taskNumber=1;
		/*задание №1 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<p style='text-align:justify;  color:black;'>Select correct title for paragraph №1.</p>";
			zadanieArray[1]="Take care of yourself";
			zadanieArray[2]="Organize your working space";
			zadanieArray[3]="Get creative";
			zadanieArray[4]="Clear your mind";
			zadanieArray[5]="Write down and review";
			zadanieArray[6]="Plan your time";
			zadanieArray[7]="Socialize and relax";
			zadanieArray[8]="Get motivated";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=studyTips;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.1";	
		/*задание №2 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<p style='text-align:justify;  color:black;'>Select correct title for paragraph №2.</p>";
			zadanieArray[1]="Take care of yourself";
			zadanieArray[2]="Organize your working space";
			zadanieArray[3]="Get creative";
			zadanieArray[4]="Clear your mind";
			zadanieArray[5]="Write down and review";
			zadanieArray[6]="Plan your time";
			zadanieArray[7]="Socialize and relax";
			zadanieArray[8]="Get motivated";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=studyTips;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.2";	
		/*задание №3 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<p style='text-align:justify;  color:black;'>Select correct title for paragraph №3.</p>";
			zadanieArray[1]="Take care of yourself";
			zadanieArray[2]="Organize your working space";
			zadanieArray[3]="Get creative";
			zadanieArray[4]="Clear your mind";
			zadanieArray[5]="Write down and review";
			zadanieArray[6]="Plan your time";
			zadanieArray[7]="Socialize and relax";
			zadanieArray[8]="Get motivated";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=studyTips;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.3";	
		/*задание №4 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<p style='text-align:justify;  color:black;'>Select correct title for paragraph №4.</p>";
			zadanieArray[1]="Take care of yourself";
			zadanieArray[2]="Organize your working space";
			zadanieArray[3]="Get creative";
			zadanieArray[4]="Clear your mind";
			zadanieArray[5]="Write down and review";
			zadanieArray[6]="Plan your time";
			zadanieArray[7]="Socialize and relax";
			zadanieArray[8]="Get motivated";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=studyTips;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.4";		
		/*задание №5 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<p style='text-align:justify;  color:black;'>Select correct title for paragraph №5.</p>";
			zadanieArray[1]="Take care of yourself";
			zadanieArray[2]="Organize your working space";
			zadanieArray[3]="Get creative";
			zadanieArray[4]="Clear your mind";
			zadanieArray[5]="Write down and review";
			zadanieArray[6]="Plan your time";
			zadanieArray[7]="Socialize and relax";
			zadanieArray[8]="Get motivated";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=studyTips;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="1.5";		
		/*задание №6 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>Which of the following is TRUE about Matty Sallin?</p>"; 
			zadanieArray[1]="He taught at New York University.";
			zadanieArray[2]="He liked fried bacon for breakfast.";
			zadanieArray[3]="He got up at 8 in the morning when a student.";
			zadanieArray[4]="He got the idea of his alarm clock from others.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=wakeUpways;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.6";
		/*задание №7 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>What does the word “they“ in line <i style='color:red;'>“Everybody has to deal with these every day, and they are extremely unpleasant!”</i> stand for?</p>"; 
			zadanieArray[1]="household chores";
			zadanieArray[2]="alarm clocks";
			zadanieArray[3]="assignments";
			zadanieArray[4]="classes";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=wakeUpways;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.7";
		/*задание №8 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>Which is NOT mentioned in the text about the new alarm clock?</p>"; 
			zadanieArray[1]="It’s available in several models.";
			zadanieArray[2]="It’s a result of team work.";
			zadanieArray[3]="It’s popular with people.";
			zadanieArray[4]="It’s safe to use.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=wakeUpways;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.8";
		/*задание №9 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>What is Matty working on now?</p>"; 
			zadanieArray[1]="halogen bulbs";
			zadanieArray[2]="a backyard elevator";
			zadanieArray[3]="a cinnamon alarm";
			zadanieArray[4]="computer programs";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=wakeUpways;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.9";
		/*задание №10 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>Which of the following does the author mention in the text?</p>"; 
			zadanieArray[1]="Matty was given the task to make an alarm clock.";
			zadanieArray[2]="Matty was successful in selling his aroma alarm.";
			zadanieArray[3]="Matty’s alarm clock fulfils two functions.";
			zadanieArray[4]="Matty’s alarm gives three beeping sounds.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=wakeUpways;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2.10";
		/*задание №11 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:black;'>This kid ___________.</p>";
			zadanieArray[1]="would like to be a water expert";
			zadanieArray[2]="shows experiences to others";
			zadanieArray[3]="dreams of far-away voyages";
			zadanieArray[4]="goes exploring with a pet";
			zadanieArray[5]="worries about using too much water";
			zadanieArray[6]="has prepared for the exploration experience";
			zadanieArray[7]="found an alternative way to view water life";
			zadanieArray[8]="likes long boating trips";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.11";
		/*задание №12 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:black;'>This kid ___________.</p>";
			zadanieArray[1]="would like to be a water expert";
			zadanieArray[2]="shows experiences to others";
			zadanieArray[3]="dreams of far-away voyages";
			zadanieArray[4]="goes exploring with a pet";
			zadanieArray[5]="worries about using too much water";
			zadanieArray[6]="has prepared for the exploration experience";
			zadanieArray[7]="found an alternative way to view water life";
			zadanieArray[8]="likes long boating trips";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="g";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.12";
		/*задание №13 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:black;'>This kid ___________.</p>";
			zadanieArray[1]="would like to be a water expert";
			zadanieArray[2]="shows experiences to others";
			zadanieArray[3]="dreams of far-away voyages";
			zadanieArray[4]="goes exploring with a pet";
			zadanieArray[5]="worries about using too much water";
			zadanieArray[6]="has prepared for the exploration experience";
			zadanieArray[7]="found an alternative way to view water life";
			zadanieArray[8]="likes long boating trips";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.13";
		/*задание №14 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:black;'>This kid ___________.</p>";
			zadanieArray[1]="would like to be a water expert";
			zadanieArray[2]="shows experiences to others";
			zadanieArray[3]="dreams of far-away voyages";
			zadanieArray[4]="goes exploring with a pet";
			zadanieArray[5]="worries about using too much water";
			zadanieArray[6]="has prepared for the exploration experience";
			zadanieArray[7]="found an alternative way to view water life";
			zadanieArray[8]="likes long boating trips";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.14";
		/*задание №15 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:black;'>This kid ___________.</p>";
			zadanieArray[1]="would like to be a water expert";
			zadanieArray[2]="shows experiences to others";
			zadanieArray[3]="dreams of far-away voyages";
			zadanieArray[4]="goes exploring with a pet";
			zadanieArray[5]="worries about using too much water";
			zadanieArray[6]="has prepared for the exploration experience";
			zadanieArray[7]="found an alternative way to view water life";
			zadanieArray[8]="likes long boating trips";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.15";
		/*задание №16 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:black;'>This kid ___________.</p>";
			zadanieArray[1]="would like to be a water expert";
			zadanieArray[2]="shows experiences to others";
			zadanieArray[3]="dreams of far-away voyages";
			zadanieArray[4]="goes exploring with a pet";
			zadanieArray[5]="worries about using too much water";
			zadanieArray[6]="has prepared for the exploration experience";
			zadanieArray[7]="found an alternative way to view water life";
			zadanieArray[8]="likes long boating trips";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
			taskNameArray[taskNumber-1]="3.16";
		/*задание №17 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>It is impossible for me (17)&nbsp;__________ when it comes to the subject of music or the music program in school.</p>";
			zadanieArray[1]="to relax from the tension of homework or tests";
			zadanieArray[2]="showing up to play for them";
			zadanieArray[3]="like a jigsaw puzzle";
			zadanieArray[4]="to be completely objective";
			zadanieArray[5]="lacking a music program";
			zadanieArray[6]="holding my saxophone";
			zadanieArray[7]="like a fish at the end of a line";
			zadanieArray[8]="the lack of live music";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=musicForSoul;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.17";
		/*задание №18 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The unity and structure of the music caught my ear and pulled me in (18)&nbsp;__________ .</p>";
			zadanieArray[1]="to relax from the tension of homework or tests";
			zadanieArray[2]="showing up to play for them";
			zadanieArray[3]="like a jigsaw puzzle";
			zadanieArray[4]="to be completely objective";
			zadanieArray[5]="lacking a music program";
			zadanieArray[6]="holding my saxophone";
			zadanieArray[7]="like a fish at the end of a line";
			zadanieArray[8]="the lack of live music";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="g";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=musicForSoul;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.18";
		/*задание №19 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>I was interested in how so many instruments could all have different parts and still fit together (19)&nbsp;__________ .</p>";
			zadanieArray[1]="to relax from the tension of homework or tests";
			zadanieArray[2]="showing up to play for them";
			zadanieArray[3]="like a jigsaw puzzle";
			zadanieArray[4]="to be completely objective";
			zadanieArray[5]="lacking a music program";
			zadanieArray[6]="holding my saxophone";
			zadanieArray[7]="like a fish at the end of a line";
			zadanieArray[8]="the lack of live music";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=musicForSoul;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.19";
		/*задание №20 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Six years have passed since (20)&nbsp;__________  for the first time and I still enjoy playing.</p>";
			zadanieArray[1]="to relax from the tension of homework or tests";
			zadanieArray[2]="showing up to play for them";
			zadanieArray[3]="like a jigsaw puzzle";
			zadanieArray[4]="to be completely objective";
			zadanieArray[5]="lacking a music program";
			zadanieArray[6]="holding my saxophone";
			zadanieArray[7]="like a fish at the end of a line";
			zadanieArray[8]="the lack of live music";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=musicForSoul;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.20";
		/*задание №21 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Although I do view my school as a very fun and exciting place with eccentric teachers and great students, I would not enjoy it if it was (21)&nbsp;__________ .</p>";
			zadanieArray[1]="to relax from the tension of homework or tests";
			zadanieArray[2]="showing up to play for them";
			zadanieArray[3]="like a jigsaw puzzle";
			zadanieArray[4]="to be completely objective";
			zadanieArray[5]="lacking a music program";
			zadanieArray[6]="holding my saxophone";
			zadanieArray[7]="like a fish at the end of a line";
			zadanieArray[8]="the lack of live music";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=musicForSoul;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.21";
		/*задание №22 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Music is a way for students (22)&nbsp;__________ .</p>";
			zadanieArray[1]="to relax from the tension of homework or tests";
			zadanieArray[2]="showing up to play for them";
			zadanieArray[3]="like a jigsaw puzzle";
			zadanieArray[4]="to be completely objective";
			zadanieArray[5]="lacking a music program";
			zadanieArray[6]="holding my saxophone";
			zadanieArray[7]="like a fish at the end of a line";
			zadanieArray[8]="the lack of live music";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=musicForSoul;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="4.22";
		/*задание №23 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>In recent decades, American cultural (23)&nbsp;__________ over this little archipelago in the western Atlantic has been strong, but it remains a British Overseas Territory – the oldest of all.</p>"; 
			zadanieArray[1]="effect";
			zadanieArray[2]="influence";
			zadanieArray[3]="presence";
			zadanieArray[4]="introduction";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="5.23";			
		/*задание №24 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>.Bermuda is oldfashioned, democratic and very friendly – (24)&nbsp;__________the eye of any stranger in the street and they’ll smile and say hello.</p>"; 
			zadanieArray[1]="get";
			zadanieArray[2]="take";
			zadanieArray[3]="hold";
			zadanieArray[4]="catch";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.24";
		/*задание №25 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The island was known (25)&nbsp;__________ the Spanish but still uninhabited in 1609...</p>"; 
			zadanieArray[1]="to";
			zadanieArray[2]="at";
			zadanieArray[3]="in";
			zadanieArray[4]="for";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.25";
		/*задание №26 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...when Sir George Somers ran aground on a sandbank in a storm and (26)&nbsp;__________ it for the Crown.</p>"; 
			zadanieArray[1]="devoted";
			zadanieArray[2]="requested";
			zadanieArray[3]="claimed";
			zadanieArray[4]="dedicated";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.26";
		/*задание №27 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The “pretty” town of St George’s, which he founded, is the oldest English (27)&nbsp;__________in the New World.</p>"; 
			zadanieArray[1]="public";
			zadanieArray[2]="group";
			zadanieArray[3]="community";
			zadanieArray[4]="audience";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.27";
		/*задание №28 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>It’s a popular shade for the neatly pressed Bermuda shorts (28)&nbsp;__________ by some locals (usually with a jacket and a tie).</p>"; 
			zadanieArray[1]="put";
			zadanieArray[2]="worn";
			zadanieArray[3]="carried";
			zadanieArray[4]="dressed";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.28";
		/*задание №29 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Many of the island’s bungalows are pink, its buses are pink – and so are its beaches, (29)&nbsp;__________to grains of coral in the sand.</p>"; 
			zadanieArray[1]="in order";
			zadanieArray[2]="because";
			zadanieArray[3]="in spite";
			zadanieArray[4]="thanks";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.29";
		/*задание №30 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>(30)&nbsp;__________ Bermuda’s other natural wonders are Crystal Cave – a cavern complex with stalagmites and stalactites...</p>"; 
			zadanieArray[1]="Within";
			zadanieArray[2]="Among";
			zadanieArray[3]="Between";
			zadanieArray[4]="Along";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.30";
		/*задание №31 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...and its rich bird’s life: like Prospero’s isle, “ (31)&nbsp;__________of noises, sounds and sweet airs”...</p>"; 
			zadanieArray[1]="full";
			zadanieArray[2]="packed";
			zadanieArray[3]="rich";
			zadanieArray[4]="filled";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5.31";
		/*задание №32 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Bermuda “thrums to the sound of birdsong (32)&nbsp;__________dawn and twilight”.</p>"; 
			zadanieArray[1]="on";
			zadanieArray[2]="in";
			zadanieArray[3]="at";
			zadanieArray[4]="by";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=thisWeakDream;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="5.32";
		/*задание №33 ЗНО-2014 английский язык. Основной тест(доделать!!!)*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Why do so few of us think of (33)&nbsp;__________ Japan in winter?</p>";
			zadanieArray[1]="visit";
			zadanieArray[2]="visited";
			zadanieArray[3]="visiting";
			zadanieArray[4]="visits";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=japanUnderSnow;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="6.33";
		/*задание №34 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>On the north island of Hokkaido, snow is as (34)&nbsp;__________ as in Finnish Lapland, but it’s not as cold.</p>";
			zadanieArray[1]="guaranteed";
			zadanieArray[2]="guaranty";
			zadanieArray[3]="guarantee";
			zadanieArray[4]="guaranteeing";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=japanUnderSnow;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="6.34";
		/*задание №35 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>And the resorts are (35)&nbsp;__________ managed and the facilities are first-class.</p>";
			zadanieArray[1]="beauty";
			zadanieArray[2]="beautiful";
			zadanieArray[3]="beautify";
			zadanieArray[4]="beautifully";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=japanUnderSnow;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="6.35";
		/*задание №36 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Niseko is even (36)&nbsp;__________, with 30 miles of trails and plenty of off-piste too.</p>"; 
			zadanieArray[1]="big";
			zadanieArray[2]="biggest";
			zadanieArray[3]="bigger";
			zadanieArray[4]="the biggest";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=japanUnderSnow;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.36";
		/*задание №37 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=37;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>After a hard day in this “Oriental (37)&nbsp;__________wonderland” you can visit a traditional onsen for a shiatsu massage and a dip in the steam bath, guaranteeing a good night’s sleep.</p>"; 
			zadanieArray[1]="winters";
			zadanieArray[2]="winter";
			zadanieArray[3]="winters’";
			zadanieArray[4]="winter’s";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=japanUnderSnow;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.37";
		/*задание №38 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=38;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Each year at Thanksgiving, the President of the United States (38)&nbsp;__________ a gift of a live turkey...</p>"; 
			zadanieArray[1]="receive";
			zadanieArray[2]="received";
			zadanieArray[3]="is receiving";
			zadanieArray[4]="receives";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=turkeyPardon;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.38";
		/*задание №39 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=39;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...along (39)&nbsp;__________ an alternate in case...</p>"; 
			zadanieArray[1]="of";
			zadanieArray[2]="with";
			zadanieArray[3]="for";
			zadanieArray[4]="in";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=turkeyPardon;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.39";
		/*задание №40 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=40;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...in case something (40)&nbsp;__________ to the official turkey...</p>"; 
			zadanieArray[1]="happen";
			zadanieArray[2]="will happen";
			zadanieArray[3]="happens";
			zadanieArray[4]="is happening";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=turkeyPardon;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.40";
		/*задание №41 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=41;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>At a White House ceremony, the president (41)&nbsp;__________ “pardons” the National Thanksgiving Turkey and the alternate turkeys...</p>"; 
			zadanieArray[1]="traditionally";
			zadanieArray[2]="traditional";
			zadanieArray[3]="tradition";
			zadanieArray[4]="traditionary";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=turkeyPardon;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.41";
		/*задание №42 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=42;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...allowing them (42)&nbsp;__________ out the rest of their lives on a farm.</p>"; 
			zadanieArray[1]="live";
			zadanieArray[2]="to live";
			zadanieArray[3]="living";
			zadanieArray[4]="lived";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=turkeyPardon;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="6.42";
		/*задание №43 ЗНО-2014 английский язык. Основной тест*/
			taskNumber=43;
			var zadanieArray=new Array();
			zadanieArray[0]="Writing<br>You have received a letter from your pen-friend in which he/she complains that his/her parents want him/her to read classical authors, while he/she is fond of fantasy. <br>Write a letter to your pen-friend in which you tell him/her<ul><li>whether your parents influence your choice of books to read</li><li>what is your favorite literary genre and why</li><li>where you usually get books you’d like to read</li></ul>Write a letter of at least 100 words. Do not use any personal information (e. g., names, dates, addresses, etc.). Start your letter in an appropriate way."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]="";
			taskTypeArray[taskNumber-1]="tvir";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=14;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="Writing.43";
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}	/* Окончание ЗНО-2014 английский язык. Основной тест. I сессия*/	
	
/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/
		startInitialization();
}
