function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	/*Массив названий тестов*/
	var taskNameArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/

/*************************************************************/
//Тесты по математике
/*************************************************************/	

/*ЗНО-2014 Математика. Пробный тест*/
	if(testName==znoMat2014Demo)
	{
		testLength=36;
		timeCounter=150*60;
		testTime=timeCounter;
		testDirectory='\/test\/mat\/img\/test2014demo\/';
		testTitle = znoName+"2014"+znoMatName;
		testDetails=demoName;
		answerLanguage="rus";
		gradeArray=new Array("100.0","100.5","102.0","105.5","107.0","108.5","110.0","115.0","120.0","124.5","129.0","133.0","136.5","139.5","142.0","144.5","146.5","148.5","150.5","152.5","154.5","156.0","158.0","160.0","161.5","163.5","165.0","166.5","168.5","170.0","171.5","173.0","174.0","175.5","176.5","178.0","179.0","180.5","181.5","183.0","184.0","185.5","186.5","187.5","189.0","190.0","191.0","192.0","193.0","194.0","195.0","196.0","197.0","198.0","198.5","199.0","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var taskNumber=1;
		taskNameArray[taskNumber-1]=""; 
		/*задание №1 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть запис числа 0,351 у стандартному вигляді.";
			zadanieArray[1]="3,51•10<sup>-1</sup>";
			zadanieArray[2]="3,51•10<sup>1</sup>";
			zadanieArray[3]="3,51•10<sup>-2</sup>";
			zadanieArray[4]="3,51•10<sup>2</sup>";
			zadanieArray[5]="3,51•10<sup>-3</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
		/*задание №2 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="У трикутнику ABC проведено висоту ВМ (див. рисунок). Визначте градусну міру кута МВА, якщо &ang; А = 40°.";
			zadanieArray[1]="20&deg;";
			zadanieArray[2]="45&deg;";
			zadanieArray[3]="50&deg;";
			zadanieArray[4]="60&deg;";
			zadanieArray[5]="90&deg;";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №3 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №3 ЗНО-2014 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №4 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="Яка   з   наведених   послідовностей   є   геометричною   прогресією, <br>знаменник якої <i>q < 0</i>?";
			zadanieArray[1]="-25; 20;-15; 10";
			zadanieArray[2]="-80;-40;-20;-10";
			zadanieArray[3]="30; 10;-10;-30";
			zadanieArray[4]="10;-20; 40;-80";
			zadanieArray[5]="-15;-30;-45;-60";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №5 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="На круговій діаграмі (круг поділено пунктирними лініями на рівні сектори) показано розподіл кількості столів, які продано магазином протягом місяця (див. рисунок). Загальна кількість проданих столів за цей період становила 108. Скільки було серед них журнальних столів?";
			zadanieArray[1]="9";
			zadanieArray[2]="18";
			zadanieArray[3]="27";
			zadanieArray[4]="36";
			zadanieArray[5]="54";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №6 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №6 ЗНО-2014 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №7 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено фрагмент графіка однієї з наведених функцій на відрізку [-1; 1]. Укажіть цю функцію.";
			zadanieArray[1]="<i>y</i> = -<i>x</i><sup>2</sup>";
			zadanieArray[2]="<i>y</i> = sin<i>x</i>";
			zadanieArray[3]="<i>y</i> = tg<i>x</i>";
			zadanieArray[4]="<i>y</i> = cos<i>x</i>";
			zadanieArray[5]="<i>y</i> = <i>x</i><sup>2</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
			/*задание №8 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="задание №8 ЗНО-2014 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №9 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено паралелограм <i>ABCD</i>, діагоналі якого перетинаються в точці <i>О</i>. Укажіть пару колінеарних векторів. ";
			zadanieArray[1]="<i><span style='text-decoration:overline;'>AB</span> i <span style='text-decoration:overline;'>BC</span></i>";
			zadanieArray[2]="<i><span style='text-decoration:overline;'>AC</span> i <span style='text-decoration:overline;'>BD</span></i>";
			zadanieArray[3]="<i><span style='text-decoration:overline;'>AO</span> i <span style='text-decoration:overline;'>OD</span></i>";
			zadanieArray[4]="<i><span style='text-decoration:overline;'>BO</span> i <span style='text-decoration:overline;'>BD</span></i>";
			zadanieArray[5]="<i><span style='text-decoration:overline;'>BC</span> i <span style='text-decoration:overline;'>BD</span></i>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №10 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="Коло задано рівнянням <i>х</i><sup>2</sup> + <i>у</i><sup>2</sup> = 9.  Визначте координати точки, яка належить кругу, обмеженому цим колом.";
			zadanieArray[1]="(&radic;<span style='text-decoration:overline;'>2</span>; 5)";
			zadanieArray[2]="(1; 3)";
			zadanieArray[3]="(4; 5)";
			zadanieArray[4]="(3; 2)";
			zadanieArray[5]="(2; &radic;<span style='text-decoration:overline;'>3</span>)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №11 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть правильну нерівність, якщо <br><i>а</i> = sin 120&deg;, <i>b</i> = cos 120&deg;.";
			zadanieArray[1]="<i>0&lt;a&lt;b</i>";
			zadanieArray[2]="<i>a&lt;0&lt;b</i>";
			zadanieArray[3]="<i>a&lt;b&lt;0</i>";
			zadanieArray[4]="<i>b&lt;0&lt;a</i>";
			zadanieArray[5]="<i>0&lt;b&lt;a</i>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №12 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено куб <i>ABCDA<sub>1</sub>B<sub>1</sub>C<sub>1</sub>D<sub>1</sub></i>, ребро якого дорівнює 1 см. Обчисліть відстань від точки <i>А</i> до прямої <i>В<sub>1</sub>С<sub>1</sub></i>.";
			zadanieArray[1]="1 см";
			zadanieArray[2]="2 см";
			zadanieArray[3]="&radic;<span style='text-decoration:overline;'>2</span> см";
			zadanieArray[4]="3 см";
			zadanieArray[5]="1,5 см";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №13 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="Знайдіть усі значення <i>х</i>, <br>при яких значення виразу <i>2 - 5х</i><br> належить проміжку (-3; 6).";
			zadanieArray[1]="<i>-1&lt;x&lt;0,8</i>";
			zadanieArray[2]="<i>-0,8&lt;x&lt;1</i>";
			zadanieArray[3]="<i>0&lt;x&lt;9</i>";
			zadanieArray[4]="<i>-1,6&lt;x&lt;0,2</i>";
			zadanieArray[5]="<i>-0,2&lt;x&lt;1,6</i>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №14 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Функція <i>у = f(x)</i> зростає на проміжку (-&infin;; +&infin;). <br>Яке з наведених чисел може бути значенням цієї функції в точці <i>х</i> = 8, <br>якщо <i>f</i>(1) = -2, <i>f</i>(9) = 5?";
			zadanieArray[1]="-8";
			zadanieArray[2]="-3";
			zadanieArray[3]="-2";
			zadanieArray[4]="3";
			zadanieArray[5]="8";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №15 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="Довжина кола основи циліндра дорівнює 18&pi;&nbsp;см. Визначте площу бічної поверхні цього циліндра, якщо його висота дорівнює 7 см.";
			zadanieArray[1]="126&pi; см<sup>2</sup>";
			zadanieArray[2]="207&pi; см<sup>2</sup>";
			zadanieArray[3]="252&pi; см<sup>2</sup>";
			zadanieArray[4]="288&pi; см<sup>2</sup>";
			zadanieArray[5]="567&pi; см<sup>2</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №16 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="|2 - &radic;<span style='text-decoration:overline;'>5</span>| + |2 + &radic;<span style='text-decoration:overline;'>5</span>| =";
			zadanieArray[1]="4";
			zadanieArray[2]="2&radic;<span style='text-decoration:overline;'>5</span>";
			zadanieArray[3]="4 + 2&radic;<span style='text-decoration:overline;'>5</span>";
			zadanieArray[4]="4 - 2&radic;<span style='text-decoration:overline;'>5</span>";
			zadanieArray[5]="2&radic;<span style='text-decoration:overline;'>5</span> - 4";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №17 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Точка <i>М</i> не належить площині <i>&alpha;</i>. Які з наведених тверджень є правильними?<p>I. Через точку <i>М</i> можна провести лише одну площину, паралельну площині <i>&alpha;</i>.</p><p>II. Через точку <i>М</i> можна провести лише одну площину, перпендикулярну до площини <i>&alpha;</i>.</p><p>III. Через точку <i>М</i> можна провести лише одну площину, що перетинає площину а під кутом 45&deg;.</p>";
			zadanieArray[1]="лише І";
			zadanieArray[2]="лише II";
			zadanieArray[3]="лише І і III";
			zadanieArray[4]="лише II і III";
			zadanieArray[5]="I, II і III";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №18 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Знайдіть похідну функції<br> <i>у = х<sup>7</sup>lnх.</i>";
			zadanieArray[1]="y'=7x<sup>5</sup>";
			zadanieArray[2]="у'=7х<sup>6</sup>lnх + х<sup>6</sup>";
			zadanieArray[3]="y'=x<sup>6</sup>lnx + x<sup>6</sup>";
			zadanieArray[4]="у'=7х<sup>6</sup>lnх";
			zadanieArray[5]="у'=7хlnх + х<sup>6</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №19 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="Об'єм конуса дорівнює 64 см<sup>3</sup>. Через середину висоти цього конуса паралельно його основі проведено площину. Утворений переріз є основою меншого конуса, вершина якого збігається з вершиною заданого. Знайдіть об'єм меншого конуса.";
			zadanieArray[1]="32 см<sup>3</sup>";
			zadanieArray[2]="16 см<sup>3</sup>";
			zadanieArray[3]="12 см<sup>3</sup>";
			zadanieArray[4]="8 см<sup>3</sup>";
			zadanieArray[5]="4 см<sup>3</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №20 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №20 ЗНО-2014 Математика. Пробный тест";
			zadanieArray[1]="а";
			zadanieArray[2]="б";
			zadanieArray[3]="в";
			zadanieArray[4]="г";
			zadanieArray[5]="д";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №21 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="";
			zadanieArray[1]="відрізок, симетричний-відрізку&nbsp;<i>d</i> відносно осі&nbsp;<i>x</i>";
			zadanieArray[2]="відрізок, симетричний-відрізку&nbsp;<i>d</i> відносно осі&nbsp;<i>y</i>";
			zadanieArray[3]="відрізок, симетричний відрізку&nbsp;<i>d</i> відносно точки&nbsp;<i>O</i>";
			zadanieArray[4]="відрізок, у який переходить відрізок&nbsp;<i>d</i> внаслідок повороту навколо точки&nbsp;<i>O</i> на кут&nbsp;90&deg; проти руху годинникової стрілки";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="numeric";
			viewArray[taskNumber-1]="multiselect_picture";
			answerArray[taskNumber-1]="bdae";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №22 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між заданим виразом (1-4) та виразом, що йому тотожно дорівнює (А-Д), якщо <i>a</i>&ne;0; <i>a</i>&ne;1; <i>a</i>&ne;-1.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]="abcd";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №23 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="3 усіх натуральних чисел, більших за&nbsp;9 і менших за&nbsp;20, навмання вибирають одне число. Установіть відповідність між подією (1-4) та ймовірністю її появи (А-Д)."; 
			zadanieArray[1]="вибране число буде простим";
			zadanieArray[2]="вибране число буде двоцифровим";
			zadanieArray[3]="вибране число буде дільником числа&nbsp;5";
			zadanieArray[4]="сума цифр вибраного числа буде ділитися на&nbsp;3";
			zadanieArray[5]="0";
			zadanieArray[6]="0,2";
			zadanieArray[7]="0,3";
			zadanieArray[8]="0,4";
			zadanieArray[9]="1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="deac";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №24 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено графік функції <i>y&nbsp;= f&nbsp;(x)</i>, визначеної на на відрізку&nbsp;[-2;&nbsp;6]. Установіть відповідність між твердженням (1–4) та рівнянням прямої (А-Д), для якої це твердження є правильним.";
			zadanieArray[1]="пряма не перетинає графік функції <i>y&nbsp;= f&nbsp;(x)</i>";
			zadanieArray[2]="пряма є дотичною, проведеною до графіка функції <i>y&nbsp;=&nbsp;f(x)</i> у точці з абсцисою <i>x</i>=5";
			zadanieArray[3]="пряма перетинає графік функції <i>y&nbsp;= f&nbsp;(x)</i> у точці з абсцисою <i>x</i>=3";
			zadanieArray[4]="пряма має з графіком функції <i>y&nbsp;= f&nbsp;(x)</i> не менше трьох спільних точок на відрізку&nbsp;[0;&nbsp;2]";
			zadanieArray[5]="<i>y&nbsp;=&nbsp;3&nbsp;+&nbsp;x</i>";
			zadanieArray[6]="<i>y&nbsp;=&nbsp;1</i>";
			zadanieArray[7]="<i>y&nbsp;=&nbsp;1&nbsp;-&nbsp;x</i>";
			zadanieArray[8]="<i>y&nbsp;=&nbsp;3</i>";
			zadanieArray[9]="<i>y&nbsp;=&nbsp;3&nbsp;-&nbsp;x</i>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection_picture";
			answerArray[taskNumber-1]="adec";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №25 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Довжина маршруту велосипедиста дорівнює 81&nbsp;км.  Першу частину цього маршруту він проїхав зі сталою швидкістю за 3&nbsp;години. Другу частину маршруту довжиною 36&nbsp;км велосипедист проїхав зі сталою швидкістю 18&nbsp;км/год.<p>1. Скільки часу (у год) витратив велосипедист на другу частину маршруту?</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=2;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.1"; 
			/*задание №26 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Довжина маршруту велосипедиста дорівнює 81&nbsp;км.  Першу частину цього маршруту він проїхав зі сталою швидкістю за 3&nbsp;години. Другу частину маршруту довжиною 36&nbsp;км велосипедист проїхав зі сталою швидкістю 18&nbsp;км/год.<p>2. Якою була середня швидкість велосипедиста (у&nbsp;км/год) протягом усього маршруту?</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 16.2;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.2"; 
			/*задание №27 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="Площа ромба дорівнює 10,8&nbsp;см<sup>2</sup>, а площа круга, вписаного в цей ромб - 2,25&nbsp;&pi;&nbsp;см<sup>2</sup>.<p>1. Визначте довжину радіуса круга, вписаного в ромб (у&nbsp;см).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 1.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.1"; 
			/*задание №28 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="Площа ромба дорівнює 10,8&nbsp;см<sup>2</sup>, а площа круга, вписаного в цей ромб - 2,25&nbsp;&pi;&nbsp;см<sup>2</sup>.<p>2. Обчисліть довжину сторони ромба (у&nbsp;см).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 3.6;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.2";
			/*задание №29 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №27 ЗНО-2014 Математика. Пробный тест"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 2.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="27";
			/*задание №30 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="Розв'яжіть нерівність <p style='text-align:center; font-style:italic;'>(18 + 2х)<sup>2</sup> (х<sup>2</sup> + 8х + 15) &le; 0.</p> У відповіді запишіть суму всіх цілих її розв'язків."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= -21;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="28";
			/*задание №31 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №29 ЗНО-2014 Математика. Пробный тест"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= -7;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]="29";
			/*задание №32 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №30 ЗНО-2014 Математика. Пробный тест"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 44;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
			taskNameArray[taskNumber-1]="30"; 
			/*задание №33 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку схематично зображено опуклий міст, що має форму дуги&nbsp;<i>АМВ</i> кола з центром у точці&nbsp;<i>O</i>. <i>MN</i> - серединний перпендикуляр до&nbsp;<i>АВ</i>, <i>MN</i>&nbsp;=&nbsp;3&nbsp;м. Визначте довжину радіуса <i>OВ</i>&nbsp;(у&nbsp;м), якщо довжина відрізка&nbsp;<i>АВ</i> дорівнює&nbsp;12&nbsp;м.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]= 7.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="31";
			/*задание №34 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="Областю визначення періодичної функції <i>у&nbsp;=f(x)</i> із періодом <i>Т</i>&nbsp;=&nbsp;9 є множина всіх дійсних чисел. На проміжку&nbsp;(-5;&nbsp;4] цю функцію задано формулою&nbsp;<i>f(x)&nbsp;=&nbsp;19&nbsp;-&nbsp;х<sup>3</sup></i>. Обчисліть значення&nbsp;<i>f(5)</i>.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 83;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="32";
			/*задание №35 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Основою піраміди&nbsp;<i>SABCD</i> є трапеція&nbsp;<i>ABCD</i>&nbsp;(<i>ВС</i>||<i>AD</i>). Бічна грань&nbsp;<i>SBC</i>, площа якої дорівнює 24,4&nbsp;см<sup>2</sup>, перпендикулярна до площини основи піраміди. Точка&nbsp;<i>М</i> - середина ребра&nbsp;<i>SB</i>. Площина&nbsp;(<i>MAD</i>) перетинає ребро&nbsp;<i>SC</i> в точці&nbsp;<i>N</i>. Визначте довжину відрізка&nbsp;<i>MN</i> (у см), якщо об'єм піраміди дорівнює 152&nbsp;см<sup>3</sup>, а площа її основи - 57&nbsp;см<sup>2</sup>.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 3.05;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="33";		
			/*задание №36 ЗНО-2014 Математика. Пробный тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="Знайдіть значення параметра a, при якому корінь рівняння<p align=center>lg(sin 5πx) = &radic;<span style='text-decoration:overline;'>&nbsp;16 + a – x&nbsp;</span></p>належить проміжку (1,5 ; 2).";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= -2.625;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="34";		
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}/*конец ЗНО-2014 Математика. Пробный тест*/
	

/*************************************************************/	

/*ЗНО-2014 Математика. Основной тест*/
	if(testName==znoMat2014Main)
	{
		testLength=36;
		timeCounter=150*60;
		testTime=timeCounter;
		testDirectory='\/test\/mat\/img\/test2014main\/';
		testTitle = znoName+"2014"+znoMatName;
		testDetails=mainName;
		answerLanguage="rus";
		gradeArray=new Array("100.0","102.0","106.5","113.0","118.5","124.0","128.0","132.5","136.0","140.0","144.5","149.0","151.0","152.5","154.0","156.0","157.0","158.5","159.5","161.0","162.0","163.0","164.5","165.5","166.5","167.5","168.5","170.0","171.0","172.0","173.0","174.0","175.0","176.0","177.0","178.0","179.0","180.0","181.0","182.0","183.0","184.0","185.0","186.5","187.5","188.5","189.5","191.0","192.0","193.5","195.0","196.0","197.5","198.5","199.5","200.0","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var taskNumber=1;
		taskNameArray[taskNumber-1]=""; 
		/*задание №1 ЗНО-2014 Математика. Основной тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Якщо <i>m</i> = <i>n</i> - 1, то 7 - <i>m</i> = ";
			zadanieArray[1]="<i>n</i>-8";
			zadanieArray[2]="6-<i>n</i>";
			zadanieArray[3]="8-<i>n</i>";
			zadanieArray[4]="<i>n</i>-6";
			zadanieArray[5]="6+<i>n</i>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
		/*задание №2 ЗНО-2014 Математика. Основной тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №2 ЗНО-2014 Математика. Основной тест";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №3 ЗНО-2014 Математика. Основной тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="Вектор <i><span style='text-decoration:overline;'>OA</span></i> лежить на осі <i>z</i> прямокутної декартової системи координат у просторі (див. рисунок), і його початок збігається з початком координат. Визначте координати вектора <i><span style='text-decoration:overline;'>OA</span></i>, якщо його довжина дорівнює 3.";
			zadanieArray[1]="(1;1;1)";
			zadanieArray[2]="(0;3;0)";
			zadanieArray[3]="(0;0;3)";
			zadanieArray[4]="(3;0;0)";
			zadanieArray[5]="(3;3;3)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №4 ЗНО-2014 Математика. Основной тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="задание №4 ЗНО-2014 Математика. Основной тест";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №5 ЗНО-2014 Математика. Основной тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="Які з наведених тверджень є правильними?<p>I. Сума двох будь-яких вертикальних кутів дорівнює 180&deg;.</p><p>II. Сума двох будь-яких суміжних кутів дорівнює 180&deg;.</i></p><p>III. Сума будь-якого гострого кута та будь-якого тупого кута дорівнює 180&deg;.</p>";
			zadanieArray[1]="лише І";
			zadanieArray[2]="лише II";
			zadanieArray[3]="лише І і III";
			zadanieArray[4]="лише II і III";
			zadanieArray[5]="I, II і III";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №6 ЗНО-2014 Математика. Основной тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="Студент на першому курсі повинен вибрати одну з трьох іноземних мов, яку вивчатиме, та одну з п'яти спортивних секцій, що відвідуватиме. Скільки всього існує варіантів вибору студентом іноземної мови та спортивної секції?";
			zadanieArray[1]="5";
			zadanieArray[2]="8";
			zadanieArray[3]="10";
			zadanieArray[4]="15";
			zadanieArray[5]="25";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №7 ЗНО-2014 Математика. Основной тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №7 ЗНО-2014 Математика. Основной тест";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
			/*задание №8 ЗНО-2014 Математика. Основной тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="Арифметичну прогресію  (<i>a<sub>n</sub></i>)  задано формулою <i>n</i>-го члена  <i>a<sub>n</sub></i>&nbsp;=&nbsp;4&nbsp;-&nbsp;8<i>n</i>. <br/>Знайдіть різницю цієї прогресії.";
			zadanieArray[1]="8";
			zadanieArray[2]="4";
			zadanieArray[3]="-2";
			zadanieArray[4]="-4";
			zadanieArray[5]="-8";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №9 ЗНО-2014 Математика. Основной тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			var zadanieArray=new Array();
			zadanieArray[0]="Точка <i>С</i> лежить на осі <i>x</i> прямокутної системи координат і знаходиться на відстані 5 від точки <i>A</i>&nbsp;(-2;&nbsp;4). Відрізок <i>AC</i> перетинає вісь <i>y</i>. Знайдіть координати точки <i>C</i>.";
			zadanieArray[1]="(1;0)";
			zadanieArray[2]="(0;1)";
			zadanieArray[3]="(-5;0)";
			zadanieArray[4]="(0;0)";
			zadanieArray[5]="(3;4)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №10 ЗНО-2014 Математика. Основной тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено графік функції <i>у =f(x)</i>, визначеної на проміжку [-6; 6]. <br/>Яку властивість має функція <i>у =f(x)</i>?";
			zadanieArray[1]="функція є періодичною";
			zadanieArray[2]="функція зростає на проміжку [-6; 6]";
			zadanieArray[3]="функція спадає на проміжку [-6; 6]";
			zadanieArray[4]="функція є парною";
			zadanieArray[5]="функція є непарною";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №11 ЗНО-2014 Математика. Основной тест*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Якому з наведених проміжків належить корінь рівняння <p style='text-align:center;'><i><sup>3</sup>&radic;<span style='text-decoration:overline;'>2x</span>= -3</i>?</p>";
			zadanieArray[1]="(-30; -20)";
			zadanieArray[2]="(-20; -10)";
			zadanieArray[3]="(-10; 0)";
			zadanieArray[4]="(0; 10)";
			zadanieArray[5]="(10; 20)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №12 ЗНО-2014 Математика. Основной тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №12 ЗНО-2014 Математика. Основной тест";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №13 ЗНО-2014 Математика. Основной тест*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №13 ЗНО-2014 Математика. Основной тест";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №14 ЗНО-2014 Математика. Основной тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Відомо, що ctg &alpha; < 0, cos &alpha; > 0. <br/>Якого значення може набувати sin &alpha;?";
			zadanieArray[1]="-1";
			zadanieArray[2]="-1/2";
			zadanieArray[3]="0";
			zadanieArray[4]="1/2";
			zadanieArray[5]="1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
			/*задание №15 ЗНО-2014 Математика. Основной тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №15 ЗНО-2014 Математика. Основной тест";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №16 ЗНО-2014 Математика. Основной тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено розгортку піраміди, що складається з квадрата, сторона якого дорівнює  10  см, і чотирьох правильних трикутників. <br/>Визначте площу бічної поверхні цієї піраміди (у см).";
			zadanieArray[1]="100&radic;<span style='text-decoration:overline;'>3</span>";
			zadanieArray[2]="100";
			zadanieArray[3]="400&radic;<span style='text-decoration:overline;'>3</span>";
			zadanieArray[4]="100(1+&radic;<span style='text-decoration:overline;'>3</span>)";
			zadanieArray[5]="200";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №17 ЗНО-2014 Математика. Основной тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Розв'яжіть нерівність<p style='text-align:center;'>(x+4)<sup>2</sup>&le;16.</p>";
			zadanieArray[1]="(-&infin;; 8]";
			zadanieArray[2]="(-&infin;; 0]";
			zadanieArray[3]="(-&infin;; 4]";
			zadanieArray[4]="[-8; 8]";
			zadanieArray[5]="[-8; 0]";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]=""; 
			/*задание №18 ЗНО-2014 Математика. Основной тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Відрізок <i>АВ</i> перетинає площину <i>&alpha;</i> в точці <i>O</i>. Проекції відрізків <i>АO</i> і <i>BO</i> на цю площину дорівнюють 5 см і 20 см відповідно. Знайдіть довжину відрізка <i>АВ</i>, якщо <i>АO</i> = 8 см.";
			zadanieArray[1]="10 см";
			zadanieArray[2]="22 см";
			zadanieArray[3]="32 см";
			zadanieArray[4]="40 см";
			zadanieArray[5]="52 см";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №19 ЗНО-2014 Математика. Основной тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="На площі міста встановили однакові бетонні ємності для квітів, виготовлені у формі прямокутних паралелепіпедів, виміри яких дорівнюють 40&nbsp;см, 40&nbsp;см і 50&nbsp;см (див. рисунок). Товщина кожної з чотирьох бічних стінок становить 5&nbsp;см, а товщина днища - 10&nbsp;см. Який об'єм бетону (у м<sup>3</sup>) було використано для виготовлення 10 таких ємностей? Утратою бетону під час виготовлення знехтуйте.";
			zadanieArray[1]="0,32 м<sup>3</sup>";
			zadanieArray[2]="0,33 м<sup>3</sup>";
			zadanieArray[3]="0,36 м<sup>3</sup>";
			zadanieArray[4]="0,44 м<sup>3</sup>";
			zadanieArray[5]="0,8 м<sup>3</sup>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №20 ЗНО-2014 Математика. Основной тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть рівняння дотичної, проведеної до графіка функції  <i>у&nbsp;=&nbsp;f(х)</i> у точці з абсцисою <i>х<sub>0</sub>&nbsp;=&nbsp;1</i>,  якщо <i>f(х<sub>0</sub>)=5</i>, <i>f'(х<sub>0</sub>)=2</i>";
			zadanieArray[1]="y = 1 + 2(x-5)";
			zadanieArray[2]="y = 5 + 2(x+1)";
			zadanieArray[3]="y = 2 + 5(x-1)";
			zadanieArray[4]="y = 2 + 5(x+1)";
			zadanieArray[5]="y = 5 + 2(x-1)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №21 ЗНО-2014 Математика. Основной тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між заданим виразом (1-4) та виразом, що йому тотожно дорівнює (А-Д), якщо <i>m</i>&gt;2,  <i>m</i>&nbsp;-&nbsp;натуральне число";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="numeric";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]="cbde";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №22 ЗНО-2014 Математика. Основной тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між функцією (1-4) та кількістю спільних точок (А-Д) графіка цієї функції з графіком функції <i>у &nbsp;=&nbsp;0,2x</i>";
			zadanieArray[1]="y=x+5";
			zadanieArray[2]="y=5<sup>x</sup>";
			zadanieArray[3]="y=&radic;<span style='text-decoration:overline;'>x</span>";
			zadanieArray[4]="y=sin(x)";
			zadanieArray[5]="жодної";
			zadanieArray[6]="лише одна";
			zadanieArray[7]="лише дві";
			zadanieArray[8]="лише три";
			zadanieArray[9]="більше трьох";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="bacd";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №23 ЗНО-2014 Математика. Основной тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено квадрат <i>ABCD</i> зі стороною 1&nbsp;см та прямокутний трикутник <i>CDF</i>, гіпотенуза якого <i>CF</i> дорівнює &radic;<span style='text-decoration:overline;'>5</span>&nbsp;см. Фігури лежать в одній площині. Установіть відповідність між початком речення (1–4) та його закінченням (А–Д) так, щоб утворилося правильне твердження."; 
			zadanieArray[1]="Довжина катета <i>FD</i> трикутника <i>CDF</i> дорівнює";
			zadanieArray[2]="Довжина радіуса кола, описаного навколо квадрата <i>ABCD</i>, дорівнює";
			zadanieArray[3]="Відстань від точки <i>F</i> до прямої <i>BC</i> дорівнює";
			zadanieArray[4]="Відстань від точки <i>F</i> до прямої <i>BD</i> дорівнює";
			zadanieArray[5]="1&nbsp;см.";
			zadanieArray[6]="1&nbsp;/&nbsp;&radic;<span style='text-decoration:overline;'>2</span>&nbsp;см.";
			zadanieArray[7]="&radic;<span style='text-decoration:overline;'>2</span>&nbsp;см.";
			zadanieArray[8]="2&nbsp;см.";
			zadanieArray[9]="&radic;<span style='text-decoration:overline;'>5</span>&nbsp;см.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection_picture";
			answerArray[taskNumber-1]="dbac";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]=""; 
			/*задание №24 ЗНО-2014 Математика. Основной тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="На рисунку зображено полігон частот певного ряду даних, на якому по осі абсцис відмічені елементи цього ряду, а по осі ординат – їхні частоти. Установіть відповідність між характеристикою (1–4) цього ряду даних та її числовим значенням (А–Д).";
			zadanieArray[1]="кількість елементів";
			zadanieArray[2]="розмах";
			zadanieArray[3]="мода";
			zadanieArray[4]="медіана";
			zadanieArray[5]="12";
			zadanieArray[6]="18";
			zadanieArray[7]="21";
			zadanieArray[8]="30";
			zadanieArray[9]="36";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection_picture";
			answerArray[taskNumber-1]="bdac";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]=""; 
			/*задание №25 ЗНО-2014 Математика. Основной тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Початкова вартість сукні становила 144&nbsp;грн. Унаслідок уцінення вартість цієї сукні було зменшено на 60%.<p>1. Обчисліть вартість сукні після уцінення (у грн).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=57.6;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.1"; 
			/*задание №26 ЗНО-2014 Математика. Основной тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Початкова вартість сукні становила 144&nbsp;грн. Унаслідок уцінення вартість цієї сукні було зменшено на 60%.<p>2. Скільки відсотків становить початкова вартість сукні від її вартості після уцінення?</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 250;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="25.2"; 
			/*задание №27 ЗНО-2014 Математика. Основной тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="На стороні <i>AD</i> паралелограма <i>АВСD</i> як на діаметрі побудовано півколо так, що воно дотикається до сторони <i>ВС</i> в точці <i>M</i>. Довжина дуги <i>MD</i> дорівнює 6,5&pi;&nbsp;см.<p>1. Обчисліть (у см) довжину радіуса цього півкола.</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 13;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.1"; 
			/*задание №28 ЗНО-2014 Математика. Основной тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="На стороні <i>AD</i> паралелограма <i>АВСD</i> як на діаметрі побудовано півколо так, що воно дотикається до сторони <i>ВС</i> в точці <i>M</i>. Довжина дуги <i>MD</i> дорівнює 6,5&pi;&nbsp;см.<p>2. Обчисліть площу паралелограма <i>АВСD</i> (у см<sup>2</sup>).</p>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 338;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="26.2";
			/*задание №29 ЗНО-2014 Математика. Основной тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №27 ЗНО-2014 Математика. Основной тест"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 2.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="27";
			/*задание №30 ЗНО-2014 Математика. Основной тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 44.8;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="28";
			/*задание №31 ЗНО-2014 Математика. Основной тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="Розв’яжіть рівняння <p>log<sub>0,4</sub>(5x<sup>2</sup> – 8) = log<sub>0,4</sub>(–3x).</p> Якщо рівняння має єдиний корінь, запишіть його у відповіді. Якщо рівняння має кілька коренів, запишіть у відповіді їхню суму."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= -1.6;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]="29";
			/*задание №32 ЗНО-2014 Математика. Основной тест*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №30 ЗНО-2014 Математика. Основной тест"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 19;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
			taskNameArray[taskNumber-1]="30"; 
			/*задание №33 ЗНО-2014 Математика. Основной тест*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="Діагональ рівнобічної трапеції є бісектрисою її гострого кута і ділить середню лінію трапеції на відрізки довжиною 13&nbsp;см і 23&nbsp;см. Обчисліть (у&nbsp;см<sup>2</sup>) площу трапеції.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 864;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		    taskNameArray[taskNumber-1]="31";
			/*задание №34 ЗНО-2014 Математика. Основной тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №32 ЗНО-2014 Математика. Основной тест"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= 48;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="32";
			/*задание №35 ЗНО-2014 Математика. Основной тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Через точки <i>А</i> і <i>B</i>, що лежать на колах верхньої та нижньої основ циліндра і не належать одній твірній, проведено площину паралельно осі циліндра. Відстань від центра нижньої основи до цієї площини дорівнює 2&nbsp;см, а площа утвореного перерізу – 60&radic;<span style='text-decoration:overline;'>2</span>&nbsp;см<sup>2</sup>. Визначте довжину відрізка <i>АB</i> (у&nbsp;см), якщо площа бічної поверхні циліндра дорівнює 20&radic;<span style='text-decoration:overline;'>30</span>&pi;&nbsp;см<sup>2</sup>.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]= 18;
			taskTypeArray[taskNumber-1]="free";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="33";		
			/*задание №36 ЗНО-2014 Математика. Основной тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="задание №34 ЗНО-2014 Математика. Основной тест"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="picture";
			answerArray[taskNumber-1]= -8.5;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
		        taskNameArray[taskNumber-1]="34";		
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}/*конец ЗНО-2014 Математика. Основной тест*/
	startInitialization();				
	
}
