function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	/*Массив названий тестов*/
	var taskNameArray=new Array();
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/
/*************************************************************/
//Тесты по немецкому языку	
/*************************************************************/	
/*ЗНО-2014 немецкий язык. Основной тест. I сессия*/
	if(testName==znoFra2014Main)
	{
		testLength=43;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/fra\/img\/test2014main\/';
		testTitle = znoName+"2014"+znoFraName;
		testDetails=mainName;
		answerLanguage="eng";
		gradeArray=new Array("100.0","100.5","101.0","102.0","103.0","105.5","107.0","111.5","116.5","119.0","124.0","126.5","130.0","132.0","135.5","138.0","140.0","142.0","143.0","144.5","145.5","146.5","147.5","148.5","150.0","150.5","151.5","152.5","154.0","155.0","156.0","157.0","158.0","159.0","160.0","161.5","163.0","164.0","165.0","166.5","167.5","168.5","170.5","171.5","174.0","175.0","178.0","180.0","183.0","186.0","189.0","191.5","193.5","196.5","199.0","200.0","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var saintValentinus="\t63 Saint-Valentins plus tard\n\n\tIl n’a jamais été question que l’amour s’arrête pour Fernande et Roger Raymond (17)___________ en octobre. Et jamais le couple n’échangerait (18)___________. Ils se sont connus à l’Hôtel-Dieu. Elle était secrétaire, il était comptable. C’était en 1946 ou 1947. «Dans ce temps-là, on se tenait la main. Et c’est tout!» se souvient Mme Raymond. \n\tQuelques mois (19)___________ dans laquelle il promettait d’être fidèle, Fernande lui disait oui devant l’autel. «Lorsque je suis tombée amoureuse, ç’a été un vrai choc. Moi qui étais si gênée, (20)___________. Je ne voyais personne. Juste lui.» \n\tQuatorze mois plus tard naissaient leurs premiers bébés. Un couple de jumeaux. Les premiers de huit enfants qui sont nés de leur union. Au fil des ans, le couple a vécu à sept adresses. «On a déménagé (21)___________. Ensuite lorsqu’elle a rapetissé.» \n\tLe secret de la longévité de leur relation, Fernande le partage d’emblée: (22)___________ par leur foi.";
		var lesen2="\tGut im Geschäft\n\n\tSie sind jung, erfolgreich und voller Ideen. Ihre Geschäfte laufen prima, doch Verträge dürfen sie nicht abschließen, Geld verdienen auch nicht. Das Einzige, was die jungen Unternehmer als Lohn erhalten, ist eine Menge Erfahrung und eine Vorstellung von ihrem zukünftigen Berufsleben. \n\n\tSchülerfirmen gibt es an vielen Schulen. Meist verkaufen ihre Mitarbeiter belegte Brötchen, Obst, Getränke und Süßigkeiten in den Pausen. Doch die Schüler haben oft noch ganz andere Ideen, für die es sich lohnt, ein eigenes Unternehmen zu gründen. 80 Schülerinnen aus dem Bundesgebiet stellen nun in Berlin ihre Geschäftsideen vor. Besucher können Waren kaufen und bestellen – wie bei einer echten Fachmesse. \n\n\tDoch es geht nicht so sehr ums Fachgeschäftliche, sondern ums Soziale. Die Schüler lernen kreativ zu sein, zusammen zu arbeiten, es geht also um Disziplin und Zuverlässigkeit. Und so müssen auch die sieben Mädchen von der Schule am Zwickauer Damm in Rudow lernen Rechnungen zu schreiben, Bilanzen zu führen und den Arbeitstag zu organisieren. Cosmo Girls nennen sich die Schülerinnen, die Haar- und Nagelpflege in ihrer Schule anbieten. Jeden Freitag öffnen die Mädchen von 9 bis 12.30 Uhr ihren Salon im Schulhaus. Sie waschen Mitschülern die Haare, massieren Hände und schminken Mädchen. Die Dienstleistungen kosten höchstens 1,50 Euro, Erwachsene zahlen das Doppelte. Alles wird für Shampoo, Spray und Schminke ausgegeben. Da bleibt kein Geld übrig. \n\n\tVor der Wirtschafts- und Finanzkrise haben junge Unternehmer keine Angst. Schülerfirmen funktionieren anders als gewöhnliche Firmen. Sie brauchen kein Startkapital, oft übernehmen Lehrer und Betreuer die finanzielle Verantwortung. Mitschüler, Lehrer und Eltern sind treue Kunden. Oft ist so eine Schülerfirma ein Plus-Minus-Null-Geschäft mit nicht so hohen Ausgaben. Doch die Pflichten werden verteilt wie in der realen Arbeitswelt. \n\n\tMit 15 Jahren ist Benedikt Franke Geschäftsführer der Firma Elegancia, die Bio-Kaffee aus Nicaragua verkauft. Seit April 2009 kümmern sich zwölf Schüler der 9. und 10. Klassen einer privaten Gesamtschule in Berlin um den Verkauf des Kaffees in umliegenden Läden, auf Messen und Tagungen. Der ist zwar teurer als gewöhnlicher Kaffee aus dem Supermarkt, „doch die Bauern, die Kaffeebohnen anbauen, bekommen dafür einen gerechten Preis“, sagt Franke.";
		var anzeigeA="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Gartenpfleger/in gesucht</p><p style='text-align:center;  color:black;'>Ich suche einen Gartenpfleger für ca. 2–3 Std./Woche.</p><p style='text-align:center;  color:black;'>Ich freue mich auf Ihren Anruf. Telefon: 457 66 90</p></div>";
		var anzeigeB="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Hausmeisterfirma</p><p style='text-align:center;  color:black;'>sucht eine/n Arbeiter/in</p><p style='text-align:center;  color:black;'>für die Grünanlagenpflege mit Festanstellung.</p><p style='text-align:center;  color:black;'>Telefon: 089/793 40 87</p></div>";
		var anzeigeC="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:black;'>Zuverlässige</p><p style='text-align:center;  color:red;'>Bürokraft</p><p style='text-align:center;  color:black;'>ab sofort gesucht.</p><p style='text-align:center;  color:black;'>Teilzeit, 20 Std./Woche Tel. 089/14 38 333</p></div>";
		var anzeigeD="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Fleißige(r) Hausmeister(in)</p><p style='text-align:center;  color:black;'>mit handwerklichem Geschick gesucht.</p><p style='text-align:center;  color:black;'>Festanstellung, ca. 35 Std./Woche</p><p style='text-align:center;  color:black;'>Ihre Bewerbung senden Sie bitte an:</p><p style='text-align:center;  color:black;'>s.schmidt@hv-schmid.de</p></div>";
		var anzeigeE="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Bürokauffrau/-mann</p><p style='text-align:center;  color:black;'>Wir suchen eine(n) Auszubildende(n).</p><p style='text-align:center;  color:black;'>Voraussetzungen: Realschulabschluss, ordentliches Erscheinungsbild und korrektes Auftreten.</p><p style='text-align:center;  color:black;'>Ihre schriftliche Bewerbung richten Sie bitte an K&M Gebäudereinigung GmbH, Breite Str. 7, 01917 Kamenz</p></div>";
		var anzeigeF="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:black;'>Für unser junges Team suchen wir</p><p style='text-align:center;  color:red;'>Bürohelfer in Vollzeit.</p><p style='text-align:center;  color:black;'>Flexibilität, sowie gutes Zahlenverständnis setzen wir voraus.</p><p style='text-align:center;  color:black;'>Schriftliche Bewerbung an:</p><p style='text-align:center;  color:red;'>VSR Verlag Service GmbH</p><p style='text-align:center;  color:black;'>Alexandra Scholz, Kistlerhofstr.170, 81379 München</p></div>";
		var anzeigeG="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:black;'>Wir suchen</p><p style='text-align:center;  color:red;'>1 Auszubildende(n) zum KFZ-Mechatroniker (PKW)</p><p style='text-align:center;  color:black;'>Voraussetzung: guter Hauptschulabschluss, oder Realschulabschluss</p><p style='text-align:center;  color:black;'>Vorhandene Praktikumsnachweise sind von Vorteil.</p><p style='text-align:center;  color:red;'>www.waldforst.net</p></div>";
		var anzeigeH="<div style='border:1px solid black; font-size:14px;'><p style='text-align:center;  color:red;'>Hausmeisterfirma</p><p style='text-align:center;  color:black;'>sucht einen Aushilfsfahrer für 2–3 Tage in der Woche, vorzugsweise mit eigenem PKW.</p><p style='text-align:center;  color:black;'>Telefon: 089/793 40 87</p></div>";
		var tornados="\tAuf der Suche nach Tornados\n\n– Mein Name ist Heiko Wichmann. Ich liebe extremes Wetter und interessiere (23)__________ für seltene und gefährliche Wetterphänomene.\n\nIch bekomme professionelle Wetterkarten mit verschiedenen Daten, (24)__________ ich analysieren muss. Und dann weiß ich, wo ich diesmal (25)___________ werde. Besonders toll finde ich (26)__________ Wetter, zum Beispiel Gewitter. Ich filme dann, mache Fotos und gebe mit (27)__________ Handy wichtige Daten an den deutschen Wetterdienst weiter.\n\nIch habe auch schon zwei Tornados gesehen. Einer war 2007 nördlich (28)__________ Berlin, der andere 2009 in Brandenburg. Dieses Wetterphänomen hat (29)__________ in Deutschland schon immer gegeben.\n\nIch lese alte Zeitungen und Kirchenchroniken und versuche, Informationen über Tornados (30)__________. Ich habe gerade sechs historische Fotos vom 1. August 1877 gefunden. An beschädigten Gebäuden sieht man, (31)__________ dort ein Tornado war. Er muss sehr stark gewesen sein. Solche historischen Wetterdaten (32)__________ untersucht und publiziert.";
		var buchmessen="\tDie Geschichte der Buchmessen\n\nDie größte Buchmesse ist die in Frankfurt am Main. So wie sie heute noch (33)__________, wurde sie im Jahr 1949 vom „Börsenverein des Deutschen Buchhandels“ (34)__________. Es (35)__________ sie jedes Jahr im Oktober. Aber diese Messe hat eine über 500-jährige Geschichte. Im Jahr 1455 (36)__________ Johannes Gutenberg in Mainz (nicht weit weg von Frankfurt) den Buchdruck. Einige Buchdrucker (37)__________ in der Folge die Frankfurter Messe zu einem Handelszentrum für gedruckte Bücher.";
		var Fahrrad="\tFahrrad fahren\n\nMehr Sport treiben, Geld sparen, die Umwelt schonen – das möchte fast jeder. Kein Wunder, dass immer mehr Deutsche für ihre täglichen Wege zur Arbeit oder zum Einkaufen vom Auto aufs Fahrrad (38)__________ . Etwa 80 Prozent aller (39)__________ haben mindestens ein Fahrrad. Das hat zum Teil praktische (40)__________: Wer Rad fährt, gibt kein Geld für Benzin aus, muss nicht nach einem Parkplatz suchen oder im (41)__________ stehen. Und gesund ist Radfahren auch. Darüber hinaus ist Fahrradfahren cool: Wer Rad fährt, präsentiert sich als (42)__________.";
		var taskNumber=1;
		/*задание №1 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'><i>Musée d’art contemporain du Val-de-Marne, place de la Libération, Vitry-sur-Seine (94)</i>.La nouvelle exposition du Mac/Val, baptisé «Homo economicus», soulève la question de la production, de l’échange. Elle réunit des univers artistiques et économiques et présente des installations étonnantes. <br><b>De 12 à 19 h.</b> <i>Tarifs: 4 €, 2 € (réduit)</i> <br><i>Renseignements: 01 43 91 64 20</i></p><p>À quoi est consacrée l’exposition citée dans l’annonce?</p>";
			zadanieArray[1]="aux problèmes historiques";
			zadanieArray[2]="aux activités économiques";
			zadanieArray[3]="à l’équipement mécanique";
			zadanieArray[4]="aux normes linguistiques";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="1 (COMPRÉHENSION ÉCRITE)";	
		/*задание №2 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>De son côté, en chef d’orchestre de l’ensemble de dispositif, l’agent de trafic s’assure avant tout de la logistique du déchargement des soutes avec des valises, sacs, malles, etc. Les équipes concernées reçoivent ainsi «la position exacte de chaque élément, afin de traiter en priorité les animaux, les objets fragiles ou sensibles», précise Ghislaine Biadelli, directrice technique de l’aéroport Paris-Charles-de-Gaulle.</p><p>De quoi est responsable l’agent de trafic?</p>";
			zadanieArray[1]="du traitement des bagages arrivés";
			zadanieArray[2]="de la qualité de travail des équipes";
			zadanieArray[3]="de la position de l’avion sur le sol";
			zadanieArray[4]="du respect des normes sanitaires";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="2 (COMPRÉHENSION ÉCRITE)";
		/*задание №3 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>DE PARIS EN ITALIE À MOINS DE 85 EUROS:<br>Le coût de quatre-vingt-cinq baguettes, mais on ne vit pas seulement de pain! Vols directs de Paris CDG vers la Sardaigne (Cagliari et Olbia), La Sicile (Catagne et Palerme), Naples et Milan.<br> Meridiane <i>eurofly</i></p><p>À quoi sert ce document?</p>";
			zadanieArray[1]="à parler aux lecteurs du pain français";
			zadanieArray[2]="à proposer des voyages en avion";
			zadanieArray[3]="à admirer la beauté de l’Italie";
			zadanieArray[4]="à apprendre les noms des villes";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="3 (COMPRÉHENSION ÉCRITE)";
		/*задание №4 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>Restaurant 75001 Paris<br>intérieur 30 chaises, terrasse 16 chaises<br><i>Nous cherchons une serveuse dynamique, souriante, motivée avec le sens de l’initiative afin de compléter notre équipe au sein d’un restaurant traditionnel au coeur de Paris. Pratique de l’anglais demandé et d’autres langues étrangères comprises seraient un plus: italien, espagnol ou russe.</i><br>Envoyer émail ou prendre contact par téléphone entre 14 h 30 et 15 h 30</p><p>Pourquoi est-ce qu’on a publié cette annonce?</p>";
			zadanieArray[1]="pour louer un local commercial au centre-ville";
			zadanieArray[2]="pour vendre des meubles d’occasion";
			zadanieArray[3]="pour proposer un emploi dans le secteur de restauration";
			zadanieArray[4]="pour trouver un professeur des langues étrangères";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="4 (COMPRÉHENSION ÉCRITE)";			
		/*задание №5 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>Nouveau message</p><table><tr><td style='text-align:right; width:20%;'>À:</td><td style='text-align:left;'>458tc@ bahoo.fr</td></tr><tr><td style='text-align:right; width:20%;'>Cc:</td><td style='text-align:left;'>89xt@voil.fr, jean@panadoo.fr, odile@botmail.fr</td></tr><tr><td style='text-align:right; width:20%;'>Objet:</td><td style='text-align:left;'>proposition de services</td></tr></table><p style='text-align:justify;  color:black;'>Bonjour!<br>Je suis à la recherche de quelques heures de ménage et de repassage. J’ai plusieurs années d’expérience. Vous pouvez me contacter par émail. Dans l’attente d’une réponse favorable de votre part, je vous remercie d’avance. Pas sérieux à s’interdire.<br>&nbsp;Cordialement<br>&nbsp;&nbsp;&nbsp;madame Lefèvre</p><p>Que peut faire madame Lefèvre?</p>";
			zadanieArray[1]="livrer des fers à repasser commandés sur catalogue";
			zadanieArray[2]="donner des consultations d’utilisation du courrier électronique";
			zadanieArray[3]="aider en ce qui concerne les travaux domestiques";
			zadanieArray[4]="présenter son expérience de l’entretien économe de la maison";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="5 (COMPRÉHENSION ÉCRITE)";	
		/*задание №6 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'><b>François Azouvi «Descartes et la France»</b><br>Cet essai du philosophe François Azouvi paru en 2002 chez Fayard dans la belle collection «L’esprit de la cité», reparaît aujourd’hui en livre de poche. L’actualité du livre est très réelle puisque c’est la France que l’auteur de l’essai interroge dans son rapport avec le philosophe qui a su, le mieux, l’incarner.</p><p>À quoi est consacré l’essai de François Azouvi?</p>";
			zadanieArray[1]="à l’étude de la vie artistique en France";
			zadanieArray[2]="à l’étude de la mentalité française";
			zadanieArray[3]="à l’étude du développement historique du pays";
			zadanieArray[4]="à l’étude de la méthode de raisonnement";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="6 (COMPRÉHENSION ÉCRITE)";	
		/*задание №7 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="<table><tr><td style='text-align:justify;color:black; border: 1px solid black; width:50%; padding:5px;'>S’échanger des émails, envoyer des fichiers de musique à un copain, jouer en réseau sur Internet... Toutes ces actions se font facilement grâce au wi-fi. Bonne nouvelle: à partir de cet été, on pourra utiliser ce réseau sans fil dans certains trains (à bord du Thalys et du TGV Est) ou certains avions</td><td style='text-align:justify; color:black; border: 1px solid black; padding:5px;'>(des compagnies comme American Airlines, Lufthansa). Pratique pour les vacances! Enfin, dans le métro et les bus parisiens, le wi-fi est accessible depuis cet été dans les couloirs et dans certaines stations (Place d’Italie, Chaussée d’Antin et Pont de Sèvres).</td></tr></table><p>Où le wi-fi est-il devenu accessible d’après ce texte?</p>";
			zadanieArray[1]="dans tous les transports pendant les vacances";
			zadanieArray[2]="partout dans le métro et les bus parisiens";
			zadanieArray[3]="sur quelques lignes aériennes françaises";
			zadanieArray[4]="dans certains transports urbains et interurbains";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="7 (COMPRÉHENSION ÉCRITE)";	
		/*задание №8 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'><b>&nbsp;&nbsp;PARIS&nbsp;14e&nbsp;&nbsp;&nbsp;670€</b><br><b>&nbsp;&nbsp;&nbsp;&nbsp;4.395 Fr&nbsp;&nbsp;&nbsp;PARIS 14e</b><br>à 50 mètres du métro <b>PERNETY</b>, un studio meublé refait à neuf; l’immeuble est sécurisé avec la vidéosurveillance; les prix nets <b>TOUT</b> compris (frais, charges, chauffage, électricité...); la somme qu’il faut verser pour servir de garantie: 1 mois de loyer.</p><p>Qu’est-ce qu’on propose dans l’annonce?</p>";
			zadanieArray[1]="l’installation de la vidéosurveillance";
			zadanieArray[2]="la location d’un appartement à 1 pièce";
			zadanieArray[3]="la modernisation du système de chauffage";
			zadanieArray[4]="la restauration des meubles neufs";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="8 (COMPRÉHENSION ÉCRITE)";	
		/*задание №9 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>Professionnel de la santé, le pharmacien peut exercer dans l’industrie pharmaceutique, un hôpital, un laboratoire d’analyses ou une pharmacie, comme moi...<br>Mon rôle: délivrer des médicaments prescrits par le médecin, commander et réceptionner les produits, pratiquer des petits soins... Le conseil constitue aussi une part importante de mon quotidien. Les qualités du pharmacien: le sens de l’accueil, une grande capacité d’écoute, et de la mémoire, car on doit retenir les effets secondaires de tous les médicaments.</p><p>En quoi consiste la fonction principale de ce pharmacien?</p>";
			zadanieArray[1]="à établir un diagnostic selon les symptômes décrits";
			zadanieArray[2]="à mémoriser les composants de tous les médicaments";
			zadanieArray[3]="à préparer les substances prescrites par le médecin";
			zadanieArray[4]="à remettre des remèdes indiqués sur ordonnance";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="9 (COMPRÉHENSION ÉCRITE)";	
		/*задание №10 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>C’est la première fois que 170 tableaux de Claude Monet sont réunis dans un même endroit. Ils proviennent de 70 musées du monde. Depuis quatre mois, près de 920&nbsp;000&nbsp;personnes sont venues admirer les oeuvres de l’un des peintres préférés des Français. Un record de visites! Lorsque l’on regarde ses oeuvres de plus près, on observe une multitude de détails. Claude Monet peignait par petites touches de couleur et ça donnait un effet original.</p><p>Par quoi s’explique le succès de l’exposition?</p>";
			zadanieArray[1]="par le style particulier du peintre";
			zadanieArray[2]="par la durée prolongée de l’exposition";
			zadanieArray[3]="par le lieu préféré de tous les visiteurs";
			zadanieArray[4]="par le programme original de l’expo";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="10 (COMPRÉHENSION ÉCRITE)";	
		/*задание №11 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>Un accident sans gravité a provoqué l’interruption du trafic sur le Grand Boulevard.<br>Il était 11 h ce matin lorsque le haut de camionnette a heurté le pont. À l’issue de ce choc, quatre véhicules, qui suivaient la camionnette, se sont heurtés. Quatre personnes ont été légèrement blessées, dont deux qui ont été transférées dans un centre hospitalier proche. Cet accident a provoqué l’interruption totale du trafic sur la voie centrale.</p><p>Quel titre convient le mieux à ce texte?</p>";
			zadanieArray[1]="Le trafic interrompu à cause des travaux";
			zadanieArray[2]="Le pont fermé pendant la grève de transport";
			zadanieArray[3]="Le piéton heurté par une camionnette";
			zadanieArray[4]="Le boulevard bloqué suite d’un accident";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="11 (COMPRÉHENSION ÉCRITE)";
		/*задание №12 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>Des actions concrètes sont mises en place pour assurer la survie des espèces menacées. Cela faisait mille ans que l’on n’avait pas vu de bison en France. Depuis cinq ans, c’est de nouveau possible. Dans la réserve des Monts d’Azur, un programme de réintroduction est lancé pour permettre à cette espèce préhistorique de survivre. Des bisons venant d’une forêt de Pologne ont été introduits dans la réserve. Aujourd’hui, on compte une trentaine de bisons aux Monts d’Azur, dont une dizaine nés sur place.</p><p>Quel est le résultat principal de cette action?</p>";
			zadanieArray[1]="la naissance de petits bisons dans la région";
			zadanieArray[2]="la sélection d’une nouvelle espèce animale";
			zadanieArray[3]="l’augmentation de la surface forestière";
			zadanieArray[4]="la création d’une réserve aux Monts d’Azur";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="12 (COMPRÉHENSION ÉCRITE)";
		/*задание №13 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>Nouveau message</p><table><tr><td style='text-align:right; width:20%;'>À:</td><td style='text-align:left;'>Jacqueline.Lafavre@yaho.fr</td></tr><tr><td style='text-align:right; width:20%;'>Copie</td><td style='text-align:left;'>&nbsp;</td></tr><tr><td style='text-align:right; width:20%;'>Objet:</td><td style='text-align:left;'>&nbsp;</td></tr></table><p style='text-align:justify;  color:black;'>Félicitations mademoiselle!<br>Le texte de votre poésie «Pour mon ange» est véritablement magnifique. Simple, débordant d’amour comme j’aurais tant aimé en recevoir un jour!<br>J’espère que le jeune homme concerné saura toujours faire preuve de mérite quant au bel amour que vous lui prouvez là.<br>Je vous souhaite à tous les deux une belle et longue histoire.</p><p>Qu’est-ce qui a impressionné l’auteur de ce message?</p>";
			zadanieArray[1]="une future histoire passionnante";
			zadanieArray[2]="la nouvelle de la jeune fille";
			zadanieArray[3]="la force d’un sentiment exprimé";
			zadanieArray[4]="la manière originale de la composition";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="13 (COMPRÉHENSION ÉCRITE)";	
		/*задание №14 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>&nbsp;&nbsp;&nbsp;Chaque année, la France reçoit en moyenne un million de coups de foudre sur son sol et on dénombre entre 100 et 200 personnes blessées! Bien évidemment, ce n’est pas du coup de foudre amoureux. Ce fait est lié à l’orage. Dimanche et lundi derniers, sept personnes, dont deux enfants, ont été touchées par la foudre en France. Elles ont été sérieusement blessées, mais sont toujours en vie.</p><p>De quoi parle-t-on dans ce texte?</p>";
			zadanieArray[1]="des conséquences d’un phénomène naturel";
			zadanieArray[2]="de la croissance de la population en France";
			zadanieArray[3]="des accidents sur les autoroutes françaises";
			zadanieArray[4]="du rôle de l’amour dans la vie de chacun";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="14 (COMPRÉHENSION ÉCRITE)";
		/*задание №15 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="<p>Quel sentiment exprime l’auteur?</p>";
			zadanieArray[1]="de fierté";
			zadanieArray[2]="de nostalgie";
			zadanieArray[3]="de reconnaissance";
			zadanieArray[4]="de regret";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="15 (COMPRÉHENSION ÉCRITE)";
		/*задание №16 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="<p style='text-align:justify;  color:black;'>«Imaginez un monde dirigé par les enfants où toutes les décisions sont prises par des enfants de 10 ans» voilà ce que disent les auteurs de l’émission diffusée en Grande-Bretagne. Pendant deux semaines, 10 garçons et 10 filles, âgés de 8 à 11 ans, vont expérimenter la vie sans adultes sous l’oeil des caméras. Les créateurs de l’émission affirment que l’expérience est positive pour les enfants, qu’elle leur permet d’apprendre à devenir responsables et indépendants, et à vivre en groupe.</p><p>Pourquoi diffuse-t-on cette émission?</p>";
			zadanieArray[1]="parce qu’elle aide à développer une imagination";
			zadanieArray[2]="parce qu’elle apprend à comprendre l’anglais";
			zadanieArray[3]="parce qu’elle sert à trouver de jeunes acteurs";
			zadanieArray[4]="parce qu’elle permet d’éduquer les enfants";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="16 (COMPRÉHENSION ÉCRITE)";
		/*задание №17 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Il n’a jamais été question que l’amour s’arrête pour Fernande et Roger Raymond (17)&nbsp;___________ en octobre.";
			zadanieArray[1]="je suis entrée à l’église baroque avec des ailes";
			zadanieArray[2]="le respect et la liberté, des valeurs renforcées";
			zadanieArray[3]="après que Roger lui ait écrit une note poétique";
			zadanieArray[4]="qui célèbreront leur 63<sup>e</sup> anniversaire de mariage";
			zadanieArray[5]="au fur et à mesure que notre famille grandissait";
			zadanieArray[6]="une page de son histoire pour quelques papillons";
			zadanieArray[7]="l’autorité et la soumission, des sentiments causés";
			zadanieArray[8]="je suis entrée à la nouvelle mairie de la ville";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=saintValentinus;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="17 (COMPRÉHENSION ÉCRITE)";
		/*задание №18 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Et jamais le couple n’échangerait (18)&nbsp;___________.";
			zadanieArray[1]="je suis entrée à l’église baroque avec des ailes";
			zadanieArray[2]="le respect et la liberté, des valeurs renforcées";
			zadanieArray[3]="après que Roger lui ait écrit une note poétique";
			zadanieArray[4]="qui célèbreront leur 63<sup>e</sup> anniversaire de mariage";
			zadanieArray[5]="au fur et à mesure que notre famille grandissait";
			zadanieArray[6]="une page de son histoire pour quelques papillons";
			zadanieArray[7]="l’autorité et la soumission, des sentiments causés";
			zadanieArray[8]="je suis entrée à la nouvelle mairie de la ville";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=saintValentinus;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="18 (COMPRÉHENSION ÉCRITE)";
		/*задание №19 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="Quelques mois (19)&nbsp;___________ dans laquelle il promettait d’être fidèle, Fernande lui disait oui devant l’autel.";
			zadanieArray[1]="je suis entrée à l’église baroque avec des ailes";
			zadanieArray[2]="le respect et la liberté, des valeurs renforcées";
			zadanieArray[3]="après que Roger lui ait écrit une note poétique";
			zadanieArray[4]="qui célèbreront leur 63<sup>e</sup> anniversaire de mariage";
			zadanieArray[5]="au fur et à mesure que notre famille grandissait";
			zadanieArray[6]="une page de son histoire pour quelques papillons";
			zadanieArray[7]="l’autorité et la soumission, des sentiments causés";
			zadanieArray[8]="je suis entrée à la nouvelle mairie de la ville";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=saintValentinus;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="19 (COMPRÉHENSION ÉCRITE)";
		/*задание №20 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="Moi qui étais si gênée, (20)&nbsp;___________. Je ne voyais personne. Juste lui.»";
			zadanieArray[1]="je suis entrée à l’église baroque avec des ailes";
			zadanieArray[2]="le respect et la liberté, des valeurs renforcées";
			zadanieArray[3]="après que Roger lui ait écrit une note poétique";
			zadanieArray[4]="qui célèbreront leur 63<sup>e</sup> anniversaire de mariage";
			zadanieArray[5]="au fur et à mesure que notre famille grandissait";
			zadanieArray[6]="une page de son histoire pour quelques papillons";
			zadanieArray[7]="l’autorité et la soumission, des sentiments causés";
			zadanieArray[8]="je suis entrée à la nouvelle mairie de la ville";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=saintValentinus;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="20 (COMPRÉHENSION ÉCRITE)";
		/*задание №21 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="«On a déménagé (21)&nbsp;___________. Ensuite lorsqu’elle a rapetissé.»";
			zadanieArray[1]="je suis entrée à l’église baroque avec des ailes";
			zadanieArray[2]="le respect et la liberté, des valeurs renforcées";
			zadanieArray[3]="après que Roger lui ait écrit une note poétique";
			zadanieArray[4]="qui célèbreront leur 63<sup>e</sup> anniversaire de mariage";
			zadanieArray[5]="au fur et à mesure que notre famille grandissait";
			zadanieArray[6]="une page de son histoire pour quelques papillons";
			zadanieArray[7]="l’autorité et la soumission, des sentiments causés";
			zadanieArray[8]="je suis entrée à la nouvelle mairie de la ville";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=saintValentinus;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="21 (COMPRÉHENSION ÉCRITE)";
		/*задание №22 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Le secret de la longévité de leur relation, Fernande le partage d’emblée: (22)&nbsp;___________ par leur foi.";
			zadanieArray[1]="je suis entrée à l’église baroque avec des ailes";
			zadanieArray[2]="le respect et la liberté, des valeurs renforcées";
			zadanieArray[3]="après que Roger lui ait écrit une note poétique";
			zadanieArray[4]="qui célèbreront leur 63<sup>e</sup> anniversaire de mariage";
			zadanieArray[5]="au fur et à mesure que notre famille grandissait";
			zadanieArray[6]="une page de son histoire pour quelques papillons";
			zadanieArray[7]="l’autorité et la soumission, des sentiments causés";
			zadanieArray[8]="je suis entrée à la nouvelle mairie de la ville";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=saintValentinus;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
			taskNameArray[taskNumber-1]="22 (COMPRÉHENSION ÉCRITE)";
		/*задание №23 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="J’ai travaillé toute la nuit et je suis très fatigué. Mes yeux se ferment. J’ai&nbsp;____________."; 
			zadanieArray[1]="honte";
			zadanieArray[2]="espoir";
			zadanieArray[3]="sommeil";
			zadanieArray[4]="envie";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="23 (LEXIQUE)";			
		/*задание №24 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="– Nous avons des achats à faire.<br>– Il y a des réductions&nbsp;___________ en ce moment."; 
			zadanieArray[1]="du tarif";
			zadanieArray[2]="du budget";
			zadanieArray[3]="du salaire";
			zadanieArray[4]="du prix";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="24 (LEXIQUE)";
		/*задание №25 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="– Rue de la Gare, s’il vous plaît!<br>– C’est simple. Vous traversez __________ Georges Pompidou et vous prenez la  deuxième à droite et vous y êtes."; 
			zadanieArray[1]="la place";
			zadanieArray[2]="la ville";
			zadanieArray[3]="la rivière";
			zadanieArray[4]="la cour";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="25 (LEXIQUE)";
		/*задание №26 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="– Julien est un jeune homme très&nbsp;____________.<br>– D’où le sais-tu?<br>– Il souhaite toujours un bon anniversaire à ses connaissances."; 
			zadanieArray[1]="comique";
			zadanieArray[2]="paresseux";
			zadanieArray[3]="attentif";
			zadanieArray[4]="sévère";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="26 (LEXIQUE)";
		/*задание №27 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="– Julie, pourrais-tu&nbsp;_____________ ma boîte aux lettres. Elle doit être pleine.<br>– D’accord, j’y vais."; 
			zadanieArray[1]="regarder";
			zadanieArray[2]="écrire";
			zadanieArray[3]="fermer";
			zadanieArray[4]="poster";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="27 (LEXIQUE)";
		/*задание №28 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="– Jacqueline a&nbsp;___________ l’argent que son frère lui a donné."; 
			zadanieArray[1]="accepté";
			zadanieArray[2]="volé";
			zadanieArray[3]="blanchi";
			zadanieArray[4]="avancé";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="28 (LEXIQUE)";
		/*задание №29 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="Une cliente téléphone à l’entreprise de vente par correspondance. Elle s’adresse à un vendeur: «Bonjour, Monsieur. Je voudrais faire&nbsp;___________ pour ce lundi»."; 
			zadanieArray[1]="une commande";
			zadanieArray[2]="une offre";
			zadanieArray[3]="une présentation";
			zadanieArray[4]="une réclamation";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="29 (LEXIQUE)";
		/*задание №30 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="– Mademoiselle Jasmine, vous avez de graves&nbsp;__________ en mathématiques. Vous avez obtenu zéro pour le dernier test."; 
			zadanieArray[1]="succès";
			zadanieArray[2]="résultats";
			zadanieArray[3]="problèmes";
			zadanieArray[4]="perspectives";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="30 (LEXIQUE)";
		/*задание №31 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="– С’est le quatrième appartement dont je change en deux mois. Je n’en peux plus.<br>– Effectivement. Trois&nbsp;___________ valent un incendie."; 
			zadanieArray[1]="inspections";
			zadanieArray[2]="cambriolages";
			zadanieArray[3]="saccagements";
			zadanieArray[4]="déménagements";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="31 (LEXIQUE)";
		/*задание №32 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="– Il est onze heures et Hugo n’est pas encore au bureau?<br>– Il fait&nbsp;___________, Monsieur."; 
			zadanieArray[1]="la grasse matinée";
			zadanieArray[2]="la sourde oreille";
			zadanieArray[3]="la fine bouche";
			zadanieArray[4]="la courte échelle";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="32 (LEXIQUE)";
		/*задание №33 ЗНО-2014 немецкий язык. Основной тест(доделать!!!)*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="– Qu’est-ce que&nbsp;____________ dis aux enfants quand ils font beaucoup de bruit?<br>– Chut! Papa travaille."; 
			zadanieArray[1]="vous";
			zadanieArray[2]="je";
			zadanieArray[3]="nous";
			zadanieArray[4]="tu";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="33 (GRAMMAIRE)";
		/*задание №34 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="Sarah, ____________-moi votre cahier, je veux voir ce que vous avez fait."; 
			zadanieArray[1]="montre";
			zadanieArray[2]="montrons";
			zadanieArray[3]="montrez";
			zadanieArray[4]="montres";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="34 (GRAMMAIRE)";
		/*задание №35 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Je voudrais aller à Barton Sprint. J’adore l’eau. _____________. Tu viens avec moi?"; 
			zadanieArray[1]="J’ai nagé";
			zadanieArray[2]="J’aurais nagé";
			zadanieArray[3]="Je nageai";
			zadanieArray[4]="Je vais nager";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="35 (GRAMMAIRE)";
		/*задание №36 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="Le jeudi soir, Aurélie&nbsp;____________ pendant deux heures dans le club des amateurs de jardinage."; 
			zadanieArray[1]="travaillera";
			zadanieArray[2]="travaillait";
			zadanieArray[3]="travaillerait";
			zadanieArray[4]="travailla";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="36 (GRAMMAIRE)";
		/*задание №37 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=37;
			var zadanieArray=new Array();
			zadanieArray[0]="– Que vas-tu prendre pour le petit déjeuner?<br>– Je&nbsp;____________ un café au lait."; 
			zadanieArray[1]="prendras";
			zadanieArray[2]="prendra";
			zadanieArray[3]="prendrait";
			zadanieArray[4]="prendrai";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="37 (GRAMMAIRE)";
		/*задание №38 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=38;
			var zadanieArray=new Array();
			zadanieArray[0]="Les Galettes du Roi&nbsp;_____________avec des couronnes en papier doré ou argenté."; 
			zadanieArray[1]="soient vendues";
			zadanieArray[2]="furent vendues";
			zadanieArray[3]="sont vendues";
			zadanieArray[4]="seraient vendues";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="38 (GRAMMAIRE)";
		/*задание №39 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=39;
			var zadanieArray=new Array();
			zadanieArray[0]="– Vous avez de la chance! Il fait&nbsp;_____________ soleil."; 
			zadanieArray[1]="de";
			zadanieArray[2]="du";
			zadanieArray[3]="le";
			zadanieArray[4]="un";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="39 (GRAMMAIRE)";
		/*задание №40 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=40;
			var zadanieArray=new Array();
			zadanieArray[0]="– Quand un garçon me plaît, je&nbsp;___________ regarde pendant les cours et j’essaie de m’asseoir à côté de lui."; 
			zadanieArray[1]="celui";
			zadanieArray[2]="le";
			zadanieArray[3]="lui";
			zadanieArray[4]="me";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="40 (GRAMMAIRE)";
		/*задание №41 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=41;
			var zadanieArray=new Array();
			zadanieArray[0]="– Le tableau&nbsp;____________ je vous parle est la perle de l’exposition du Louvre."; 
			zadanieArray[1]="auquel";
			zadanieArray[2]="dont";
			zadanieArray[3]="que";
			zadanieArray[4]="où";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="41 (GRAMMAIRE)";
		/*задание №42 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=42;
			var zadanieArray=new Array();
			zadanieArray[0]="– Êtes-vous allé en Turquie, Céline?<br>– Oui, ____________ suis allée quelques fois."; 
			zadanieArray[1]="j’en";
			zadanieArray[2]="j’y";
			zadanieArray[3]="je la";
			zadanieArray[4]="je le";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="42 (GRAMMAIRE)";
		/*задание №43 ЗНО-2014 немецкий язык. Основной тест*/
			taskNumber=43;
			var zadanieArray=new Array();
			zadanieArray[0]="Vous vous êtes inscrit(e) à un club sportif. Impressionné(e) par votre première expérience, vous écrivez à votre ami(e) français(e) pour:<ul><li>caractériser ce club;</li><li>expliquer votre choix d’une activité sportive;</li><li>questionner votre ami(e) sur ses succès sportifs.</li></ul>"; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]="";
			taskTypeArray[taskNumber-1]="tvir";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=14;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="43 (EXPRESSION ÉCRITE)";
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}	/* Окончание ЗНО-2014 немецкий язык. Основной тест. I сессия*/	
	
/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();
	
}
