function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/
/*************************************************************/
//Тесты по английскому языку	
/*************************************************************/	
/*ЗНО-2013 английский язык. Основной тест. I сессия*/
	if(testName==znoEng2013Main)
	{
		testLength=43;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/eng\/img\/test2013main1\/';
		testTitle = znoName+"2013"+znoEngName;
		testDetails=mainName;
		answerLanguage="eng";
		gradeArray=new Array("100.0","100.5","100.5","102.0","105.0","108.5","113.0","116.0","120.5","125.5","128.5","131.5","134.0","136.0","137.5","139.0","140.0","141.5","142.5","144.0","145.0","146.0","147.0","148.0","149.0","150.5","151.5","152.5","153.5","154.5","155.5","156.5","158.0","159.0","160.0","161.5","162.5","164.0","165.5","166.5","168.0","169.5","171.5","173.0","175.0","177.0","179.0","181.0","183.5","186.5","189.0","192.0","194.5","197.0","199.0","199.5","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var chupaChups="The History of Chupa Chups Lollipops\n\n\t The Chupa Chups company started as an idea of a Spanish citizen named Enric Bernat in 1958. Mr. Bernat started his career at an apple jam factory. He approached investors about a lollipop business but he failed to get support. He took over the company himself and built the first production machines with his own hands. He also decided that the new creation would be called Chupa Chups, after the Spanish verb chupar, which translates into to suck.\n\t Enric Bernat knew that the bon-bons on a wooden stick would be an instant hit. Previously candy had been marketed as a luxury and kept away from children. However, he knew that if he could get the candy into the view of children he would sell many more lollipops. Five years after he first introduced the idea, Chupa Chups were being sold at over 300,000 stores across Europe. \n\t The original Chupa Chups sales force was over 600 sales agents for 300,000 locations. This amazing sales force sped across Europe to bring the good news and delicious taste of the Chupa Chups lollipops to the masses. Without their dedication and excitement, there would be no way the company could have grown to the massive size that it is today. \n\t Sadly, the traditional wooden stick that was associated with Chupa Chups had to be discontinued and replaced with a plastic one due to the lack of wood available in Spain. The stick has remained plastic ever since. \n\t Chupa Chups were originally going to be called GOL but the name did not stick. An advertising firm came up with the idea to name them Chupa and the delightful lollipops were born. Salvador Dali, the famous painter, created the new Chupa Chups logo, which remains on the wrapper on all of the lollipops to this day. \n\t The Chupa Chups business went international beginning with Asia and Australia in the 1970’s. It soon followed to North America and the rest of Europe. The amazing results led to a high point for the company, with the production of over 4 billion Chupa Chups lollipops during the 2003 calendar year.";
		var zebras="Why are Zebras Striped?\n\nWhen zebras stick together in a herd, the pattern of their stripes blend together with the stripes of the zebras around them. This is confusing to a lion! All it can see is a large, moving, striped mass. The lion has trouble picking out individual zebras and it’s harder still for the lion to recognize (17)____!\n\nEach zebra pattern is unique like a fingerprint. Like a fingerprint (18)____ and no two zebras are exactly alike. What is truly amazing is (19)____ from their body stripe!\n\nThere are several species classified according to variations in stripe patterns. The mountain zebra has silver-white stripes with black markings (20)____ except for the stomach and the inner thighs. Plains zebras are pale yellow with broad black stripes.\n\nDo you know that people of Africa think of zebras as black animals with white stripes (21)____ as white animals with black stripes! Black stripes or white, the fact remains (22)____ and are among the fastest and most graceful of runners in the African bush land.";
		var Sugababes="\tSugababes\n\nThe story of the Sugababes starts with two self-confident eight-year-old friends from London who (23)____ a hatred of maths but loved singing (24)____ to the radio. Mutya and Keisha then met Siobhan who joined their “gang”. They (25)____ writing and singing and at fourteen the group (26)____ their first record deal. Just two years later, when their classmates were studying for their exams, the girls (27)__________ their first album, the incredibly cool One Touch. But it wasn’t as easy as it (28)____. The album didn’t get publicity and Siobhan decided to leave the group.\n\nKeisha and Mutya advertised for another girl but did not want to (29)____ the group name. “We wanted someone who could sing and had her own ideas,” they said. That was Heidi. Heidi used to be in the girlband Atomic Kitten but she left because she never quite (30)____ in. Heidi was desperate to sing live in concerts and do her own writing – and she soon realised that she would never be able to do this in a “manufactured” band. Her love of urban music (31)____ her the perfect Sugababe. The three became friends as soon as they met and (32)____ to write and record the huge Angels with Dirty Faces album.";
		var toucan="\tThe Beak of the Toucan\n\nWhy does the toucan (33)____ such an enormous beak? The answer, we learned in August, may be that it uses it (34)____ body temperature. Infrared measurement (35)____ just before sleep shows that the bird’s long beak – which can grow to (36)____ of its body size – gets hotter, (37)____ the bird uses it in the presleep cooling process. At other times, as the external heat rises, so too does the heat of the toucan’s beak, while its core body heat stays the same.";
		var ScientificProgress="\tScientific Progress\n\nDespite warnings that it might set off a catastrophic chain reaction that could (38)____ the Earth, scientists have (39)____ created a miniature version of the Big Bang, without any observable ill effects. They were able (40)____ a temperature of (41)____ ten trillion degrees – a million times hotter than the centre of the sun – by (42)____ together lead ions at incredible speeds in the Large Hadron Collider, a 27 km underground tunnel at the CERN (European Organization for Nuclear Research) facility near Geneva.";
		var taskNumber=1;
		/*задание №1 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<br>What are the advertisement about?<p style='text-align:center;  color:red;'>BACK PAIN?<br>Use these Safe and Simple methods to free<br>yourself from back pain misery.<br>FREE Report<br>Visit:<br>www.banishbackpain.co.uk</p>";
			zadanieArray[1]="Properties for sale";
			zadanieArray[2]="Educational services";
			zadanieArray[3]="Editing services";
			zadanieArray[4]="Holidaymaking";
			zadanieArray[5]="Art exhibition";
			zadanieArray[6]="Publishing services";
			zadanieArray[7]="Handicraft art";
			zadanieArray[8]="Health care";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №2 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<br>What are the advertisement about?<p style='text-align:center;  color:red;'>We make a book out of your manuscript.<br>Looking for NEW AUTHORS<br>ALL SUBJECTS INVITED<br>write or send your work to:<br>ATHENA PRESS<br>QUEEN’S HOUSE, 3 HOLLY ROAD,<br>TWICKENHAM, TW1 4EG<br>www.athenapress.com<br>e-mail: info@athenapress.com</p>";
			zadanieArray[1]="Properties for sale";
			zadanieArray[2]="Educational services";
			zadanieArray[3]="Editing services";
			zadanieArray[4]="Holidaymaking";
			zadanieArray[5]="Art exhibition";
			zadanieArray[6]="Publishing services";
			zadanieArray[7]="Handicraft art";
			zadanieArray[8]="Health care";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №3 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<br>What are the advertisement about?<p style='text-align:center;  color:red;'>KCP International<br>Language Institute<br>is pleased to be able to offer students from around<br>the world a unique opportunity to learn more about<br>Japan, its language and culture. Our programs are<br>open to all English speaking students.<br>http://www.kcpinternational.com</p>";
			zadanieArray[1]="Properties for sale";
			zadanieArray[2]="Educational services";
			zadanieArray[3]="Editing services";
			zadanieArray[4]="Holidaymaking";
			zadanieArray[5]="Art exhibition";
			zadanieArray[6]="Publishing services";
			zadanieArray[7]="Handicraft art";
			zadanieArray[8]="Health care";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №4 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<br>What are the advertisement about?<p style='text-align:center;  color:red;'>THE JOHN DAVIES GALLERY<br>Deep in the West Country<br>RICHARD THORN<br>Admire our new collection of 50 new paintings<br>2nd – 23rd October 2010<br>Open 9.30 am – 5.30 pm<br>Monday to Saturday</p>";
			zadanieArray[1]="Properties for sale";
			zadanieArray[2]="Educational services";
			zadanieArray[3]="Editing services";
			zadanieArray[4]="Holidaymaking";
			zadanieArray[5]="Art exhibition";
			zadanieArray[6]="Publishing services";
			zadanieArray[7]="Handicraft art";
			zadanieArray[8]="Health care";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №5 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 1<br>Read the text below.<br>What are the advertisement about?<p style='text-align:center;  color:red;'>Melbury Abbas, Dorset SP7<br>&pound;625,000 guide price<br>An attractively designed 4 bedroom modern family<br>home in a lovely setting with half an acre of<br>delightfully landscaped gardens.<br>Contact 9901 7490 65</p>";
			zadanieArray[1]="Properties for sale";
			zadanieArray[2]="Educational services";
			zadanieArray[3]="Editing services";
			zadanieArray[4]="Holidaymaking";
			zadanieArray[5]="Art exhibition";
			zadanieArray[6]="Publishing services";
			zadanieArray[7]="Handicraft art";
			zadanieArray[8]="Health care";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №6 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>Which of the following is stated in the text about Enric Bernat?</p>"; 
			zadanieArray[1]="He inherited the family business.";
			zadanieArray[2]="He borrowed money from a bank.";
			zadanieArray[3]="He devoted his life to jam production.";
			zadanieArray[4]="He made the factory equipment himself.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=chupaChups;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №7 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>What is TRUE about the Chupa Chups logo?</p>"; 
			zadanieArray[1]="It was designed by a great artist.";
			zadanieArray[2]="It made the lollipop more popular.";
			zadanieArray[3]="It has changed three times by now.";
			zadanieArray[4]="It varies from country to country.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=chupaChups;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №8 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>Where was the Chupa Chups business originally concentrated?</p>"; 
			zadanieArray[1]="In Asia";
			zadanieArray[2]="In Europe";
			zadanieArray[3]="In Australia";
			zadanieArray[4]="In America";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=chupaChups;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №9 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>According to the text, what helped the company to become a big success?</p>"; 
			zadanieArray[1]="The product’s unusual name";
			zadanieArray[2]="The variety of lollipop tastes";
			zadanieArray[3]="The candy’s attractive wrapping";
			zadanieArray[4]="The sales staff’s enthusiasm";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=chupaChups;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №10 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 2<br>Read the text below.<p style='text-align:justify;  color:black;'>Which of the following is NOT TRUE according to the text?</p>"; 
			zadanieArray[1]="Candies used to be an expensive treat.";
			zadanieArray[2]="The name Chupa Chups means bon-bons.";
			zadanieArray[3]="Chupa Chups originally had wooden sticks.";
			zadanieArray[4]="Bernat’s product was meant mainly for children.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=chupaChups;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №11 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:blue;'><p style='text-align:center;'>Chinese New Year</p>Chinese New Year is the most important of the traditional Chinese holidays. It falls on different dates each year, between January&nbsp;21 and February&nbsp;20. Visits to friends and family take place during this celebration. Everything golden is said to bring wealth, and everything red is considered especially lucky.</p><p style='text-align:justify;  color:black;'>Which of the winter celebrations is associated with&nbsp;________?</p>";
			zadanieArray[1]="bonfires in the backyard";
			zadanieArray[2]="honoring people’s main values";
			zadanieArray[3]="an imaginary figure appearing in different ways";
			zadanieArray[4]="a festive treat containing a surprise";
			zadanieArray[5]="colours to make people fortunate";
			zadanieArray[6]="sharing food with neighbours";
			zadanieArray[7]="a special dish eaten with something sweet";
			zadanieArray[8]="greens as symbols of riches";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
		/*задание №12 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:blue;'><p style='text-align:center;'>Christmas</p>Christmas is the celebration of the birth of Jesus Christ. Around the world, family members help to decorate trees and homes with bright lights, wreaths, candles, holly, mistletoe, and ornaments. On Christmas Eve, many people go to church. Also on Christmas Eve, Santa comes from the North Pole in a sleigh to deliver gifts. In Hawaii, it is said he arrives by boat, in Australia, the jolly man arrives on water skis, and in Ghana, he comes out of the jungle.</p><p style='text-align:justify;  color:black;'>Which of the winter celebrations is associated with&nbsp;________?</p>";
			zadanieArray[1]="bonfires in the backyard";
			zadanieArray[2]="honoring people’s main values";
			zadanieArray[3]="an imaginary figure appearing in different ways";
			zadanieArray[4]="a festive treat containing a surprise";
			zadanieArray[5]="colours to make people fortunate";
			zadanieArray[6]="sharing food with neighbours";
			zadanieArray[7]="a special dish eaten with something sweet";
			zadanieArray[8]="greens as symbols of riches";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
		/*задание №13 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:blue;'><p style='text-align:center;'>Hanukkah</p>Jewish people celebrate Hanukkah, a holiday honoring the Maccabees victory over King Antiochus, who forbade Jews to practice their religion. For eight nights, Hanukkah is celebrated with prayer, the lighting of the menorah, and food. Children play games, sing  songs, and exchange gifts. Potato pancakes, known as latkes in Yiddish, are traditionally served with applesauce or jam.</p><p style='text-align:justify;  color:black;'>Which of the winter celebrations is associated with&nbsp;________?</p>";
			zadanieArray[1]="bonfires in the backyard";
			zadanieArray[2]="honoring people’s main values";
			zadanieArray[3]="an imaginary figure appearing in different ways";
			zadanieArray[4]="a festive treat containing a surprise";
			zadanieArray[5]="colours to make people fortunate";
			zadanieArray[6]="sharing food with neighbours";
			zadanieArray[7]="a special dish eaten with something sweet";
			zadanieArray[8]="greens as symbols of riches";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="g";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
		/*задание №14 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:blue;'><p style='text-align:center;'>Kwanzaa</p>On December&nbsp;26, Kwanzaa is celebrated. It is a holiday to commemorate African heritage. Kwanzaa lasts a week during which participants gather with family and friends to exchange gifts and to light a series of black, red, and green candles. These candles symbolize the seven basic merits of African American family life: unity, self-determination, collective work and responsibility, cooperative economics, purpose, creativity, and faith.</p><p style='text-align:justify;  color:black;'>Which of the winter celebrations is associated with&nbsp;________?</p>";
			zadanieArray[1]="bonfires in the backyard";
			zadanieArray[2]="honoring people’s main values";
			zadanieArray[3]="an imaginary figure appearing in different ways";
			zadanieArray[4]="a festive treat containing a surprise";
			zadanieArray[5]="colours to make people fortunate";
			zadanieArray[6]="sharing food with neighbours";
			zadanieArray[7]="a special dish eaten with something sweet";
			zadanieArray[8]="greens as symbols of riches";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
		/*задание №15 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:blue;'><p style='text-align:center;'>New Year’s Day</p>New Year’s Day, on January&nbsp;1, is the first day of the year in the Gregorian calendar. There are often fireworks at midnight to celebrate the New Year. Commonly served in the southern part of the United States, peas are thought to bring luck for the New Year, and vegetables bring wealth.</p><p style='text-align:justify;  color:black;'>Which of the winter celebrations is associated with&nbsp;________?</p>";
			zadanieArray[1]="bonfires in the backyard";
			zadanieArray[2]="honoring people’s main values";
			zadanieArray[3]="an imaginary figure appearing in different ways";
			zadanieArray[4]="a festive treat containing a surprise";
			zadanieArray[5]="colours to make people fortunate";
			zadanieArray[6]="sharing food with neighbours";
			zadanieArray[7]="a special dish eaten with something sweet";
			zadanieArray[8]="greens as symbols of riches";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
		/*задание №16 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 3<br>Read the text below.<p style='text-align:justify;  color:blue;'><p style='text-align:center;'>Three Kings Day</p>At the end of the Twelve Days of Christmas comes a day called the Epiphany, or Three Kings Day. This holiday is celebrated as the day the three wise men first saw baby Jesus and brought him gifts. On this day in Spain, many children get their Christmas presents. In Puerto Rico, before children go to sleep on January&nbsp;5, they leave a box with hay under their beds so the kings will leave good presents. In France, a delicious King cake is baked. Bakers will hide a coin, jewel or little toy inside it.</p><p style='text-align:justify;  color:black;'>Which of the winter celebrations is associated with&nbsp;________?</p>";
			zadanieArray[1]="bonfires in the backyard";
			zadanieArray[2]="honoring people’s main values";
			zadanieArray[3]="an imaginary figure appearing in different ways";
			zadanieArray[4]="a festive treat containing a surprise";
			zadanieArray[5]="colours to make people fortunate";
			zadanieArray[6]="sharing food with neighbours";
			zadanieArray[7]="a special dish eaten with something sweet";
			zadanieArray[8]="greens as symbols of riches";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;	
		/*задание №17 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The lion has trouble picking out individual zebras and it’s harder still for the lion to recognize (17)&nbsp;__________!</p>";
			zadanieArray[1]="that zebras are extremely unique";
			zadanieArray[2]="patterns vary from zebra to zebra";
			zadanieArray[3]="whereas people outside Africa consider them";
			zadanieArray[4]="zebras’ stripes are hard to count";
			zadanieArray[5]="that zebras can recognize other zebras";
			zadanieArray[6]="which way each zebra is moving";
			zadanieArray[7]="Africans try to protect zebras";
			zadanieArray[8]="that extend to every part of the body";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="f";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=zebras;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №18 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Like a fingerprint (18)&nbsp;__________and no two zebras are exactly alike.</p>";
			zadanieArray[1]="that zebras are extremely unique";
			zadanieArray[2]="patterns vary from zebra to zebra";
			zadanieArray[3]="whereas people outside Africa consider them";
			zadanieArray[4]="zebras’ stripes are hard to count";
			zadanieArray[5]="that zebras can recognize other zebras";
			zadanieArray[6]="which way each zebra is moving";
			zadanieArray[7]="Africans try to protect zebras";
			zadanieArray[8]="that extend to every part of the body";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=zebras;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №19 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>What is truly amazing is (19)&nbsp;__________from their body stripe!</p>";
			zadanieArray[1]="that zebras are extremely unique";
			zadanieArray[2]="patterns vary from zebra to zebra";
			zadanieArray[3]="whereas people outside Africa consider them";
			zadanieArray[4]="zebras’ stripes are hard to count";
			zadanieArray[5]="that zebras can recognize other zebras";
			zadanieArray[6]="which way each zebra is moving";
			zadanieArray[7]="Africans try to protect zebras";
			zadanieArray[8]="that extend to every part of the body";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="e";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=zebras;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №20 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The mountain zebra has silver-white stripes with black markings (20)&nbsp;__________except for the stomach and the inner thighs.</p>";
			zadanieArray[1]="that zebras are extremely unique";
			zadanieArray[2]="patterns vary from zebra to zebra";
			zadanieArray[3]="whereas people outside Africa consider them";
			zadanieArray[4]="zebras’ stripes are hard to count";
			zadanieArray[5]="that zebras can recognize other zebras";
			zadanieArray[6]="which way each zebra is moving";
			zadanieArray[7]="Africans try to protect zebras";
			zadanieArray[8]="that extend to every part of the body";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="h";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=zebras;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №21 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Do you know that people of Africa think of zebras as black animals with white stripes (21)&nbsp;__________as white animals with black stripes!</p>";
			zadanieArray[1]="that zebras are extremely unique";
			zadanieArray[2]="patterns vary from zebra to zebra";
			zadanieArray[3]="whereas people outside Africa consider them";
			zadanieArray[4]="zebras’ stripes are hard to count";
			zadanieArray[5]="that zebras can recognize other zebras";
			zadanieArray[6]="which way each zebra is moving";
			zadanieArray[7]="Africans try to protect zebras";
			zadanieArray[8]="that extend to every part of the body";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=zebras;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №22 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 4<br>Read the text below.<br> Choose from (A – H) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Black stripes or white, the fact remains (22)&nbsp;__________and are among the fastest and most graceful of runners in the African bush land.</p>";
			zadanieArray[1]="that zebras are extremely unique";
			zadanieArray[2]="patterns vary from zebra to zebra";
			zadanieArray[3]="whereas people outside Africa consider them";
			zadanieArray[4]="zebras’ stripes are hard to count";
			zadanieArray[5]="that zebras can recognize other zebras";
			zadanieArray[6]="which way each zebra is moving";
			zadanieArray[7]="Africans try to protect zebras";
			zadanieArray[8]="that extend to every part of the body";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=zebras;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=8;
		/*задание №23 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The story of the Sugababes starts with two self-confident eight-year-old friends from London who (23)&nbsp;__________a hatred of maths but loved singing...</p>"; 
			zadanieArray[1]="united";
			zadanieArray[2]="combined";
			zadanieArray[3]="shared";
			zadanieArray[4]="joined";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
		/*задание №24 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...hatred of maths but loved singing (24)&nbsp;__________to the radio.</p>"; 
			zadanieArray[1]="along";
			zadanieArray[2]="nearly";
			zadanieArray[3]="across";
			zadanieArray[4]="beside";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №25 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>They (25)&nbsp;__________writing and singing...</p>"; 
			zadanieArray[1]="opened";
			zadanieArray[2]="disclosed";
			zadanieArray[3]="revealed";
			zadanieArray[4]="discovered";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №26 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...and at fourteen the group (26)&nbsp;__________their first record deal.</p>"; 
			zadanieArray[1]="took";
			zadanieArray[2]="brought";
			zadanieArray[3]="got";
			zadanieArray[4]="wrote";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №27 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Just two years later, when their classmates were studying for their exams, the girls (27)&nbsp;__________their first album, the incredibly cool <i>One Touch</i>.</p>"; 
			zadanieArray[1]="demonstrated";
			zadanieArray[2]="released";
			zadanieArray[3]="published";
			zadanieArray[4]="displayed";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №28 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>But it wasn’t as easy as it (28)&nbsp;__________.</p>"; 
			zadanieArray[1]="says";
			zadanieArray[2]="proclaims";
			zadanieArray[3]="goes";
			zadanieArray[4]="sounds";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №29 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Keisha and Mutya advertised for another girl but did not want to (29)&nbsp;__________the group name.</p>"; 
			zadanieArray[1]="bare";
			zadanieArray[2]="mention";
			zadanieArray[3]="describe";
			zadanieArray[4]="comment";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №30 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Heidi used to be in the girlband Atomic Kitten but she left because she never quite (30)&nbsp;__________in.</p>"; 
			zadanieArray[1]="fitted";
			zadanieArray[2]="went";
			zadanieArray[3]="suited";
			zadanieArray[4]="got";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №31 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Her love of urban music (31)&nbsp;__________her the perfect Sugababe.</p>"; 
			zadanieArray[1]="kept";
			zadanieArray[2]="did";
			zadanieArray[3]="held";
			zadanieArray[4]="made";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
		/*задание №32 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=32;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 5<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The three became friends as soon as they met and (32)&nbsp;__________to write and record the huge <i>Angels with Dirty Faces</i> album.</p>"; 
			zadanieArray[1]="went down";
			zadanieArray[2]="went off";
			zadanieArray[3]="went on";
			zadanieArray[4]="went up";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=Sugababes;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
		/*задание №33 ЗНО-2013 английский язык. Основной тест(доделать!!!)*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Why does the toucan (33)&nbsp;__________such an enormous beak?</p>";
			zadanieArray[1]="has";
			zadanieArray[2]="had";
			zadanieArray[3]="having";
			zadanieArray[4]="have";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=toucan;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
		/*задание №34 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>The answer, we learned in August, may be that it uses it (34)&nbsp;__________body temperature.</p>";
			zadanieArray[1]="regulate";
			zadanieArray[2]="to regulate";
			zadanieArray[3]="regulated";
			zadanieArray[4]="regulates";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=toucan;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
		/*задание №35 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Infrared measurement (35)&nbsp;__________just before sleep shows that...</p>";
			zadanieArray[1]="taken";
			zadanieArray[2]="take";
			zadanieArray[3]="to take";
			zadanieArray[4]="taking";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=toucan;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
		/*задание №36 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...shows that the bird’s long beak – which can grow to (36)&nbsp;__________of its body size – gets hotter,...</p>"; 
			zadanieArray[1]="third";
			zadanieArray[2]="a three";
			zadanieArray[3]="a third";
			zadanieArray[4]="three";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=toucan;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №37 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=37;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...gets hotter, (37)&nbsp;__________the bird uses it in the presleep cooling process.</p>"; 
			zadanieArray[1]="suggested";
			zadanieArray[2]="suggesting";
			zadanieArray[3]="suggest";
			zadanieArray[4]="to suggest";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=toucan;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №38 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=38;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>Despite warnings that it might set off a catastrophic chain reaction that could (38)&nbsp;__________the Earth,...</p>"; 
			zadanieArray[1]="to destroy";
			zadanieArray[2]="destroying";
			zadanieArray[3]="destroyed";
			zadanieArray[4]="destroy";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=ScientificProgress;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №39 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=39;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...scientists have (39)&nbsp;__________ created a miniature version of the Big Bang, without any observable ill effects.</p>"; 
			zadanieArray[1]="successful";
			zadanieArray[2]="success";
			zadanieArray[3]="successfully";
			zadanieArray[4]="successfulness";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=ScientificProgress;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №40 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=40;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>They were able (40)&nbsp;__________ a temperature...</p>"; 
			zadanieArray[1]="produce";
			zadanieArray[2]="produced";
			zadanieArray[3]="to produce";
			zadanieArray[4]="producing";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=ScientificProgress;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №41 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=41;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>temperature of (41)&nbsp;__________ ten trillion degrees...</p>"; 
			zadanieArray[1]="the most";
			zadanieArray[2]="more than";
			zadanieArray[3]="more";
			zadanieArray[4]="much more";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=ScientificProgress;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №42 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=42;
			var zadanieArray=new Array();
			zadanieArray[0]="Task 6<br>Read the text below.<br> Choose from (A – D) the one which best fits following sentence in the text.<p style='text-align:justify;  color:black;'>...a million times hotter than the centre of the sun – by (42)&nbsp;__________ together lead ions at incredible speeds in the Large Hadron Collider, a 27&nbsp;km underground tunnel at the CERN (European Organization for Nuclear Research) facility near Geneva.</p>"; 
			zadanieArray[1]="smashing";
			zadanieArray[2]="smashed";
			zadanieArray[3]="smash";
			zadanieArray[4]="to smash";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="textanalysis";
			textAnalysisArray[taskNumber-1]=ScientificProgress;
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
		/*задание №43 ЗНО-2013 английский язык. Основной тест*/
			taskNumber=43;
			var zadanieArray=new Array();
			zadanieArray[0]="Writing<br>Listening to a radio programme you heard different people discussing the topic of friendship between teens. You have decided to write a letter to the editor of the programme. In your letter <ul><li>describe what kind of friend you prefer and why</li><li>say what can cause a friendship to go wrong</li><li>argue whether it is better to have a wide circle of friends or a few close friends</li></ul>Write a letter of at least 100 words. Do not write your own name, any dates, addresses or other personal information. Start your letter in an appropriate way."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]="";
			taskTypeArray[taskNumber-1]="tvir";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=14;
			variantNumberArray[taskNumber-1]=4;	
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],"");
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}	/* Окончание ЗНО-2013 английский язык. Основной тест. I сессия*/	
	
/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();	
	
}
