function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/

/*************************************************************/
//Тесты по французскому языку	
/*************************************************************/		
/*ЗНО-2011 французский язык. Основной тест.*/
	if(testName==znoFra2011Main)
	{
		testLength=46;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/fra\/img\/test2011main1\/';
		testTitle = znoName+"2011"+znoFraName;
		testDetails=mainName;
		var inet_annonce="Professionnels, vous n'avez pas ou plus de secretaire. Particuliers, vous ne savez pas (ou mal) taper sur un clavier... Je vous propose a distance des services individualises et de qualite. Exemples: compte-rendu, livre, these, bon de commande, facture de l'hotel en un mot l'enregistrement sur un ordinateur de tous documents ecrits a la main ou enregistres. Site: http://www.isa-tap.com Tel.: 03.26.70.52.05., isabelle.demianville@laposte.net";
		var tv_prog='   FRANCE 3\n20.55 Lit Grande Illusion Divertissement. Presente par Valerie Benain. \n\nApres Marseille et Paris,«La Grande Illusion» entreprend de perturber l\'espace-temps et le sens commun a La Rochelle. Pierre Palmade, piege par son complice de «Made in Palmade», vole au secours d\'une femme enceinte et bascule dans un monde sans repere. \n\n\n   TF1\n20.50 Josephine, ange gardien: Profession menteur Telefilm de Sylvie Ayme (Fr., 2006). 1 h 30. Avec Mimie Mathy, Bruno Debrandt.\n\nFrederic Duval a perdu son travail mais n\'en a rien dit a ses proches. Josephine intervient pour le ramener a la raison. Elle le pousse a cesser de vivre dans le mensonge. \n\n\n   FRANCE 2\n20.50 Cold Case, affaires classees   Serie.   «Reves   et desillusions». (USA, 2006). Avec Kathryn Morris, Danny  Pino,   Jeremy Ratcliford. \n\n1929: une femme est retrouvee morte le jour de Noel. 2006: l\'arriere-petite-fille de la defunte sollicite l\'aide de Lilly et de son equipe pour en savoir plus sur les circonstances de la mort de son aieule. \n\n\n   M6\n20.50 Kaamelott Serie. «Livre V, 2e partie». Avec Alexandre Astier; Guy Bedos, Patrick Bouchitey. \n\nKaamelott est sans Roi: l\'epee est a nouveau plantee dans le rocher Alors que les clans autonomes se multiplient,on etudie vainement les lois bretonnes afin de designer un chef d\' Etat. Arthur doit se mettre a la recherche de sa possible descendance.';
		var text3_2011='Creee en 1914, afin d\'expedier les hommes et tes materiaux necessaires a la construction du barrage d\'Artouste, situee a 2000 metres d\'attitude, cette ligne de chemin de fer, parmi les plus hautes d\'Europe fut maintenue puis modernisee, des 1932 a des fins touristiques. Sur 10 km de voie a cote de montagne vous decouvrirez des champs de plantes sauvages et vous vous laisserez surprendre par de paysages admirables. Fonctionne tous les jours.';
		var brest='Brest: le prefet interdit l\'alcool le jeudi soir sire la place de la Liberte \n\nPar arrete prefectoral, la consommation d\'alcool est interdite place de la Liberte, au centre-ville de Brest, ainsi que dans plusieurs rues voisines, entre 21 h et 6 h du matin. Cette mesure s\'appliquera dans un premier temps du 7 janvier 2010 au 8 avril 2010 compris. «La place de la Liberte a Brest connait regulierement des rassemblements de personnes alcoolisees qui generent des desordres frequemment signales par les riverains et les passants», explique la prefecture du Finistere.\n\n      www.ouest-france.fr';
		var en_france='En France \n\nMardi sera une journee de temps calme et anticyclonique sur tout le pays. Cependant, les hautes pressions n\'induiront pas partout un ciel limpide et ensoleille. Des nuages relatifs a l\'humidite residuelle des derniers jours seront en effet tres presents sur un bon quart nord-ouest, entre la Bretagne, les Pays de la Loire, le Bassin Parisien, la Normandie et le Nord-Pas-de-Calais. Le soleil s\'imposera progressivement sur les autres regions. Les temperatures remonteront un peu partout, sauf la region du Nord-ouest';
		var text8_2011='Le champion de toutes categories de la collecte et du recyclage des sapins de Noel n\'est pas une collectivite mois une entreprise privee: l\'enseigne lkea. [...]\n\nLa fameuse societe des magasins de meubles a mis en place en 2003 une operation appelee «Agir a la racine». \n\nChaque sapin achete 20 € en decembre peut etre echange i la jardinerie d\'lkea en janvier suivant contre un bon d\'achat de 19 €. Pour le consommateur qui en accepte le principe, le cout d\'un sapin ne se monte plus qu\'a 1 €, que l\'enseigne s\'engage a reverser a l\'Office national des forets. \n\nLes sapins recuperes sont recycles en compost. \n\n       La Voix du Nord';
		var text9_2011='EVOLUTION vous accueillera dans une ambiance chaleureuse tres conviviale. Notre equipe tres professionnelle, vous offrira une tasse de cafe et commencera le diagnostic de vos attentes afin de bien vous comprendre. \n\nPhilosophie: \nNous souhailons mettre en avant les bienfaits de l\'arrangement des cheveux sur le morale et sur le dynamique qu\'elle peut generer. \n\nService: \nMorphologie assistee par ordinateur, coupe moderne et classique, couleur, chignon, une tres large palette de services vous sera proposee. \n\nSpecialite: \nChignon marie etc., morphologie, extension \n\nMode de paiement: \nEspece, carte, cheque ';
		var text10_2011='Decus par les recettes du film Avatar projete en 2D a Vitre, les responsables du cinema L\'Aurore ont decide d\'investir dans un nouveau projecteur: «La ou le film est projete en 3D, Avatar fait un carton. Les salies sont encore pleines.» Vitre ne passera done pas a cote de cette revolution techologique: «Le cinema de L\'Aurore sera equipe des cet ete en materiel 3D. Les spectateurs seront equipes de lunettes speciales pour profiter pleinement du relief.» Le prix des billets sera un peu plus eleve (le montant n\'est pas arrete) mais pas suffisamment pour decourager les passionnes.\n\n           www.ouest-france.fr';
		var text12_2011='La police francaise a annonce jeudi l\'arrestation nocturne d\'un crocodile qui circulait tranquillement dans une rue de General Leclerc, une bourgade du departement du Cher (centre). \n\nLes policiers ont ete alertes vers 02h 00 du matin par un appel telephonique affirmant qu\'un crocodile se promenait dans la rue. \n\nEcartant l\'hypothese pourtant vraisemblable d\'une plaisanterie, tes policiers se sont rendus sur les lieux pour decouvrir l\'animal. Quelques heures plus tard, ils retrouvaient ses proprietaires: un petit cirque qui fait actuellement etape dans la ville.';
		var text13_2011='C\'est un document constitue par un ensemble de feuilles qui sont reliees entre elles et souvent protegees par une couverture. Il designe aussi le contenu, cree par un ecrivain et destine a etre lu par d\'autres. Il existe plusieurs types de ce document. On peut citer les documents, qui racontent une histoire, les ecrits documentaires et manuels, scolaires, ou sont reunis Les savoirs d\'un certain domaine, les documents illustres, qui contiennent des images, les bandes dessinees, qui racontent une histoire sous forme de dessins, les documents sous forme electronique diffuses par Internet, etc. Selon les specialistes ce document doit contenir cinquante pages an minimum.';
		var text14_2011='Payer les eleves pour aller a l\'ecole?! \n\nJe suis scandalisee! Moi aussi, je veux bien aller voir un match «gratos» au velodrome! Et si je seche, je ne peux pas y aller, moi, a Marseille. \n\nLes eleves ont avant tout des devoirs, et celui de venir i l\'ecole est incontournable, indiscutable. \n\nIl existe une loi qui prevoit de supprimer les allocations familiales aux familles dont les enfants sont trop absents. Dans les faits, je suis curieuse de savoir si cela existe vraiment et pour combien de demi-journees d\'absence. \n\nIl  faut trouver d\'autres  moyens,  la recompense de  venir a  l\'ecole, c\'est d\'Apprendre!!! \n\nN\'est-ce pas une merveilleuse recompense qu\'il faut valoriser, encourager. \n\nJe ne suis pas sure que donner l\'envie d\'apprendre, d\'apprendre a apprendre vienne avec des billets! \n\n     Le blog de Brun Junod, prof d\' Eps, titulaire volontaire dans un college de ZEP';
		var text15_2011='Les aurores boreales sont de fabuleux phenomenes qui se produisent dans le ciel nocturne. On peut les observer dans des regions proches du pole nord. Ce sont de grandes bandes lumineuses vertes, bleues ou rouges se deplacant plus ou moins vite dans le ciet nocturne polaire. E Iles se forment a une altitude comprise entre 100 et 500 kilometres et peuvent durer plusieurs dizaines de minutes. La cause de ce phenomene est due a notre astre: le soleil. Regulierement, il subit de violentes tempetes et rejette dans l\'espace ce que l\'on appelle des vents solaires. Ceux-ci viennent en contact avec le champ magnetique terrestre qui est une sorte de bouclier pour notre planete. C\'est lors de cette rencontre que se produit le magnifique spectacle des aurores boreales. Le phenomene n\'est pas sans consequence puisqu\'il perturbe les reseaux electriques. GPS et radios peuvent aussi etre perturbes et des vols peuvent etre annules en cas d\'activite importante.';
		var text16_21_2011='    (21)...\n\nI (l6)... A Clichy-so us-Bois, le centre de production de cette patisserie est en pleine essor.\n\nII Le rythme de production s\'est accelere depuis fin octobre pour fabriquer un maximum de gateaux avant Noel et hier encore c\'etait le coup de chaud dans les ateliers de la Romainville.\n\nIII Malgre la surcharge de travail, rien n\'est laisse au hasard dans la centrale de production de la patisserie, basee a Clichy-sous-Bois. Ici, chaque unite a sa specialite: tarte, galette des rois, bavarois... Autour du tapis roulant sur lequel sont mis ces douceurs, une quinzaine d\'employes s\'attaquent aux finitions: glacage, decoration, a chaque geste une fonction.\n\nIV Car si la production ressemble plus a des quantites industrielles qu\'artisanales, «tout est fait a la main (17) car aucune patisserie ne se ressemble exactement», souligne Julie fi loche, responsable qualite.\n\nV  A proximite, de grands bacs remplis de chocolat, de creme vanille feraient perdre conscience n\'importe quel gourmand. Un peu plus loin, les gateaux sont emballes et prets a etre livres dans les 22 magasins du groupe, principalement en region parisienne, mais aussi a Lyon.\n\nVI En cette veille de Noel, l\'entreprise devrait vendre 15 000 buches et gateaux. «Au plus fort de la journee, les clients feront la queue pendant deux heures et demie pour acheter leurs gateaux, sourit Etienne Ortega, directeur general de la Romainville. Depuis quelques annees, nous avons meme du engager des surveillants pendant les feles pour eviter toute mauvaise conduite des clients.» «En temps normal, dans la boutique de Clichy, nous avons deux ou trois vendeurs mais a Noel nous montons a 10 ou 15 et les cadres du groupe descendent des bureaux pour renforcer l\'equipe», explique Julie Filoche. Ils aident a vendre les milliers de buches.\n\nVII (18) Pourtant,  «depuis deux ou trois ans, on assiste a une baisse des ventes de ce type de produit», reconnait Etienne Ortega.. Alors, le laboratoire maison, avec ses 35 patissiers, tente cette annee de proposer autre chose. «Nous avons cree des gateaux relatifs au Noel, qui sont une alternative a la buche, analyse Philippe Gobinet, responsable de production. Nous en avons en forme de Pere Noel, de patinoire... Et ca marche plus tot bien puisque nous avons distribue 3 500 cette annee.»\n\n      Sebastien Thomas\n\n      www. lepurisieii.fr';
		var text22_33_2011='   J\'ai traverse l\'Atlantique a bord de l\'A380\n\n    Une nuit dans le train Rodez-Paris pour rallier lu plateforme de Roissy Charles-de-Gaulle qui accueille depuis quelques jours a peine la nouvelle star de l\'aviation civile, j\'ai nomme l\'A380. A l\'aeroport, precipitation sur la salle d\'embarquement pour etre dans les blocs a fin de decouvrir la bete. Derriere l\'immense baie vitree, (22)_____________de le manquer, on ne voit que lui.\n\n    Son (23)_____________qui nous Tait faee est enorme. Tout le monde se reunit et photographie le geant. Cote piste, un s\'affaire autour de lui, un le prepare pour sa traversee de l\'Atlantique jusqu\'a New York. Des que le top depart est donne puur l\'installation, les 538 passagers se precipitent. Heureusement, l\'embarquement est tres (24)_____________et se fait avec une rigueur militaire.\n\n    On prend place sur le pont inferieur, vers le fond de l\'avion, du cote droit, a peine assis, un sent et on voit la difference. Le hublot est a la taille de l\'appareil et l\'espace entre les rangees est plus(25)____________compare a un Boeing 747. Un ecran insere dans le siege de devant nous reserve un programme d\'une centaine de films, de series tele, et autant d\'albums de musique. Une prise USB permet de se connecter et un clavier d\'envoyer des mails ou de telephoner, a condition, bien sur, d\'inserer sa carte bancaire. Autre fonction tres interessante et (26) _____________ condition, la communication avec un autre siege.\n\n    En attendant, les (27)____________se ferment, le personnel est souriant et une hotesse se confie: c\'est une premiere pour les 24 membres de l\'equipage qui sont tres fiers de voler a bord de l\'A380.\n\n    Probleme: une heure apres, on est toujours colle (28)____________. On n\'arrive pas a decrocher les passerelles d\'embarquement. Certains (29)____________s\'impatientent. Un mot du commandant nous expliquant les (30)____________, et on roule enfin vers la piste. Derriere nous, ranges en file indienne les autres appareils laissent la priorite a la vedette.\n\n    Ca y est, on est (31)____________position, les reacteurs tournent a fond, le titan se transforme en oiseau leger. Ses ailes blanches, dont la taille atteint la largeur d\'un terrain de football, paraissent dans le ciel azur. Et (32)____________qui frappe des la premiere seconde du vol c\'est le silence. Un silence coupe par les bouchons (33)____________qui sautent. Un vol inaugural ca se fete.\n\n       Marie-Christine Bessou \n        www.ladepeche.fr';
		var text34_39_2011='A 7 ans il (34)___________une pelleteuse pour deblayer la neige\n\n   Un garcon de sept ans (35)___________par la police au volant d\'une pelleteuse en train de deblayer la neige sur une roule du nord de la France pour faire plaisir a son pere.\n\n   L\'enfant a explique que son papa avait dit que la route etait sale et qu\'il  «voulait aider». selon un communique de la police. «Voyant les cles sur la serrure de contact, il a saisi l\'occasion» et (36)___________au volant de l\'engin haut de 3,5 metres pour deblayer laneige sur la route.\n\n   Quand il a remarque la police, il a arrete aussitot Le moteur. «Il a ouvert la porte, (37)___________et a reconnu tout de suite ne pas avoir de permis de conduire», selon les agents.\n\n   Au montent ou la police l\'a decouvert, il (38)___________sa tache et voulait reconduire la machine sur le site de l\'entreprise familiale a Laval pres de Brest, ou il l\'(39)___________.\n\n   Les policiers ont remis l\'enfant a sa mere, avec les cles de la pelleteuse. A la place des parents on irait vite lui acheter pour Noel des grues et des engins de chantier... miniatures.\n\n      www.ouest-france.fr';
		var text40_45_2011='   Elle decouvre son frere soixante ans apres\n\n   Elle se croyait fille unique. Colette, une habitante de Suresnes, a appris (40)_________ elle avait un demi-frere allemand, aujourd\'hui age de plus de soixante ans.\n\n   (41)__________vie de Colette Guillard a bascule en une seconde. Ce jour ou, il y a quelques semaines, elle a rencontre son frere pour la premiere fois. Cinq jours plus tot, cette habitante de Suresnes se croyait encore fille unique.\n\n   Tout commence par un coup de fil et une voix d\'homme avec un (42)_________accent germanique qui lui pose des questions precises, notamment sur son pere.\n\n   Son correspondant explique mener (43)__________recherches en filiation depuis quarante ans. «Quand il im\'a dit que mon pere etait aussi le sien, c\'etait un coup de massue», se souvient Colette, des etoiles plein les yeux. Un rendez-vous est finalement cale a Suresnes. Aujourd\'hui, elle revit la scene avec autant d\'intensite: «Je (44)__________ai entendu monter l\'escalier. A chaque pas, mon coeur battait un peu plus vite. J\'ai ouvert la porte, on s\'est regarde sans rien dire. El a souri et, la, j\'ai vu tout le portrait de mon pere. l\'ai eclate (45)_________sanglots. C\'est le moment le plus fort de ma vie.»[...]n\n     www.leparisien.fr';
		gradeArray=new Array("100.0","100.5","101.0","101.0","101.0","103.5","106.0","108.0","111.5","116.5","121.0","124.5","130.5","134.0","138.0","141.0","143.5","146.5","149.0","151.0","153.5","155.0","155.5","156.5","157.0","158.5","159.0","159.5","160.0","161.5","162.5","164.0","164.5","165.0","166.0","167.0","167.5","168.5","169.0","169.5","170.5","171.5","172.5","174.0","175.0","176.5","177.5","179.0","179.5","180.5","181.0","182.0","183.0","184.5","186.0","187.5","190.0","192.5","193.0","194.0","195.0","196.5","197.5","200.0","200.0","200.0","200.0","200.0","200.0","200.0");
		answerArray=new Array("b","d","b","b","a","a","d","a","c","a","d","c","d","b","b","c","a","b","b","c","a","b","c","a","a","c","b","a","c","b","b","c","a","b","a","d","c","b","d","d","b","d","a","b","c"," ");
        taskTypeArray=new Array("textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","test","test","textanalysis","textanalysis","textanalysis","test","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","tvir");
		textAnalysisArray=new Array(inet_annonce,tv_prog,text3_2011,brest,en_france,"test","test",text8_2011,text9_2011,text10_2011,"test",text12_2011,text13_2011,text14_2011,text15_2011,text16_21_2011,text16_21_2011,text16_21_2011,text16_21_2011,text16_21_2011,text16_21_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text22_33_2011,text34_39_2011,text34_39_2011,text34_39_2011,text34_39_2011,text34_39_2011,text34_39_2011,text40_45_2011,text40_45_2011,text40_45_2011,text40_45_2011,text40_45_2011,text40_45_2011,"tvir");
		taskMarkArray=new Array(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,24);
		variantNumberArray=new Array(4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0);
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,"picture",variantNumberArray[i], "vertical", answerLanguage, "", "");
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}		
	}

/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();	
}
