function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/

/*************************************************************/
//Тесты по французскому языку	
/*************************************************************/		
if(testName==znoFra2010Main)
	{
		testLength=51;
		timeCounter=120*60;
		testTime=timeCounter;
		testDirectory='\/test\/fra\/img\/test2010main1\/';
		testTitle = znoName+"2010"+znoFraName;
		testDetails=mainName;
		var Task1='À: Jacques.Lafavre@yaho.fr \n\nCopie: Nadia.Chikou@hitmail.com , Pierre.Arditi@laposte.fr, Alice.Newman@voila.fr, Georges.de.Durand@bmail.com\n\nObjet: petit mot de moi \n\nSalut chers frères et amis(ies), \nJ’étais occupé ces dernières 24 h à une mission urgente et trop importante pour la société où je travaille. Mais je n’ai pas oublié l’esprit d’amitié et d’entraide qui règne dans notre institut et surtout les traditions que nous gardons toujours dans nos coeurs. Je tiens à tous vous féliciter d’avoir exprimé des sentiments si chaleureux envers ceux qui ont réussi leurs examens, la gentillesse touche directement le coeur...';
		var Task2='Le 22 octobre 2008 Airbus A380 a soufflé sa première bougie. Le plus gros avion de voyageurs du monde (500 à 840 places selon ses aménagements) a transporté 700 000 passagers depuis son lancement, il y a un an. C’est le meilleur résultat de l’avion parmi tous les avions des compagnies aériennes.';
		var Task3='Quelques programmes spécifiques...\n\nLe Fonds francophone des inforoutes...\nfinance des projets qui favorisent l’appropriation et l’usage des inforoutes par la création de contenus d’expression française dans des domaines aussi variés que la jeunesse, la culture, l’enseignement, la recherche, l’économie, le droit, la presse, le tourisme ou les arts.\n\nhttp://www. francophonie.org/fonds';
		var Task4='Service d’accueil des Étudiants Étrangers \n39, av. Georges Bernanos\n75005 Paris \nTél.: 01 40 51 36 00 \n\nAttestation de bourse \n\nLe directeur du Centre Régional des OEuvres Universitaires et Scolaires de PARIS atteste que: \nMlle Oxana PETRENKO Dossier nº: 20005198 \nNé(e) le: 25/01/1987 \nPays de nationalité: UKRAINE \nAdresse: 20, rue Zhitomirska, apt.47 \n02345 Kyiv \nest titulaire d’une bourse du Gouvernement Français pour la période du 02/07/2005 au 28/07/2005 \n\nÀ Paris le 03/07/2005 \nLe Directeur du CROUS';
		var Task5='  ESPAGNE\n\nLes enfants du village espagnol de Noblejas (centre) seront désormais payés pour lire. La commune de 3 300 habitants «subventionnera les familles à hauteur d’un euro par heure passée à la bibliothèque» par leurs enfants scolarisés en primaire, a annoncé hier la mairie.\n\nAFP';
		var Task6='   En Belgique, il y a beaucoup de chaînes de télévision. Il est possible de les recevoir avec une antenne ou avec le câble. La plupart des Belges ont le câble. Il permet d\'avoir plus de chaînes de télévision. Les antennes satellites permettent de capter des chaînes du monde entier.\n  Il existe des magazines de télévision. Ils donnent les programmes et les articles sur les émissions. Le journal télévisé est présenté par des journalistes. Pour les autres émissions, ce sont des présentateurs. On dit aussi "animateurs" pour les jeux.';
		var Task7='   PASSEZ ENTRE LES GOUTTES\n\nLes averses sont nombreuses sur l’arc atlantique et le long des côtes de la Manche. Sur un large quart nord-est, de très belles éclaircies sont présentes. Au sud, le temps est perturbé et les précipitations sont soutenues en Corse.';
		var Task8='   Dernière minute\n\nTrop dur, je rentre de vacances. Une folie avec un pote (copain). On est parti tous les deux avec un vol trouvé à la dernière minute. Notre objectif c’était partir le plus loin possible, pour pas cher... On s’est retrouvé au fin fond de l’Inde. Superbe, merveilleux. On n’a rien dépensé, on a dormi dehors, rencontré des gens, mangé local... Je pense qu’on refera ça tous les ans. Ça, c’est la vraie découverte d’un pays et de ses habitants... Par contre le retour est... triste.';
		var Task9='   Pourquoi personne ne porte plus le caïman pour le mettre à l\'eau?\n\nDe Blaise Cendrars. \nPrix:13,50 euros Édition le Sorbier. \n\nParce qu’il n’est pas très gentil? Parce qu’il fait peur? Un peu des deux en fait. Un chasseur courageux peu méfiant porte secours à un caïman qui le supplie de l’aider. Le caïman, une fois sauvé se retourne contre le chasseur, et essaie de le dévorer. Mais un lièvre rusé passe par là. Beau conte africain.';
		var Task10='Pour la première fois depuis le début des années 1950, la capitale gagne des habitants. Selon le dernier recensement, compilé par l’Insee Ile-de-France et rendu public aujourd’hui, la ville comptait 2 181 400 habitants au 1er janvier 2006, soit 56 100 de plus qu’en 1999. Cette progression est uniquement due à un solde naturel plus important (+ 0,7% de croissance annuelle). Car le solde migratoire,lui, restenégatif(-0,4 %).';
		var Task11='  Chère Anita,\n\nJe te remercie pour tes belles photos. J’espère que tu as passé une bonne fin de séjour à Montpellier et un bon voyage de retour. T’es-tu remise pendant le mois d’août des gros efforts réalisés en juillet? Moi, j’ai passé quinze jours splendides en Corse, et maintenant la dure réalité frappe à nouveau à ma porte, les cours vont bientôt recommencer. Enfin, c’est la vie. J’espère continuer à avoir de tes nouvelles.\n\n     Je t’embrasse.\n          José';
		var Task12='  Les rayons solaires sont 8 fois plus puissants dans l’espace qu’une fois arrivés sur le sol terrestre. L’atmosphère protège ainsi la vie sur Terre. Cette puissance des rayons solaires intéresse les chercheurs depuis longtemps. Selon eux, une centrale placée en orbite autour de la Terre pourrait absorber l’énergie solaire et renvoyer beaucoup d’électricité propre sur notre planète, sous la forme d’ondes.\n  Problème important: envoyer du matériel dans l’espace dans une navette coûte actuellement près de 15 000 euros le kilo ...';
		var Task13='  Big Ben est-elle la plus grosse cloche du monde?\n\nContrairement à ce que pourrait laisser penser son nom, Big Ben n’est pas la plus grosse cloche du monde, elle est devancée par l’inutilisé «Tsar Kolokol III» du Kremlin à Moscou qui pèse 212 tonnes (soit plus de 10 fois plus lourde que la cloche anglaise). On estime aujourd’hui à plus de 200 000 le nombre de cloches réparties sur l’ensemble du territoire français.';
		var Task14='  Vous allez partir en France\n\nAvant de quitter votre pays vous devez:\n- retirer votre lettre de présentation à l’Ambassade,\n- vous assurer que l’Ambassade a bien prévenu le CNOUS de votre arrivée en France,\n- vous munir obligatoirement d’une somme de 100 € minimum,\n- vérifier que la validité de votre visa correspond bien à la durée du stage,\n- éviter d’arriver un samedi, un dimanche ou un jour chômé.\n\nNe venez pas en avance, votre hébergement ne pourra être assuré.';
		var Task15='  Leur histoire est liée aux loisirs ouvriers et aux «Dimanches au bord de l’Eau» pour y exercer des activités variées, très souvent liées à l’eau (régates, canotage, natation, joutes, pêche...), mais aussi pour se divertir avec des jeux de foire, de quilles, de boules et balançoires... On s’y attablait pour savourer une cuisine simple servie avec du vin blanc ou rouge: friture ou matelote de poisson, fricassée de lapin. Et puis on y dansait les danses populaires à l’époque: la valse, la polka et plus tard, la valse «Musette».\n  La première moitié du XXe siècle constitue l’âge d’or pour les guinguettes, alors que, au début des années 60, le goût pour les week-ends plus éloignés et de nouveaux types de musiques en annoncent le déclin. De nombreuses guinguettes ont été détruites. Actuellement, quatre d’entre elles sont toujours en activité dans le Val-de-Marne';
		var Task16='  Aussi haut que la dame de fer\n\nURBANISME. La Fondation d’entreprise de la Société de la tour Eiffel lance la première édition du concours d’architecture Eiffel 2008, réservé aux étudiants en architecture des écoles françaises. Individuellement ou en équipe pluridisciplinaire sont invités à concevoir un édifice de très grande hauteur, à distance, accolé ou à la place même de la tour Eiffel. Leurs projets devront tenir compte des réalités environnementales du site, urbaines, sociales, techniques et économiques. Ils devront, également, faire appel aux techniques et matériaux contemporains.\n\n    A.S\nInfos: www.fondationsocietetoureiffel.org';
		var Task17_22='   (22)... .\n\n(18) ... . Et la saison ne fait que commencer! À Dijon, les pompiers sont intervenus plus d’une cinquantaine de fois, principalement pour des inondations de caves, après un violent orage mardi soir. Près d’Avignon, la foudre a blessé six enfants de 11 à 12 ans qui jouaient sur un terrain de football. Météo France a placé 2 départements du sud-ouest en vigilance orange jusqu’à aujourd’hui, cela signifie qu’il y a de forts risques d’inondation dans ces zones.\n(19) ... , que faire en cas d’orage?\nDe façon générale, il faut éviter le plus possible les activités extérieures. Ce n’est pas le moment de sortir ton chien, finir ta partie de foot et encore moins de partir en randonnée. Si malgré tout tu te trouves dehors, quelques règles s’imposent. La première: se débarrasser et s’éloigner de tout objet métallique, ils attirent la foudre. (20) ... , tu ne t’abrites pas sous ton parapluie, tant pis si ça mouille, c’est moins dangereux. Il faut aussi s’éloigner des poteaux électriques et de tout autre objet plus haut que toi, pointu et pointé vers le ciel. Surtout, ne pas s’abriter sous un arbre, et encore moins s’il est isolé. L’idéal est de trouver rapidement un abri de pierre. Si tu n’en trouves pas, roule-toi en boule au sol et attends. Les orages durent rarement plus de trente minutes.\n\n    CÉLINE BOUSQUET';
		var Task23_34='(23)__________ du téléphone portable!\n\nFace aux manques de (24)__________ sur les risques des téléphones portables pour la santé, il faut rester prudent, surtout si tu as moins de douze ans. Voici quelques (25)__________.\n\nLes téléphones portables sont-ils (26)__________? C’est la question que se posent de nombreux scientifiques: (27)__________, nous n’avons pas de réponse définitive concernant leur influence (28)__________ la santé. Pourtant, de plus en plus d’études montrent qu’ils peuvent le (29)__________, surtout chez les enfants de moins de douze ans. En fait, à cet âge-là, tu es plus fragile que les adultes (30)__________ ton corps et tes organes sont en train de se développer.\n\nPour (31)__________ les risques de maladie, des cancérologues viennent de publier (32)__________ de conseils: par exemple, utilise au maximum un kit mains libres, un kit piéton, une oreillette ou un haut-parleur. D’autres gestes simples peuvent aussi être utiles: utilise plutôt les SMS que les appels et ne laisse pas ton portable (33)__________ sur ta table de nuit pendant que tu dors. Et comme dit cette phrase (34)__________ «mieux vaut prévenir que guérir»!\n\n    DELPHINE FABIUS\n\nhttp://www.lesclesjunior.com'
		var Task35_40='   Santé\n\nHalte au surpoids!\n\n«Parce qu’au début, ça ne se voit pas», des centaines de pédiatres (35)__________ ce samedi des informations pour détecter les problèmes de surpoids chez les enfants.\n\n1 enfant sur 6 est trop gros en France. Ce pourcentage (36)__________ très vite en l’espace de 20 ans. Aujourd’hui, il est si (37)__________ que dans une centaine de villes en France, des pédiatres organisent des animations, des conférences et des ateliers pour donner des conseils pour manger (38)__________: c’est la journée nationale de prévention et d’information sur l’obésité infantile. Ces pédiatres insistent aussi sur le dépistage et recommandent d’aller les voir au moins une fois par an. Car un enfant trop gros, cela se voit, peut-on penser. Inutile alors d’aller consulter un docteur. Or, justement, au début ça ne se voit pas… D’où l’importance de consulter un spécialiste. Celui-ci te pèsera et te mesurera. En fonction de ton poids et de ta taille, il (39)__________ en mesure de dire si tu «es juste comme il faut» ou déjà trop gros. Si tel est le cas, ne te vexe pas. Plus ce problème de santé (40)_________ tôt, plus il est facile à soigner. Selon les pédiatres, 9 cas d’obésité sur 10 sont évitables grâce à des règles simples. Pour savoir où rencontrer les pédiatres lors de cette journée nationale de prévention et d’information sur l’obésité infantile, visite le site de l’Association française de pédiatres ambulatoires: www.afpa.org.\n\n     http://www.lesclesjunior.com le 10 janvier 2009';
		var Task41_46='  Les macaques savent compter!\n\nLes hommes ne seraient pas les seuls à savoir compter. Les macaques aussi maîtrisent, comme (41)__________, l’addition.\n\nOn sait depuis longtemps que les singes sont capables de comparer des quantités: (42)___________ réussissent, sans se tromper, à montrer de la patte le pot où il y a le plus de billes. Aujourd’hui, des chercheurs viennent de montrer qu’ils ne savent (43)__________ seulement comparer des quantités. Les singes savent véritablement compter et maîtrisent parfaitement l’addition.\n\nPour montrer l’esprit matheux des singes, les chercheurs ont entraîné (44)__________ guenons (macaques femelles) à compter les sons qu’elles entendaient. Après un certain nombre de «biiiip», les guenons devaient choisir, sur (45)__________écran d’ordinateur, le dessin où apparaissait le même nombre de points. Bilan? 20/20 pour les guenons! Ensuite, les chercheurs ont légèrement compliqué l’exercice: en plus des «biiiip», ils ont ajouté des éclairs de lumière. Les guenons devaient alors additionner le nombre de «biiiip» et d’éclairs. Et, une fois encore, elles ont obtenu de très (46) __________ résultats. C’est prouvé: les macaques savent compter!\n\n       http://www.lesclesjunior.com, le 07 juillet 2008';
		var Task47_50='Akira Kurosawa - Dessinateur\n\nAkira Kurosawa n’était pas que le (47)__________ grand réalisateur japonais.\n\nC’était aussi un peintre et dessinateur d’exception, auquel le Petit Palais (48)__________ hommage en exposant près (49)__________ une centaine d’oeuvres rares, (50)__________ le Vieux meunier, au crayon, aquarelle et pastel. Jusqu’au 11 janvier 2010. \n(http://www.petitpalais.paris.fr).';
		answer47Array=new Array("plus");
		answer48Array=new Array("rend","a rendu","rendait");
		answer49Array=new Array("d'");
		answer50Array=new Array("dont","parmi lesquelles","y compris");
		gradeArray=new Array("100.0","100.5","100.5","101.5","102.0","103.0","106.5","110.5","114.0","116.5","120.5","124.0","127.0","129.5","133.0","135.5","138.0","140.0","141.5","143.0","144.5","145.5","147.0","148.0","149.0","150.0","151.0","152.0","153.0","154.0","154.5","155.0","155.5","156.5","157.5","158.0","158.5","159.5","160.5","161.5","162.0","163.0","164.0","164.5","165.5","166.5","167.5","168.5","169.5","170.5","171.0","172.5","173.5","174.5","175.5","176.5","177.0","178.5","179.5","181.5","182.5","184.0","186.5","187.5","190.0","192.0","193.0","194.5","195.5","197.0","197.5","200.0","200.0","200.0","200.0","200.0","200.0","200.0","200.0");
		answerArray=new Array("c","d","d","a","d","a","b","c","a","b","b","b","c","a","c","a","d","b","b","c","c","b","c","b","d","c","a","c","d","b","c","b","c","d","h","f","a","g","d","b","d","f","b","g","i","a",answer47Array,answer48Array,answer49Array,answer50Array," ");
		taskTypeArray=new Array("textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textanalysis","textual","textual","textual","textual","tvir");
		textAnalysisArray=new Array(Task1,Task2,Task3,Task4,Task5,Task6,Task7,Task8,Task9,Task10,Task11,Task12,Task13,Task14,Task15,Task16,Task17_22,Task17_22,Task17_22,Task17_22,Task17_22,Task17_22,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task23_34,Task35_40,Task35_40,Task35_40,Task35_40,Task35_40,Task35_40,Task41_46,Task41_46,Task41_46,Task41_46,Task41_46,Task41_46,Task47_50,Task47_50,Task47_50,Task47_50,"tvir");
		taskMarkArray=new Array(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,24);
		variantNumberArray=new Array(4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,9,9,9,9,9,9,9,9,9,9,9,9,0,0,0,0,0);
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,"picture",variantNumberArray[i], "vertical", answerLanguage, "", "");
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}			
	}
/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();						
}
