function testInit(testName)
{
	testOficialTitle=testName;
	/*обнуление всех текущих счетчиков*/
	answerCounter=0;
	correctAnswerCounter=0;
	passCounter =0;
	currentTaskCounter=0;
	timeCounter=0;
	testTime=0;
	testLength=0;
	/*Обнуление массива заданий*/
	taskArray=new Array();
	/*Массив правильных ответов*/
	var answerArray=new Array();
	/*Массив типов вопросов теста*/
	var taskTypeArray=new Array();
	/*Массив баллов за правильные ответы*/
	var taskMarkArray=new Array();
	/*Массив названий тестов*/
	var taskNameArray=new Array();
	
	/*Оценки за задания тестов*/
	/*Инициализация тестов в зависимости от названия теста*/

/*************************************************************/
//Тесты по химим
/*************************************************************/	

/*ЗНО-2014 химия. Основной тест. I сессия*/
	if(testName==znoHim2014Main)
	{
		testLength=60;
		timeCounter=150*60;
		testTime=timeCounter;
		testDirectory='\/test\/him\/img\/test2014main\/';
		testTitle = znoName+"2014"+znoHimName;
		testDetails=mainName;
		answerLanguage="rus";
		gradeArray=new Array("100.0","100.5","100.5","100.5","100.5","100.5","100.5","100.5","101.0","102.0","103.5","105.5","108.0","111.5","114.5","117.0","120.0","123.0","125.5","128.0","130.0","132.5","134.5","136.5","138.0","139.5","140.5","142.0","143.5","144.5","145.5","146.5","147.5","148.0","149.0","150.0","150.5","151.5","152.5","153.5","153.5","154.5","155.0","155.5","156.5","157.0","157.5","158.0","158.5","159.5","160.0","160.5","161.0","161.5","162.0","163.0","163.5","164.0","164.5","165.0","165.5","166.0","167.0","167.5","168.0","168.5","169.0","170.0","170.5","171.5","172.0","172.5","173.5","174.0","175.0","175.5","176.5","177.5","178.0","179.0","180.0","181.0","182.0","183.5","184.5","185.5","187.0","188.5","190.0","192.0","193.5","195.5","197.5","198.5","200.0");
		answerArray=new Array();
		taskTypeArray=new Array();
		textAnalysisArray=new Array();
		taskMarkArray=new Array();
		variantNumberArray=new Array();
		directionArray=new Array();
		viewArray=new Array();
		taskTextsArray=new Array();
		var taskNumber=1;
		/*задание №1 ЗНО-2014 химия. Основной тест*/
			taskNumber=1;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть хімічне явище.";
			zadanieArray[1]="випаровування води";
			zadanieArray[2]="плавлення льоду";
			zadanieArray[3]="горіння деревини";
			zadanieArray[4]="подрібнення крейди";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №2 ЗНО-2014 химия. Основной тест*/
			taskNumber=2;
			var zadanieArray=new Array();
			zadanieArray[0]="Скільки електронів в атомі Оксигену?";
			zadanieArray[1]="2";
			zadanieArray[2]="6";
			zadanieArray[3]="8";
			zadanieArray[4]="16";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №3 ЗНО-2014 химия. Основной тест*/
			taskNumber=3;
			var zadanieArray=new Array();
			zadanieArray[0]="У якому рядку найбільше неметалічних елементів?";
			zadanieArray[1]="Al, Au, As";
			zadanieArray[2]="N, Na, Ni";
			zadanieArray[3]="С, Сs, Cr";
			zadanieArray[4]="S, Se, Sс";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №4 ЗНО-2014 химия. Основной тест*/
			taskNumber=4;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть число елементів і число атомів у складі сполуки, формула якої <span style='white-space: nowrap;'>CH<sub>3</sub>COOH.</span>";
			zadanieArray[1]="3 і 7";
			zadanieArray[2]="3 і 8";
			zadanieArray[3]="7 і 7";
			zadanieArray[4]="7 і 9";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №5 ЗНО-2014 химия. Основной тест*/
			taskNumber=5;
			var zadanieArray=new Array();
			zadanieArray[0]="У якому рядку наведено формули лише йонних сполук?"; 
			zadanieArray[1]="MgBr<sub>2</sub>, KF, H<sub>2</sub>";
			zadanieArray[2]="ZnCl<sub>2</sub>, HF, H<sub>2</sub>O";
			zadanieArray[3]="CaI<sub>2</sub>, NH<sub>3</sub>, NaBr";
			zadanieArray[4]="Na<sub>2</sub>S, KCl, CaBr<sub>2</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №6 ЗНО-2014 химия. Основной тест*/
			taskNumber=6;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть порядковий номер хімічного елемента Е, який належить до III&nbsp;періоду періодичної системи й утворює летку сполуку з Гідрогеном складу ЕН<sub>3</sub>."; 
			zadanieArray[1]="5";
			zadanieArray[2]="7";
			zadanieArray[3]="13";
			zadanieArray[4]="15";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №7 ЗНО-2014 химия. Основной тест*/
			taskNumber=7;
			var zadanieArray=new Array();
			zadanieArray[0]="Який тип кристалічних ґраток у бінарній сполуці хімічних елементів із протонними числами 9 і 19?";
			zadanieArray[1]="йонні";
			zadanieArray[2]="молекулярні";
			zadanieArray[3]="атомні";
			zadanieArray[4]="металічні";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №8 ЗНО-2014 химия. Основной тест*/
			taskNumber=8;
			var zadanieArray=new Array();
			zadanieArray[0]="У прилад, що зображений на рисунку, помістили водний розчин речовини <b>Х</b> і тверду речовину <b>Y</b>. Укажіть формули речовин <b>Х</b> і <b>Y</b>.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="singleText_picture";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №9 ЗНО-2014 химия. Основной тест*/
			taskNumber=9;
			var zadanieArray=new Array();
			zadanieArray[0]="Які речовини реагують між собою у водному розчині?";
			zadanieArray[1]="NaСl і Н<sub>2</sub>S";
			zadanieArray[2]="K<sub>2</sub>SО<sub>4</sub> і Al(NO<sub>3</sub>)<sub>3</sub>";
			zadanieArray[3]="NaNO<sub>3</sub> і K<sub>2</sub>СО<sub>3</sub>";
			zadanieArray[4]="AgNO<sub>3</sub> і KCl";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №10 ЗНО-2014 химия. Основной тест*/
			taskNumber=10;
			var zadanieArray=new Array();
			zadanieArray[0]="Необоротна реакція відбувається у водному розчині між";
			zadanieArray[1]="калій хлоридом і купрум(ІІ) нітратом.";
			zadanieArray[2]="натрій сульфатом і калій гідроксидом.";
			zadanieArray[3]="барій хлоридом і сульфатною кислотою.";
			zadanieArray[4]="натрій нітратом і ферум(ІІІ) хлоридом.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №11 ЗНО-2014 химия. Основной тест*/
			taskNumber=11;
			var zadanieArray=new Array();
			zadanieArray[0]="Скільки електронів беруть участь у процесі відновлення Сульфуру за схемою <span style='white-space: nowrap;'>SO<sub>4</sub><sup>2-</sup> &rarr; Н<sub>2</sub>S</span>?";
			zadanieArray[1]="2";
			zadanieArray[2]="4";
			zadanieArray[3]="6";
			zadanieArray[4]="8";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №12 ЗНО-2014 химия. Основной тест*/
			taskNumber=12;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть правильний запис рівняння реакції між ферум(ІІ) гідроксидом і хлоридною кислотою в повній йонній формі.";
			zadanieArray[1]="<span style='white-space: nowrap;'>Fe(OH)<sub>2</sub> + 2HCl = Fe<sup>2+</sup> + Cl<sub>2</sub><sup>-</sup> + 2Н<sub>2</sub>O</span>"; 
			zadanieArray[2]="<span style='white-space: nowrap;'>Fe(OH)<sub>2</sub> + 2H<sup>+</sup> + 2Cl<sup>-</sup> = Fe<sup>2+</sup> + 2Cl<sup>-</sup> + 2Н<sub>2</sub>O</span>";
			zadanieArray[3]="<span style='white-space: nowrap;'>Fe(OH)<sub>2</sub> + 2H<sup>+</sup> + 2Cl<sup>-</sup> = Fe<sup>2+</sup> + 2Cl<sup>-</sup> + 2H<sup>+</sup> + O<sup>2-</sup></span>";
			zadanieArray[4]="<span style='white-space: nowrap;'>Fe<sup>2+</sup> + 2OH<sup>-</sup> + 2H<sup>+</sup> + 2Cl<sup>-</sup> = Fe<sup>2+</sup> + Cl<sub>2</sub><sup>-</sup> + 2H<sup>+</sup> + 2OH<sup>-</sup></span>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №13 ЗНО-2014 химия. Основной тест*/
			taskNumber=13;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть формулу оксиду, який реагує з водою з утворенням лугу.";
			zadanieArray[1]="BaO";
			zadanieArray[2]="ZnO";
			zadanieArray[3]="CuO";
			zadanieArray[4]="FeO";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №14 ЗНО-2014 химия. Основной тест*/
			taskNumber=14;
			var zadanieArray=new Array();
			zadanieArray[0]="Яку з речовин можна добути взаємодією металу з водою?";
			zadanieArray[1]="Fe(OH)<sub>2</sub>";
			zadanieArray[2]="Pb(OH)<sub>2</sub>";
			zadanieArray[3]="Cu(OH)<sub>2</sub>";
			zadanieArray[4]="Ca(OH)<sub>2</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №15 ЗНО-2014 химия. Основной тест*/
			taskNumber=15;
			var zadanieArray=new Array();
			zadanieArray[0]="До складу одноосновної кислоти входять";
			zadanieArray[1]="катіон Гідрогену та аніон кислотного залишку.";
			zadanieArray[2]="аніон Гідрогену та катіон кислотного залишку.";
			zadanieArray[3]="гідроксильна група та аніон кислотного залишку.";
			zadanieArray[4]="карбонільна група та аніон кислотного залишку.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №16 ЗНО-2014 химия. Основной тест*/
			taskNumber=16;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть формулу кислої солі.";
			zadanieArray[1]="(CuOH)<sub>2</sub>CO<sub>3</sub>";
			zadanieArray[2]="Na<sub>2</sub>CO<sub>3</sub>";
			zadanieArray[3]="NaHCO<sub>3</sub>";
			zadanieArray[4]="(NH<sub>4</sub>)<sub>2</sub>CO<sub>3</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №17 ЗНО-2014 химия. Основной тест*/
			taskNumber=17;
			var zadanieArray=new Array();
			zadanieArray[0]="У якому рядку наведено формули лише тих речовин, які виявляють амфотерні властивості?";
			zadanieArray[1]="AlСl<sub>3</sub>, Al<sub>2</sub>O<sub>3</sub>, Al(OH)<sub>3</sub>";
			zadanieArray[2]="Al<sub>2</sub>O<sub>3</sub>, Al(OH)<sub>3</sub>, ZnO";
			zadanieArray[3]="FeO, FeCl<sub>3</sub>, Zn(OH)<sub>2</sub>";
			zadanieArray[4]="NaOH, Ba(OH)<sub>2</sub>, Al(OH)<sub>3</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №18 ЗНО-2014 химия. Основной тест*/
			taskNumber=18;
			var zadanieArray=new Array();
			zadanieArray[0]="Яка речовина реагує із залізом з утворенням ферум(ІІ) хлориду?";
			zadanieArray[1]="Сl<sub>2</sub>";
			zadanieArray[2]="HCl";
			zadanieArray[3]="NaCl";
			zadanieArray[4]="CaCl<sub>2</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №19 ЗНО-2014 химия. Основной тест*/
			taskNumber=19;
			var zadanieArray=new Array();
			zadanieArray[0]="У якій групі періодичної системи (коротка форма) містяться лише металічні елементи?";
			zadanieArray[1]="ІІ";
			zadanieArray[2]="ІV";
			zadanieArray[3]="V";
			zadanieArray[4]="VI";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №20 ЗНО-2014 химия. Основной тест*/
			taskNumber=20;
			var zadanieArray=new Array();
			zadanieArray[0]="Під час виконання домашнього лабораторного досліду учневі потрібно було довести, що складовими порошкоподібного універсального засобу для чищення є карбонати Кальцію і Магнію. Йому вдалося це зробити за допомогою";
			zadanieArray[1]="столового оцту.";
			zadanieArray[2]="нашатирного спирту.";
			zadanieArray[3]="розчину кухонної солі.";
			zadanieArray[4]="розчину питної соди.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="";
		/*задание №21 ЗНО-2014 химия. Основной тест*/
			taskNumber=21;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть формулу речовини, із якою реагує алюміній, якщо внаслідок цього утворюється алюміній сульфат.";
			zadanieArray[1]="S";
			zadanieArray[2]="Н<sub>2</sub>SO<sub>3</sub>";
			zadanieArray[3]="Н<sub>2</sub>SO<sub>4</sub> (розб.)";
			zadanieArray[4]="Н<sub>2</sub>S (газ)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №22 ЗНО-2014 химия. Основной тест*/
			taskNumber=22;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть продукти термічного розкладання ферум(ІІІ) гідроксиду.";
			zadanieArray[1]="FeO і H<sub>2</sub>О";
			zadanieArray[2]="FeO і H<sub>2</sub>О<sub>2</sub>";
			zadanieArray[3]="Fe<sub>2</sub>О<sub>3</sub> і H<sub>2</sub>";
			zadanieArray[4]="Fe<sub>2</sub>О<sub>3</sub> і H<sub>2</sub>О";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №23 ЗНО-2014 химия. Основной тест*/
			taskNumber=23;
			var zadanieArray=new Array();
			zadanieArray[0]="Спільним в електронній будові атомів Хлору та Йоду є";
			zadanieArray[1]="загальне число електронів на енергетичних рівнях.";
			zadanieArray[2]="число енергетичних рівнів, на яких перебувають електрони.";
			zadanieArray[3]="число електронів на зовнішньому енергетичному рівні.";
			zadanieArray[4]="число енергетичних підрівнів, на яких перебувають електрони.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="";
		/*задание №24 ЗНО-2014 химия. Основной тест*/
			taskNumber=24;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть формулу речовини Х у схемі хімічної реакції<p style='text-align:center;'>Сu + Х &rarr; СuSO<sub>4</sub> + SO<sub>2</sub> + H<sub>2</sub>О.</p>";
			zadanieArray[1]="H<sub>2</sub>S";
			zadanieArray[2]="H<sub>2</sub>SO<sub>3</sub>";
			zadanieArray[3]="Н<sub>2</sub>SO<sub>4</sub> (конц.)";
			zadanieArray[4]="Н<sub>2</sub>SO<sub>4</sub> (розб.)";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №25 ЗНО-2014 химия. Основной тест*/
			taskNumber=25;
			var zadanieArray=new Array();
			zadanieArray[0]="Із якою речовиною реагує амоніак?";
			zadanieArray[1]="Na<sub>2</sub>SO<sub>4</sub>";
			zadanieArray[2]="NaOН";
			zadanieArray[3]="Н<sub>2</sub>";
			zadanieArray[4]="Н<sub>2</sub>SO<sub>4</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №26 ЗНО-2014 химия. Основной тест*/
			taskNumber=26;
			var zadanieArray=new Array();
			zadanieArray[0]="Між якими речовинами потрібно провести реакцію, щоб добути карбон(ІV) оксид?";
			zadanieArray[1]="СaSО<sub>4</sub> і Na<sub>2</sub>СО<sub>3</sub>";
			zadanieArray[2]="Са(NО<sub>3</sub>)<sub>2</sub> і Na<sub>2</sub>СО<sub>3</sub>";
			zadanieArray[3]="Са(НСО<sub>3</sub>)<sub>2</sub> і Са(ОН)<sub>2</sub>";
			zadanieArray[4]="СаСО<sub>3</sub> і НNО<sub>3</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №27 ЗНО-2014 химия. Основной тест*/
			taskNumber=27;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть назву речовини, яка належить до гомологічного ряду вуглеводнів із загальною формулою C<sub>n</sub>H<sub>2n-2</sub>.";
			zadanieArray[1]="пропан";
			zadanieArray[2]="пропен";
			zadanieArray[3]="пропін";
			zadanieArray[4]="циклопропан";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №28 ЗНО-2014 химия. Основной тест*/
			taskNumber=28;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть за номенклатурою ІUРАC назву речовини, структурна формула якої";
			zadanieArray[1]="2,5-діетил-4-метилгексан";
			zadanieArray[2]="2,5-діетил-3-метилгексан";
			zadanieArray[3]="3,5,6-триметилоктан";
			zadanieArray[4]="3,4,6-триметилоктан";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table_picture";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №29 ЗНО-2014 химия. Основной тест*/
			taskNumber=29;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть формулу гомолога метану.";
			zadanieArray[1]="С<sub>2</sub>Н<sub>4</sub>";
			zadanieArray[2]="С<sub>3</sub>Н<sub>8</sub>";
			zadanieArray[3]="С<sub>4</sub>Н<sub>6</sub>";
			zadanieArray[4]="С<sub>6</sub>Н<sub>6</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №30 ЗНО-2014 химия. Основной тест*/
			taskNumber=30;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть число структурних ізомерів, що відповідає формулі С<sub>4</sub>Н<sub>8</sub>.";
			zadanieArray[1]="6";
			zadanieArray[2]="5";
			zadanieArray[3]="4";
			zadanieArray[4]="3";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №31 ЗНО-2014 химия. Основной тест*/
			taskNumber=31;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть формулу речовини Х у схемі перетворень <p style='text-align:center;'>CH<sub>4</sub> &rarr; Х &rarr; C<sub>6</sub>H<sub>6</sub>.</p>";
			zadanieArray[1]="C<sub>2</sub>H<sub>2</sub>";
			zadanieArray[2]="C<sub>2</sub>H<sub>4</sub>";
			zadanieArray[3]="CH<sub>3</sub>Сl";
			zadanieArray[4]="CH<sub>3</sub>OН";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №32 ЗНО-2014 химия. Основной тест*/
			taskNumber=32;
			var zadanieArray=new Array(); 
			zadanieArray[0]="Укажіть співвідношення між кількостями речовин бензену й водню в рівнянні хімічної реакції, продуктом якої є циклогексан.";
			zadanieArray[1]="1 : 1";
			zadanieArray[2]="1 : 2";
			zadanieArray[3]="1 : 3";
			zadanieArray[4]="3 : 1";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";			
		/*задание №33 ЗНО-2014 химия. Основной тест*/
			taskNumber=33;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть продукт перегонки нафти.";
			zadanieArray[1]="газойль";
			zadanieArray[2]="поліетилен";
			zadanieArray[3]="етилетаноат";
			zadanieArray[4]="етаналь";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="";
		/*задание №34 ЗНО-2014 химия. Основной тест*/
			taskNumber=34;
			var zadanieArray=new Array();
			zadanieArray[0]="Фенол реагує з";
			zadanieArray[1]="калій гідрогенкарбонатом.";
			zadanieArray[2]="натрій гідроксидом.";
			zadanieArray[3]="калій сульфатом.";
			zadanieArray[4]="гідроген хлоридом.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №35 ЗНО-2014 химия. Основной тест*/
			taskNumber=35;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть формулу речовини Х у схемі хімічної реакції<p style='text-align:center;'>X + Cu(OH)<sub>2</sub> &rarr;<sup>t&deg;</sup>&rarr; CH<sub>3</sub>СООН + Cu<sub>2</sub>O + H<sub>2</sub>O.</p>";
			zadanieArray[1]="CH<sub>3</sub>СНО";
			zadanieArray[2]="CH<sub>3</sub>ОН";
			zadanieArray[3]="HCHO";
			zadanieArray[4]="CH<sub>3</sub>OCH<sub>3</sub>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="a";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №36 ЗНО-2014 химия. Основной тест*/
			taskNumber=36;
			var zadanieArray=new Array();
			zadanieArray[0]="Проаналізуйте твердження й укажіть, чи є поміж них правильні. <p style='color:black; text-indent:-1em; padding-left: 2em;'>I. Добування твердого жиру з олії ґрунтується на реакції гідролізу.</p> <p style='color:black;text-indent:-1em;padding-left:2em;'>II. Добування твердого жиру з олії ґрунтується на реакції гідрування.</p>";
			zadanieArray[1]="правильне лише І";
			zadanieArray[2]="правильне лише ІІ";
			zadanieArray[3]="обидва правильні";
			zadanieArray[4]="немає правильних";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;
			taskNameArray[taskNumber-1]="";
		/*задание №37 ЗНО-2014 химия. Основной тест*/
			taskNumber=37;
			var zadanieArray=new Array();
			zadanieArray[0]="Моносахаридами є";
			zadanieArray[1]="крохмаль і глюкоза.";
			zadanieArray[2]="фруктоза і сахароза.";
			zadanieArray[3]="фруктоза і глюкоза.";
			zadanieArray[4]="сахароза і целюлоза.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="c";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="";
		/*задание №38 ЗНО-2014 химия. Основной тест*/
			taskNumber=38;
			var zadanieArray=new Array();
			zadanieArray[0]="Які твердження характеризують аміноетанову кислоту?<p style='color:black; text-indent:-1em; padding-left: 2em;'>1 використовують для добування капрону</p> <p style='color:black; text-indent:-1em; padding-left: 2em;'>2 можна одержати гідролізом білка</p> <p style='color:black; text-indent:-1em; padding-left: 2em;'>3 містить лише одну функціональну групу</p> <p style='color:black; text-indent:-1em; padding-left: 2em;'>4 є амфотерною сполукою</p>";
			zadanieArray[1]="1, 3";
			zadanieArray[2]="1, 4";
			zadanieArray[3]="2, 3";
			zadanieArray[4]="2, 4";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="horizontal";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="d";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №39 ЗНО-2014 химия. Основной тест*/
			taskNumber=39;
			var zadanieArray=new Array();
			zadanieArray[0]="Під час лабораторного досліду учениця поклала зразок поліетилену на керамічну підставку й обережно нагріла. Коли полімер розм’якшився, вона за допомогою скляної палички змінила форму зразка. Охолоджений зразок знову нагріла і знову змінила його форму. Це свідчить про те, що досліджуваний полімер є";
			zadanieArray[1]="термореактивним.";
			zadanieArray[2]="термопластичним.";
			zadanieArray[3]="еластичним.";
			zadanieArray[4]="міцним.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="";
		/*задание №40 ЗНО-2014 химия. Основной тест*/
			taskNumber=40;
			var zadanieArray=new Array();
			zadanieArray[0]="Укажіть речовину X у схемі хімічної реакції<p style='text-align:center;'>СH<sub>3</sub>СOONa &rarr;<sup>NaOH, t&deg;</sup>&rarr; X + Na<sub>2</sub>СO<sub>3</sub>.</p>";
			zadanieArray[1]="етанол";
			zadanieArray[2]="метан";
			zadanieArray[3]="етан";
			zadanieArray[4]="метаналь";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="b";
			taskTypeArray[taskNumber-1]="test";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=1;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="";
		/*задание №41 ЗНО-2014 химия. Основной тест*/
		/*Dodelat*/
			taskNumber=41;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між схемою та типом хімічної реакції.";
			zadanieArray[1]="<span style='white-space: nowrap ;'>Na<sub>2</sub>O+H<sub>2</sub>O&rarr;NaOH</span>";
			zadanieArray[2]="<span style='white-space: nowrap ;'>KOH+H<sub>3</sub>PO<sub>4</sub>&rarr;K<sub>3</sub>PO<sub>4</sub>+H<sub>2</sub>O</span>";
			zadanieArray[3]="<span style='white-space: nowrap ;'>H<sub>2</sub>O<sub>2</sub>&rarr;H<sub>2</sub>O+O<sub>2</sub></span>";
			zadanieArray[4]="<span style='white-space: nowrap ;'>Ca+H<sub>2</sub>O&rarr;Ca(OH)<sub>2</sub>+H<sub>2</sub></sub></span>";
			zadanieArray[5]="обміну";
			zadanieArray[6]="заміщення";
			zadanieArray[7]="полімеризації";
			zadanieArray[8]="розкладу";
			zadanieArray[9]="сполучення";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="eadb";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";			
		/*задание №42 ЗНО-2014 химия. Основной тест*/
			taskNumber=42;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між схемою та типом хімічної реакції.";
			zadanieArray[1]="<span style='white-space: nowrap ;'>nH<sub>2</sub>N–(СН<sub>2</sub>)<sub>5</sub>–СООН&rarr;(–HN–(СН<sub>2</sub>)<sub>5</sub>–СO–)<sub>n</sub>+nH<sub>2</sub>O</span>";
			zadanieArray[2]="<span style='white-space: nowrap ;'>CH<sub>3</sub>COOH+C<sub>2</sub>H<sub>5</sub>OH&rarr;СH<sub>3</sub>COOC<sub>2</sub>H<sub>5</sub>+H<sub>2</sub>O</span>";
			zadanieArray[3]="<span style='white-space: nowrap ;'>С<sub>2</sub>H<sub>4</sub>+H<sub>2</sub>O&rarr;С<sub>2</sub>H<sub>5</sub>OH</span>";
			zadanieArray[4]="<span style='white-space: nowrap ;'>nС<sub>2</sub>H<sub>4</sub>&rarr;(–СH<sub>2</sub>–СH<sub>2</sub>–)<sub>n</sub></span>";
			zadanieArray[5]="гідратації";
			zadanieArray[6]="полімеризації";
			zadanieArray[7]="поліконденсації";
			zadanieArray[8]="естерифікації";
			zadanieArray[9]="гідрування";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="cdab";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;			
			taskNameArray[taskNumber-1]="";
		/*задание №43 ЗНО-2014 химия. Основной тест*/
			taskNumber=43;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між тривіальною назвою та формулою речовини.";
			zadanieArray[1]="гіпс";
			zadanieArray[2]="алебастр";
			zadanieArray[3]="негашене вапно";
			zadanieArray[4]="кальцинована сода";
			zadanieArray[5]="<span style='white-space: nowrap ;'>CaSO<sub>4</sub> · 0,5H<sub>2</sub>O</span>";
			zadanieArray[6]="NaNO<sub>3</sub>";
			zadanieArray[7]="<span style='white-space: nowrap ;'>CaSO<sub>4</sub> · 2H<sub>2</sub>O</span>";
			zadanieArray[8]="Na<sub>2</sub>CO<sub>3</sub>";
			zadanieArray[9]="CaO";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="caed";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №44 ЗНО-2014 химия. Основной тест*/
			taskNumber=44;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між формулою та природою речовини.";
			zadanieArray[1]="<span style='white-space: nowrap ;'>H<sub>2</sub>SО<sub>3</sub></span>";
			zadanieArray[2]="<span style='white-space: nowrap ;'>Mg<sub>3</sub>(PO<sub>4</sub>)<sub>2</sub></span>";
			zadanieArray[3]="<span style='white-space: nowrap ;'>Ca(OH)<sub>2</sub></span>";
			zadanieArray[4]="<span style='white-space: nowrap ;'>CaO</span>";
			zadanieArray[5]="кислотний оксид";
			zadanieArray[6]="кислота";
			zadanieArray[7]="основний оксид";
			zadanieArray[8]="основа";
			zadanieArray[9]="сіль";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="bedc";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №45 ЗНО-2014 химия. Основной тест*/
			taskNumber=45;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між формулою та природою речовини.";
			zadanieArray[1]="<span style='white-space: nowrap ;'>С<sub>2</sub>H<sub>2</sub></span>";
			zadanieArray[2]="<span style='white-space: nowrap ;'>С<sub>6</sub>H<sub>5</sub>NH<sub>2</sub></span>";
			zadanieArray[3]="<span style='white-space: nowrap ;'>CH<sub>3</sub>OH</span>";
			zadanieArray[4]="<span style='white-space: nowrap ;'>HCHO</span>";
			zadanieArray[5]="альдегід";
			zadanieArray[6]="спирт";
			zadanieArray[7]="амінокислота";
			zadanieArray[8]="алкін";
			zadanieArray[9]="амін";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="deba";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №46 ЗНО-2014 химия. Основной тест*/
			taskNumber=46;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть відповідність між назвою речовини та одним зі способів її добування.";
			zadanieArray[1]="анілін";
			zadanieArray[2]="фенол";
			zadanieArray[3]="глюкоза";
			zadanieArray[4]="етаналь";
			zadanieArray[5]="гідроліз хлоробензену";
			zadanieArray[6]="гідратація ацетилену";
			zadanieArray[7]="термічне розкладання метану";
			zadanieArray[8]="гідроліз крохмалю";
			zadanieArray[9]="відновлення нітробензену";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="connection";
			answerArray[taskNumber-1]="eadb";
			taskTypeArray[taskNumber-1]="connect";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=4;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №47 ЗНО-2014 химия. Основной тест*/
			taskNumber=47;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть послідовність використання процесів і речовин під час здійснення ланцюжка перетворень <p style='white-space: nowrap;text-align:center;'>Fe<sup>0</sup> &rarr; Fe<sup>2+</sup> &rarr; Fe(OH)<sub>2</sub> &rarr; Fe(OH)<sub>3</sub> &rarr; Fe<sub>2</sub>О<sub>3</sub>.</p>";
			zadanieArray[1]="нагрівання";
			zadanieArray[2]="кисень і вода";
			zadanieArray[3]="бромідна кислота";
			zadanieArray[4]="натрій гідроксид";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="cdba";
			taskTypeArray[taskNumber-1]="ordernew";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=3;
			variantNumberArray[taskNumber-1]=4;	
			taskNameArray[taskNumber-1]="";
		/*задание №48 ЗНО-2014 химия. Основной тест*/
			taskNumber=48;
			var zadanieArray=new Array();
			zadanieArray[0]="Установіть послідовність використання речовин під час добування метанової кислоти.";
			zadanieArray[1]="метаналь";
			zadanieArray[2]="метан";
			zadanieArray[3]="хлорометан";
			zadanieArray[4]="метанол";			
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="table";
			answerArray[taskNumber-1]="bcda";
			taskTypeArray[taskNumber-1]="ordernew";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=3;
			variantNumberArray[taskNumber-1]=4;		
			taskNameArray[taskNumber-1]="";
		/*задание №49 ЗНО-2014 химия. Основной тест*/
			taskNumber=49;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть відносну молекулярну масу речовини, формула якої <span style='white-space: nowrap;'>CH<sub>3</sub>NHC<sub>2</sub>H<sub>5</sub>.</span>";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="alphabetic";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=59;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
		/*задание №50 ЗНО-2014 химия. Основной тест*/
			taskNumber=50;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть відносну молекулярну масу газу, відносна густина якого за киснем дорівнює 2.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="alphabetic";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=64;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
		/*задание №51 ЗНО-2014 химия. Основной тест*/
			taskNumber=51;
			var zadanieArray=new Array();
			zadanieArray[0]="Масова частка води в кристалогідраті натрій сульфіту становить 50&nbsp;%. Укажіть число молекул води у формулі цього кристалогідрату."; 
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="alphabetic";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=7;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;
			taskNameArray[taskNumber-1]="";
		/*задание №52 ЗНО-2014 химия. Основной тест*/
			taskNumber=52;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть об’єм (л) водню масою <span style='white-space: nowrap;'>5 г (н. у.)</span>.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=56;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";			
		/*задание №53 ЗНО-2014 химия. Основной тест*/
			taskNumber=53;
			var zadanieArray=new Array();
			zadanieArray[0]="Скільки різновидів молекул води може утворитися з нукліда Оксигену <sup>16</sup>O та ізотопів Гідрогену <sup>1</sup>Н, <sup>2</sup>Н і <sup>3</sup>Н?";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=6;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №54 ЗНО-2014 химия. Основной тест */
			taskNumber=54;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть масу (г) Фосфору у фосфор(V) оксиді кількістю речовини 0,5&nbsp;моль.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=31;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №55 ЗНО-2014 химия. Основной тест*/
			taskNumber=55;
			var zadanieArray=new Array();
			zadanieArray[0]="На суміш масою 10&nbsp;г, що складається із заліза та міді, подіяли надлишком розбавленої сульфатної кислоти, унаслідок чого виділився газ об’ємом 2,8&nbsp;л (н.&nbsp;у.). Обчисліть масову частку&nbsp;(%) заліза в суміші.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=70;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]="";
		/*задание №56 ЗНО-2014 химия. Основной тест*/
			taskNumber=56;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть масу&nbsp;(г) кухонної солі, яку потрібно взяти для приготування фізіологічного розчину масою 9&nbsp;кг із масовою часткою солі 0,9&nbsp;%.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=81;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]="";
		/*задание №57 ЗНО-2014 химия. Основной тест*/
			taskNumber=57;
			var zadanieArray=new Array();
			zadanieArray[0]="Для проведення реакції взято метал масою 9,2&nbsp;г і воду в надлишку. Унаслідок реакції виділився водень кількістю речовини 0,2&nbsp;моль і утворився гідроксид одновалентного металічного елемента. Визначте молярну масу&nbsp;(г/моль) металу.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=23;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;		
			taskNameArray[taskNumber-1]="";
		/*задание №58 ЗНО-2014 химия. Основной тест*/
			taskNumber=58;
			var zadanieArray=new Array();
			zadanieArray[0]="Обчисліть масу&nbsp;(г) продукту реакції, для проведення якої взято водень масою 4&nbsp;г і бром масою 160&nbsp;г, якщо відносний вихід продукту реакції становить 50&nbsp;%.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=81;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №59 ЗНО-2014 химия. Основной тест*/
			taskNumber=59;
			var zadanieArray=new Array();
			zadanieArray[0]="Використовуючи метод електронного балансу, перетворіть схему реакції <p style='white-space: nowrap;text-align:center;'>KMnO<sub>4</sub> + HCl &rarr; KCl + MnCl<sub>2</sub> + Cl<sub>2</sub> + Н<sub>2</sub>O</p> на хімічне рівняння та вкажіть коефіцієнт перед формулою окисника.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=2;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;	
			taskNameArray[taskNumber-1]="";
		/*задание №60 ЗНО-2014 химия. Основной тест*/
			taskNumber=60;
			var zadanieArray=new Array();
			zadanieArray[0]="Виведіть молекулярну формулу органічної речовини, що складається з Карбону, Гідрогену та Оксигену. Масова частка Карбону в ній становить 72&nbsp;%, Гідрогену – 12&nbsp;%. Відносна густина пари цієї речовини за воднем дорівнює 50. У відповіді запишіть число, що дорівнює сумі індексів у виведеній формулі.";
			taskTextsArray[taskNumber-1]=zadanieArray;
			directionArray[taskNumber-1]="vertical";
			viewArray[taskNumber-1]="singleText";
			answerArray[taskNumber-1]=19;
			taskTypeArray[taskNumber-1]="numeric";
			textAnalysisArray[taskNumber-1]="";
			taskMarkArray[taskNumber-1]=2;
			variantNumberArray[taskNumber-1]=5;			
			taskNameArray[taskNumber-1]="";
		/*Завершение инициализации теста*/	
		for (var i=0; i<testLength; i++)
		{
			curView=new view(testName,i+1,testDirectory,viewArray[i],variantNumberArray[i], directionArray[i], answerLanguage, taskTextsArray[i],taskNameArray[i]);
			taskArray[i]=new task(taskTypeArray[i],taskMarkArray[i],answerArray[i],curView);
		}
	}	/* Окончание ЗНО-2014 химия. Основной тест. I сессия*/	
	
	

/*Завершение инициализации тестов*/
/*Заполнение поля дано ответов*/

		startInitialization();
}
